/*
 * LoginFlow — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.URL;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class LoginFlow {

    private AppiumDriver driver;

    @BeforeMethod
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        options.setAppPackage("com.example.app");
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL("http://localhost:4723"), options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Condition-based wait budget for locating elements. */
    private static final Duration TIMEOUT = Duration.ofSeconds(10);

    /**
     * Locate an element, waiting for it to appear and self-healing through ranked
     * alternatives — each poll tries every locator until one resolves or we time
     * out. A real condition-based wait, not an instant lookup that flakes on async UI.
     */
    private WebElement find(By primary, By[] fallbacks) {
        List<By> locators = new ArrayList<>();
        locators.add(primary);
        locators.addAll(Arrays.asList(fallbacks));
        try {
            return new WebDriverWait(driver, TIMEOUT).until(d -> {
                for (By by : locators) {
                    try {
                        return d.findElement(by);
                    } catch (NoSuchElementException ignored) {
                    }
                }
                return null;
            });
        } catch (TimeoutException e) {
            throw new NoSuchElementException(
                "No locator matched within " + TIMEOUT.getSeconds() + "s (primary + " + fallbacks.length + " fallbacks)");
        }
    }

    @Test
    public void login() {
        // Open app
        driver.activateApp("com.example.app");
        // Enter email
        find(AppiumBy.id("user_field"), new By[]{AppiumBy.xpath("//input[1]")}).sendKeys("alice@example.com");
        // Tap login
        find(AppiumBy.accessibilityId("login_btn"), new By[]{}).click();
        // Wait for home
        // Condition-based: wait for the screen to render rather than a global implicit wait.
        new WebDriverWait(driver, Duration.ofSeconds(3)).until(d -> !d.findElements(By.xpath("//*")).isEmpty());
        // Dismiss a dialog
        driver.navigate().back();
        // Welcome message shown
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")"), new By[]{}).isDisplayed());
    }

}
