Feature: Search products screen
  What the Search products screen of com.example.shop shows and does.
  Auto-generated by Mobiscout. Regenerate rather than hand-edit.

  Scenario: The search products screen shows its expected controls
    Given I am on the Search products screen
    Then I see Running Shoes on the Search products screen
    And I see Backpack
    And I see Cart
