package mobiscout.tests

import mobiscout.pages.RunningShoesPage
import mobiscout.pages.SearchProductsPage
import mobiscout.pages.WelcomeBackPage
import mobiscout.support.BaseTest
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Tests for the Running Shoes screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class RunningShoesTest : BaseTest() {

    @Test
    fun `The running shoes screen shows its expected controls`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        val searchProductsPage = welcomeBackPage.tapSignIn()
        val runningShoesPage = searchProductsPage.tapRunningShoes()
        assertTrue(runningShoesPage.hasRunningShoes())
        assertTrue(runningShoesPage.isDisplayed())
    }
}
