package mobiscout.tests

import mobiscout.pages.SearchProductsPage
import mobiscout.pages.WelcomeBackPage
import mobiscout.support.BaseTest
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Tests for the Search products screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class SearchProductsTest : BaseTest() {

    @Test
    fun `The search products screen shows its expected controls`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        val searchProductsPage = welcomeBackPage.tapSignIn()
        assertTrue(searchProductsPage.isDisplayed())
        assertTrue(searchProductsPage.hasRunningShoes())
        assertTrue(searchProductsPage.hasBackpack())
        assertTrue(searchProductsPage.hasCart())
    }
}
