package mobiscout.tests

import mobiscout.pages.WelcomeBackPage
import mobiscout.support.BaseTest
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Tests for the Welcome back screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class WelcomeBackTest : BaseTest() {

    @Test
    fun `The welcome back screen shows its expected controls`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        assertTrue(welcomeBackPage.isDisplayed())
        assertTrue(welcomeBackPage.hasEmail())
        assertTrue(welcomeBackPage.hasPassword())
        assertTrue(welcomeBackPage.hasRememberMe())
        assertTrue(welcomeBackPage.hasSignIn())
        assertTrue(welcomeBackPage.hasForgotPassword())
    }

    @Test
    fun `Submitting the welcome back form with invalid data is rejected`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("not-an-email")
        welcomeBackPage.enterPassword("1")
        welcomeBackPage.tapSignIn()
        assertTrue(welcomeBackPage.isDisplayed())
    }

    @Test
    fun `Submitting the welcome back form with empty fields is rejected`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("")
        welcomeBackPage.enterPassword("")
        welcomeBackPage.tapSignIn()
        assertTrue(welcomeBackPage.isDisplayed())
    }

    @Test
    fun `The welcome back form survives too-long input`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("x".repeat(300))
        welcomeBackPage.enterPassword("x".repeat(300))
        welcomeBackPage.tapSignIn()
        assertTrue(welcomeBackPage.isAppRunning())
    }

    @Test
    fun `The welcome back form survives special characters`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("!@#\$%^&*()_+-=[]{};:,.?/~`'")
        welcomeBackPage.enterPassword("!@#\$%^&*()_+-=[]{};:,.?/~`'")
        welcomeBackPage.tapSignIn()
        assertTrue(welcomeBackPage.isAppRunning())
    }
}
