package mobiscout.tests

import mobiscout.pages.RunningShoesPage
import mobiscout.pages.SearchProductsPage
import mobiscout.pages.WelcomeBackPage
import mobiscout.pages.YourCartPage
import mobiscout.support.BaseTest
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Tests for the Your cart screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class YourCartTest : BaseTest() {

    @Test
    fun `The your cart screen shows its expected controls`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        val searchProductsPage = welcomeBackPage.tapSignIn()
        val yourCartPage = searchProductsPage.tapCart()
        assertTrue(yourCartPage.isDisplayed())
        assertTrue(yourCartPage.hasPlaceOrder())
    }

    @Test
    fun `The journey from Welcome back through Search products, Running Shoes to Your cart`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("test@example.com")
        welcomeBackPage.enterPassword("Password123!")
        welcomeBackPage.tapRememberMe()
        val searchProductsPage = welcomeBackPage.tapSignIn()
        assertTrue(searchProductsPage.isDisplayed())
        searchProductsPage.enterSearchProducts("test")
        val runningShoesPage = searchProductsPage.tapRunningShoes()
        assertTrue(runningShoesPage.isDisplayed())
        val yourCartPage = runningShoesPage.tapAddToCart()
        assertTrue(yourCartPage.isDisplayed())
    }

    @Test
    fun `The journey from Welcome back through Search products to Your cart`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        welcomeBackPage.enterEmail("test@example.com")
        welcomeBackPage.enterPassword("Password123!")
        welcomeBackPage.tapRememberMe()
        val searchProductsPage = welcomeBackPage.tapSignIn()
        assertTrue(searchProductsPage.isDisplayed())
        searchProductsPage.enterSearchProducts("test")
        val yourCartPage = searchProductsPage.tapCart()
        assertTrue(yourCartPage.isDisplayed())
    }
}
