/*
 * CrawlFlow — auto-generated by Mobiscout.
 * Auto-generated from an autonomous crawl (state + navigation).
 * App under test: com.example.shop
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.URL;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CrawlFlow {

    private AppiumDriver driver;

    @BeforeMethod
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        options.setAppPackage("com.example.shop");
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL("http://localhost:4723"), options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Condition-based wait budget for locating elements. */
    private static final Duration TIMEOUT = Duration.ofSeconds(10);

    /**
     * Locate an element, waiting for it to appear and self-healing through ranked
     * alternatives — each poll tries every locator until one resolves or we time
     * out. A real condition-based wait, not an instant lookup that flakes on async UI.
     */
    private WebElement find(By primary, By[] fallbacks) {
        List<By> locators = new ArrayList<>();
        locators.add(primary);
        locators.addAll(Arrays.asList(fallbacks));
        try {
            return new WebDriverWait(driver, TIMEOUT).until(d -> {
                for (By by : locators) {
                    try {
                        return d.findElement(by);
                    } catch (NoSuchElementException ignored) {
                    }
                }
                return null;
            });
        } catch (TimeoutException e) {
            throw new NoSuchElementException(
                "No locator matched within " + TIMEOUT.getSeconds() + "s (primary + " + fallbacks.length + " fallbacks)");
        }
    }

    /** A generic loading indicator (no app-specific knowledge) — used by settle(). */
    private static final String BUSY_XPATH = "//android.widget.ProgressBar";

    /**
     * Middle beat of {@code act -> wait-busy-clears -> assert}: after an action that
     * triggers a transition, wait for a loading/activity indicator to disappear so the
     * next step doesn't act on a mid-transition screen. A no-op when nothing is
     * spinning; a stuck indicator is tolerated, not failed.
     */
    private void settle() {
        try {
            new WebDriverWait(driver, TIMEOUT).until(d -> d.findElements(By.xpath(BUSY_XPATH)).isEmpty());
        } catch (TimeoutException ignored) {
        }
    }

    @Test
    public void welcomeBackScreenShowsExpectedControls() {
        // Open app
        driver.activateApp("com.example.shop");
        // Welcome back is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome back\")"), new By[]{}).isDisplayed());
        // Email is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).isDisplayed());
        // Email is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).isEnabled());
        // Password is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).isDisplayed());
        // Password is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).isEnabled());
        // Remember me is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).isDisplayed());
        // Remember me is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).isEnabled());
        // Sign in is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).isDisplayed());
        // Sign in is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).isEnabled());
        // Forgot password? is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/forgot"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Forgot password?\")")}).isDisplayed());
        // Forgot password? is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/forgot"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Forgot password?\")")}).isEnabled());
    }

    @Test
    public void searchProductsScreenShowsExpectedControls() {
        // Open app
        driver.activateApp("com.example.shop");
        // Navigate: tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Search products is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Search products is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isEnabled());
        // Running Shoes is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).isDisplayed());
        // Running Shoes is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).isEnabled());
        // Backpack is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_bag"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")")}).isDisplayed());
        // Backpack is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_bag"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")")}).isEnabled());
        // Cart is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).isDisplayed());
        // Cart is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).isEnabled());
    }

    @Test
    public void runningShoesScreenShowsExpectedControls() {
        // Open app
        driver.activateApp("com.example.shop");
        // Navigate: tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Navigate: tap Running Shoes
        find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).click();
        settle();
        // Running Shoes is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"), new By[]{}).isDisplayed());
        // Add to cart is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).isDisplayed());
        // Add to cart is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).isEnabled());
    }

    @Test
    public void yourCartScreenShowsExpectedControls() {
        // Open app
        driver.activateApp("com.example.shop");
        // Navigate: tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Navigate: tap Cart
        find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).click();
        settle();
        // Your cart is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
        // Place order is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/order"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")}).isDisplayed());
        // Place order is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/order"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")}).isEnabled());
    }

    @Test
    public void tappingSignInOpensSearchProducts() {
        // Open app
        driver.activateApp("com.example.shop");
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Destination screen is shown
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
    }

    @Test
    public void journeyFromSignInToAddToCart() {
        // Open app
        driver.activateApp("com.example.shop");
        // Type into Email
        find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).sendKeys("test@example.com");
        settle();
        // Type into Password
        find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).sendKeys("Password123!");
        settle();
        // Toggle Remember me
        find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).click();
        settle();
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Reached screen 2
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Type into Search products
        find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).sendKeys("test");
        settle();
        // Tap Running Shoes
        find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).click();
        settle();
        // Reached screen 3
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"), new By[]{}).isDisplayed());
        // Tap Add to cart
        find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).click();
        settle();
        // Reached screen 4
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
    }

    @Test
    public void journeyFromSignInToCart() {
        // Open app
        driver.activateApp("com.example.shop");
        // Type into Email
        find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).sendKeys("test@example.com");
        settle();
        // Type into Password
        find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).sendKeys("Password123!");
        settle();
        // Toggle Remember me
        find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).click();
        settle();
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Reached screen 2
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Type into Search products
        find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).sendKeys("test");
        settle();
        // Tap Cart
        find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).click();
        settle();
        // Reached screen 4
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
    }

    @Test
    public void rejectsInvalidInputOnWelcomeBack() {
        // Open app
        driver.activateApp("com.example.shop");
        // Type invalid data into Email
        find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).sendKeys("not-an-email");
        settle();
        // Type invalid data into Password
        find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).sendKeys("1");
        settle();
        // Submit Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        settle();
        // Invalid input is rejected — the form did not advance
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).isDisplayed());
    }

}
