/*
 * CrawlFlow — auto-generated by Mobile Test Recorder.
 * Auto-generated from an autonomous crawl (state + navigation).
 * App under test: com.example.shop
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebElement;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.URL;
import java.time.Duration;

public class CrawlFlow {

    private AppiumDriver driver;

    @BeforeMethod
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        options.setAppPackage("com.example.shop");
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL("http://localhost:4723"), options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Locate an element, falling back through ranked alternatives (self-healing). */
    private WebElement find(By primary, By[] fallbacks) {
        try {
            return driver.findElement(primary);
        } catch (NoSuchElementException ignored) {
        }
        for (By by : fallbacks) {
            try {
                return driver.findElement(by);
            } catch (NoSuchElementException ignored) {
            }
        }
        throw new NoSuchElementException("No locator matched (primary + " + fallbacks.length + " fallbacks)");
    }

    @Test
    public void screen1State() {
        // Open app
        driver.activateApp("com.example.shop");
        // Welcome back is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome back\")"), new By[]{}).isDisplayed());
        // Email is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).isDisplayed());
        // Email is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).isEnabled());
        // Password is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).isDisplayed());
        // Password is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).isEnabled());
        // Remember me is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).isDisplayed());
        // Remember me is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).isEnabled());
        // Sign in is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).isDisplayed());
        // Sign in is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).isEnabled());
    }

    @Test
    public void screen2State() {
        // Open app
        driver.activateApp("com.example.shop");
        // Search products is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Search products is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isEnabled());
        // Running Shoes is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).isDisplayed());
        // Running Shoes is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).isEnabled());
        // Backpack is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_bag"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")")}).isDisplayed());
        // Backpack is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/p_bag"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")")}).isEnabled());
        // Cart is visible
        Assert.assertTrue(find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).isDisplayed());
        // Cart is enabled
        Assert.assertTrue(find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).isEnabled());
    }

    @Test
    public void screen3State() {
        // Open app
        driver.activateApp("com.example.shop");
        // Running Shoes is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"), new By[]{}).isDisplayed());
        // Add to cart is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).isDisplayed());
        // Add to cart is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).isEnabled());
    }

    @Test
    public void screen4State() {
        // Open app
        driver.activateApp("com.example.shop");
        // Your cart is visible
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
        // Place order is visible
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/order"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")}).isDisplayed());
        // Place order is enabled
        Assert.assertTrue(find(AppiumBy.id("com.example.shop:id/order"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")}).isEnabled());
    }

    @Test
    public void navigate1() {
        // Open app
        driver.activateApp("com.example.shop");
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        // Destination screen is shown
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
    }

    @Test
    public void path1234() {
        // Open app
        driver.activateApp("com.example.shop");
        // Type into Email
        find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).sendKeys("test@example.com");
        // Type into Password
        find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).sendKeys("Password123!");
        // Toggle Remember me
        find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).click();
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        // Reached screen 2
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Type into Search products
        find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).sendKeys("test");
        // Tap Running Shoes
        find(AppiumBy.id("com.example.shop:id/p_shoes"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")}).click();
        // Reached screen 3
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"), new By[]{}).isDisplayed());
        // Tap Add to cart
        find(AppiumBy.id("com.example.shop:id/add"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")}).click();
        // Reached screen 4
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
    }

    @Test
    public void path124() {
        // Open app
        driver.activateApp("com.example.shop");
        // Type into Email
        find(AppiumBy.accessibilityId("Email"), new By[]{AppiumBy.id("com.example.shop:id/email")}).sendKeys("test@example.com");
        // Type into Password
        find(AppiumBy.accessibilityId("Password"), new By[]{AppiumBy.id("com.example.shop:id/password")}).sendKeys("Password123!");
        // Toggle Remember me
        find(AppiumBy.id("com.example.shop:id/remember"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")}).click();
        // Tap Sign in
        find(AppiumBy.id("com.example.shop:id/signin"), new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")}).click();
        // Reached screen 2
        Assert.assertTrue(find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).isDisplayed());
        // Type into Search products
        find(AppiumBy.accessibilityId("Search products"), new By[]{AppiumBy.id("com.example.shop:id/search")}).sendKeys("test");
        // Tap Cart
        find(AppiumBy.accessibilityId("Cart"), new By[]{AppiumBy.id("com.example.shop:id/cart")}).click();
        // Reached screen 4
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"), new By[]{}).isDisplayed());
    }

}
