"""
Step definitions for LoginFlow — auto-generated by Mobiscout.

Generic, reusable pytest-bdd steps. Element targets are resolved through the
LOCATORS registry below (primary locator + ranked fallbacks for self-healing),
so the .feature file stays free of locator detail.
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from pytest_bdd import given, when, then, parsers, scenarios

scenarios("features/login_flow.feature")

APP_PACKAGE = "com.example.app"
APP_ACTIVITY = ".MainActivity"

# Condition-based wait budget (seconds) — poll for the element instead of a fixed
# sleep or a global implicit wait, so steps stay in sync with async UI.
TIMEOUT = 10

# Friendly target name -> ranked locators (primary first, then fallbacks).
LOCATORS = {
    "user_field": [(AppiumBy.ID, "user_field"), (AppiumBy.XPATH, "//input[1]")],
    "login_btn": [(AppiumBy.ACCESSIBILITY_ID, "login_btn")],
    "Welcome": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome\")")],
}


def _find(driver, target):
    """Resolve a friendly target to an element, waiting for it to appear and
    self-healing through its ranked locators — a condition-based wait, not an
    instant lookup that flakes on async screens."""
    locators = LOCATORS[target]

    def _locate(drv):
        for by, value in locators:
            try:
                return drv.find_element(by, value)
            except NoSuchElementException:
                continue
        return False

    try:
        return WebDriverWait(driver, TIMEOUT, poll_frequency=0.3).until(_locate)
    except TimeoutException:
        raise NoSuchElementException(f"No locator matched for target: {target!r} within {TIMEOUT}s")


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = APP_PACKAGE
    options.app_activity = APP_ACTIVITY
    drv = webdriver.Remote("http://localhost:4723", options=options)
    yield drv
    drv.quit()


@given("the app is launched")
def _launch(driver):
    driver.activate_app(APP_PACKAGE)


@when(parsers.parse('I enter "{text}" into "{target}"'))
def _enter(driver, text, target):
    _find(driver, target).send_keys(text)


@when(parsers.parse('I tap "{target}"'))
def _tap(driver, target):
    _find(driver, target).click()


@when(parsers.parse("I wait {seconds:d} seconds"))
def _wait(driver, seconds):
    # Condition-based: wait for the screen to render rather than a global implicit wait.
    WebDriverWait(driver, seconds).until(lambda d: d.find_elements(AppiumBy.XPATH, "//*"))


@when("I press back")
def _back(driver):
    driver.back()


@when(parsers.parse('I long-press "{target}"'))
def _long_press(driver, target):
    driver.execute_script("mobile: longClickGesture", {"elementId": _find(driver, target).id, "duration": 1000})


@when(parsers.parse('I scroll to "{target}"'))
def _scroll_to(driver, target):
    selector = 'new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().textContains("%s"))'
    driver.find_element(AppiumBy.ANDROID_UIAUTOMATOR, selector % target)


@when(parsers.parse('I open the deep link "{url}"'))
def _deep_link(driver, url):
    driver.get(url)


@when(parsers.parse('I press the "{key}" key'))
def _press_key(driver, key):
    codes = {"BACK": 4, "HOME": 3, "ENTER": 66, "TAB": 61, "SEARCH": 84, "APP_SWITCH": 187, "DEL": 67}
    driver.press_keycode(codes.get(key.upper(), 0))


@then(parsers.parse('"{target}" is visible'))
def _visible(driver, target):
    assert _find(driver, target).is_displayed()


@then(parsers.parse('"{target}" text is "{expected}"'))
def _text_equals(driver, target, expected):
    assert _find(driver, target).text == expected


@then(parsers.parse('"{target}" is enabled'))
def _enabled(driver, target):
    assert _find(driver, target).is_enabled()
