"""
Steps on the Running Shoes screen — each one a call on a page object.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pytest_bdd import given, then, when

from pages.running_shoes_page import RunningShoesPage
from pages.welcome_back_page import WelcomeBackPage


@given("I am on the Running Shoes screen")
def on_running_shoes_screen(driver):
    assert WelcomeBackPage(driver).tap_sign_in().tap_running_shoes().is_displayed()


@when("I tap Add to cart")
def tap_add_to_cart(driver):
    RunningShoesPage(driver).tap_add_to_cart()


@then("I see Running Shoes on the Running Shoes screen")
def see_running_shoes(driver):
    assert RunningShoesPage(driver).has_running_shoes()


@then("I see the Running Shoes screen")
def see_running_shoes_screen(driver):
    assert RunningShoesPage(driver).is_displayed()
