"""
Steps on the Search products screen — each one a call on a page object.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pytest_bdd import given, parsers, then, when

from pages.search_products_page import SearchProductsPage
from pages.welcome_back_page import WelcomeBackPage


@given("I am on the Search products screen")
def on_search_products_screen(driver):
    assert WelcomeBackPage(driver).tap_sign_in().is_displayed()


@when(parsers.parse('I enter "{value}" into Search products'))
def enter_search_products(driver, value):
    SearchProductsPage(driver).enter_search_products(value)


@when("I tap Running Shoes")
def tap_running_shoes(driver):
    SearchProductsPage(driver).tap_running_shoes()


@when("I tap Cart")
def tap_cart(driver):
    SearchProductsPage(driver).tap_cart()


@then("I see Running Shoes on the Search products screen")
def see_running_shoes(driver):
    assert SearchProductsPage(driver).has_running_shoes()


@then("I see Backpack")
def see_backpack(driver):
    assert SearchProductsPage(driver).has_backpack()


@then("I see Cart")
def see_cart(driver):
    assert SearchProductsPage(driver).has_cart()


@then("I see the Search products screen")
def see_search_products_screen(driver):
    assert SearchProductsPage(driver).is_displayed()
