/**
 * Steps on the Running Shoes screen — each one a call on a page object.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import { Given, When, Then } from '@wdio/cucumber-framework';

import welcomeBackPage from '../../test/pageobjects/welcome-back.page.js';
import searchProductsPage from '../../test/pageobjects/search-products.page.js';
import runningShoesPage from '../../test/pageobjects/running-shoes.page.js';

Given('I am on the Running Shoes screen', async () => {
    await welcomeBackPage.tapSignIn();
    await searchProductsPage.tapRunningShoes();
    expect(await runningShoesPage.isDisplayed()).toBe(true);
});

When('I tap Add to cart', async () => {
    await runningShoesPage.tapAddToCart();
});

Then('I see Running Shoes on the Running Shoes screen', async () => {
    expect(await runningShoesPage.hasRunningShoes()).toBe(true);
});

Then('I see the Running Shoes screen', async () => {
    expect(await runningShoesPage.isDisplayed()).toBe(true);
});
