/**
 * Steps on the Search products screen — each one a call on a page object.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import { Given, When, Then } from '@wdio/cucumber-framework';

import welcomeBackPage from '../../test/pageobjects/welcome-back.page.js';
import searchProductsPage from '../../test/pageobjects/search-products.page.js';

Given('I am on the Search products screen', async () => {
    await welcomeBackPage.tapSignIn();
    expect(await searchProductsPage.isDisplayed()).toBe(true);
});

When('I enter {string} into Search products', async (value) => {
    await searchProductsPage.enterSearchProducts(value);
});

When('I tap Running Shoes', async () => {
    await searchProductsPage.tapRunningShoes();
});

When('I tap Cart', async () => {
    await searchProductsPage.tapCart();
});

Then('I see Running Shoes on the Search products screen', async () => {
    expect(await searchProductsPage.hasRunningShoes()).toBe(true);
});

Then('I see Backpack', async () => {
    expect(await searchProductsPage.hasBackpack()).toBe(true);
});

Then('I see Cart', async () => {
    expect(await searchProductsPage.hasCart()).toBe(true);
});

Then('I see the Search products screen', async () => {
    expect(await searchProductsPage.isDisplayed()).toBe(true);
});
