/**
 * Steps on the Welcome back screen — each one a call on a page object.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import { Given, When, Then } from '@wdio/cucumber-framework';

import welcomeBackPage from '../../test/pageobjects/welcome-back.page.js';

Given('I am on the Welcome back screen', async () => {
    expect(await welcomeBackPage.isDisplayed()).toBe(true);
});

When('I enter {string} into Email', async (value) => {
    await welcomeBackPage.enterEmail(value);
});

When('I enter {string} into Password', async (value) => {
    await welcomeBackPage.enterPassword(value);
});

When('I tap Sign in', async () => {
    await welcomeBackPage.tapSignIn();
});

When('I enter 300 characters into Email', async () => {
    await welcomeBackPage.enterEmail('x'.repeat(300));
});

When('I enter 300 characters into Password', async () => {
    await welcomeBackPage.enterPassword('x'.repeat(300));
});

When('I tap Remember me', async () => {
    await welcomeBackPage.tapRememberMe();
});

Then('I see Email', async () => {
    expect(await welcomeBackPage.hasEmail()).toBe(true);
});

Then('I see Password', async () => {
    expect(await welcomeBackPage.hasPassword()).toBe(true);
});

Then('I see Remember me', async () => {
    expect(await welcomeBackPage.hasRememberMe()).toBe(true);
});

Then('I see Sign in', async () => {
    expect(await welcomeBackPage.hasSignIn()).toBe(true);
});

Then('I see Forgot password?', async () => {
    expect(await welcomeBackPage.hasForgotPassword()).toBe(true);
});

Then('I am still on the Welcome back screen', async () => {
    expect(await welcomeBackPage.isDisplayed()).toBe(true);
});

Then('the app is still running', async () => {
    expect(await welcomeBackPage.isAppRunning()).toBe(true);
});
