/**
 * Steps on the Your cart screen — each one a call on a page object.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import { Given, Then } from '@wdio/cucumber-framework';

import welcomeBackPage from '../../test/pageobjects/welcome-back.page.js';
import searchProductsPage from '../../test/pageobjects/search-products.page.js';
import yourCartPage from '../../test/pageobjects/your-cart.page.js';

Given('I am on the Your cart screen', async () => {
    await welcomeBackPage.tapSignIn();
    await searchProductsPage.tapCart();
    expect(await yourCartPage.isDisplayed()).toBe(true);
});

Then('I see Place order', async () => {
    expect(await yourCartPage.hasPlaceOrder()).toBe(true);
});

Then('I see the Your cart screen', async () => {
    expect(await yourCartPage.isDisplayed()).toBe(true);
});
