package mobiscout.pages

import io.appium.java_client.AppiumBy
import io.appium.java_client.AppiumDriver

/**
 * The Running Shoes screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class RunningShoesPage(driver: AppiumDriver) : BasePage(driver) {

    override val screen = "Running Shoes"

    override val identity: String? = "add_to_cart"

    override val locators = mapOf(
        "running_shoes" to listOf(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")),
        "e_89_00" to listOf(AppiumBy.androidUIAutomator("new UiSelector().text(\"\$89.00\")")),
        "add_to_cart" to listOf(AppiumBy.id("com.example.shop:id/add"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")),
    )

    /** Tap Add to cart — opens the Your cart screen. */
    fun tapAddToCart(): YourCartPage {
        tap("add_to_cart")
        return YourCartPage(driver)
    }

    /** Whether Running Shoes is shown. */
    fun hasRunningShoes(): Boolean = isVisible("running_shoes")
}
