package mobiscout.pages

import io.appium.java_client.AppiumBy
import io.appium.java_client.AppiumDriver

/**
 * The Search products screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class SearchProductsPage(driver: AppiumDriver) : BasePage(driver) {

    override val screen = "Search products"

    override val identity: String? = "search_products"

    override val locators = mapOf(
        "search_products" to listOf(AppiumBy.accessibilityId("Search products"), AppiumBy.id("com.example.shop:id/search")),
        "running_shoes" to listOf(AppiumBy.id("com.example.shop:id/p_shoes"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")")),
        "backpack" to listOf(AppiumBy.id("com.example.shop:id/p_bag"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")")),
        "cart" to listOf(AppiumBy.accessibilityId("Cart"), AppiumBy.id("com.example.shop:id/cart")),
    )

    /** Type [value] into Search products. */
    fun enterSearchProducts(value: String): SearchProductsPage = apply { type("search_products", value) }

    /** Tap Running Shoes — opens the Running Shoes screen. */
    fun tapRunningShoes(): RunningShoesPage {
        tap("running_shoes")
        return RunningShoesPage(driver)
    }

    /** Tap Backpack. */
    fun tapBackpack(): SearchProductsPage = apply { tap("backpack") }

    /** Tap Cart — opens the Your cart screen. */
    fun tapCart(): YourCartPage {
        tap("cart")
        return YourCartPage(driver)
    }

    /** Whether Backpack is shown. */
    fun hasBackpack(): Boolean = isVisible("backpack")

    /** Whether Cart is shown. */
    fun hasCart(): Boolean = isVisible("cart")

    /** Whether Running Shoes is shown. */
    fun hasRunningShoes(): Boolean = isVisible("running_shoes")
}
