package mobiscout.pages

import io.appium.java_client.AppiumBy
import io.appium.java_client.AppiumDriver

/**
 * The Welcome back screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class WelcomeBackPage(driver: AppiumDriver) : BasePage(driver) {

    override val screen = "Welcome back"

    override val identity: String? = "welcome_back"

    override val locators = mapOf(
        "welcome_back" to listOf(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome back\")")),
        "email" to listOf(AppiumBy.accessibilityId("Email"), AppiumBy.id("com.example.shop:id/email")),
        "password" to listOf(AppiumBy.accessibilityId("Password"), AppiumBy.id("com.example.shop:id/password")),
        "remember_me" to listOf(AppiumBy.id("com.example.shop:id/remember"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")")),
        "sign_in" to listOf(AppiumBy.id("com.example.shop:id/signin"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")")),
        "forgot_password" to listOf(AppiumBy.id("com.example.shop:id/forgot"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Forgot password?\")")),
    )

    /** Type [value] into Email. */
    fun enterEmail(value: String): WelcomeBackPage = apply { type("email", value) }

    /** Type [value] into Password. */
    fun enterPassword(value: String): WelcomeBackPage = apply { type("password", value) }

    /** Tap Remember me. */
    fun tapRememberMe(): WelcomeBackPage = apply { tap("remember_me") }

    /** Tap Sign in — opens the Search products screen. */
    fun tapSignIn(): SearchProductsPage {
        tap("sign_in")
        return SearchProductsPage(driver)
    }

    /** Tap Forgot password?. */
    fun tapForgotPassword(): WelcomeBackPage = apply { tap("forgot_password") }

    /** Whether Email is shown. */
    fun hasEmail(): Boolean = isVisible("email")

    /** Whether Forgot password? is shown. */
    fun hasForgotPassword(): Boolean = isVisible("forgot_password")

    /** Whether Password is shown. */
    fun hasPassword(): Boolean = isVisible("password")

    /** Whether Remember me is shown. */
    fun hasRememberMe(): Boolean = isVisible("remember_me")

    /** Whether Sign in is shown. */
    fun hasSignIn(): Boolean = isVisible("sign_in")
}
