package mobiscout.pages

import io.appium.java_client.AppiumBy
import io.appium.java_client.AppiumDriver

/**
 * The Your cart screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
class YourCartPage(driver: AppiumDriver) : BasePage(driver) {

    override val screen = "Your cart"

    override val identity: String? = "your_cart"

    override val locators = mapOf(
        "your_cart" to listOf(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")")),
        "place_order" to listOf(AppiumBy.id("com.example.shop:id/order"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")),
    )

    /** Tap Place order. */
    fun tapPlaceOrder(): YourCartPage = apply { tap("place_order") }

    /** Whether Place order is shown. */
    fun hasPlaceOrder(): Boolean = isVisible("place_order")
}
