"""
Steps on the Search products screen — each one a call on a page object.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from behave import given, then, when

from pages.search_products_page import SearchProductsPage
from pages.welcome_back_page import WelcomeBackPage


@given("I am on the Search products screen")
def on_search_products_screen(context):
    assert WelcomeBackPage(context.driver).tap_sign_in().is_displayed()


@when('I enter "{value}" into Search products')
def enter_search_products(context, value):
    SearchProductsPage(context.driver).enter_search_products(value)


@when("I tap Running Shoes")
def tap_running_shoes(context):
    SearchProductsPage(context.driver).tap_running_shoes()


@when("I tap Cart")
def tap_cart(context):
    SearchProductsPage(context.driver).tap_cart()


@then("I see Running Shoes on the Search products screen")
def see_running_shoes(context):
    assert SearchProductsPage(context.driver).has_running_shoes()


@then("I see Backpack")
def see_backpack(context):
    assert SearchProductsPage(context.driver).has_backpack()


@then("I see Cart")
def see_cart(context):
    assert SearchProductsPage(context.driver).has_cart()


@then("I see the Search products screen")
def see_search_products_screen(context):
    assert SearchProductsPage(context.driver).is_displayed()
