"""
Steps on the Welcome back screen — each one a call on a page object.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from behave import given, then, when

from pages.welcome_back_page import WelcomeBackPage


@given("I am on the Welcome back screen")
def on_welcome_back_screen(context):
    assert WelcomeBackPage(context.driver).is_displayed()


@when('I enter "{value}" into Email')
def enter_email(context, value):
    WelcomeBackPage(context.driver).enter_email(value)


@when('I enter "{value}" into Password')
def enter_password(context, value):
    WelcomeBackPage(context.driver).enter_password(value)


@when("I tap Sign in")
def tap_sign_in(context):
    WelcomeBackPage(context.driver).tap_sign_in()


@when("I enter 300 characters into Email")
def enter_300_characters_into_email(context):
    WelcomeBackPage(context.driver).enter_email("x" * 300)


@when("I enter 300 characters into Password")
def enter_300_characters_into_password(context):
    WelcomeBackPage(context.driver).enter_password("x" * 300)


@when("I tap Remember me")
def tap_remember_me(context):
    WelcomeBackPage(context.driver).tap_remember_me()


@then("I see Email")
def see_email(context):
    assert WelcomeBackPage(context.driver).has_email()


@then("I see Password")
def see_password(context):
    assert WelcomeBackPage(context.driver).has_password()


@then("I see Remember me")
def see_remember_me(context):
    assert WelcomeBackPage(context.driver).has_remember_me()


@then("I see Sign in")
def see_sign_in(context):
    assert WelcomeBackPage(context.driver).has_sign_in()


@then("I see Forgot password?")
def see_forgot_password(context):
    assert WelcomeBackPage(context.driver).has_forgot_password()


@then("I am still on the Welcome back screen")
def still_on_welcome_back_screen(context):
    assert WelcomeBackPage(context.driver).is_displayed()


@then("the app is still running")
def app_is_running(context):
    assert WelcomeBackPage(context.driver).is_app_running()
