"""
Steps on the Your cart screen — each one a call on a page object.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from behave import given, then

from pages.welcome_back_page import WelcomeBackPage
from pages.your_cart_page import YourCartPage


@given("I am on the Your cart screen")
def on_your_cart_screen(context):
    assert WelcomeBackPage(context.driver).tap_sign_in().tap_cart().is_displayed()


@then("I see Place order")
def see_place_order(context):
    assert YourCartPage(context.driver).has_place_order()


@then("I see the Your cart screen")
def see_your_cart_screen(context):
    assert YourCartPage(context.driver).is_displayed()
