"""
CrawlFlow — auto-generated by Mobiscout.
Auto-generated from an autonomous crawl (state + navigation).
App under test: com.example.shop
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import json
import os

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds). We poll for the element instead of a
# fixed sleep or a global implicit wait (which silently fights explicit waits),
# so tests stay in sync with async UI without paying a worst-case sleep every step.
_TIMEOUT = 10

# A generic "busy" indicator per platform — used by _settle to wait out a
# transition. Not app-specific, so it's a no-op on screens that show no spinner.
_BUSY_XPATH = "//android.widget.ProgressBar"


def _settle(driver, timeout=_TIMEOUT):
    """Middle beat of ``act -> wait-busy-clears -> assert``: after an action that
    triggers a transition, wait for a loading/activity indicator to disappear so the
    next step doesn't act on a mid-transition screen or read a stale result. A no-op
    when nothing is spinning; a stuck indicator is tolerated, not failed."""
    try:
        WebDriverWait(driver, timeout, poll_frequency=0.3).until(
            lambda d: not d.find_elements(AppiumBy.XPATH, _BUSY_XPATH)
        )
    except TimeoutException:
        pass


def _find(driver, primary, fallbacks, timeout=_TIMEOUT):
    """Locate an element, waiting for it to appear and self-healing through ranked
    fallback locators.

    Each poll tries every locator (primary first) until one resolves or the wait
    times out — a real condition-based wait, so a slow/async screen no longer flakes
    the way an instant ``find_element`` does at machine speed.
    """
    locators = [primary, *fallbacks]

    def _locate(drv):
        for by, value in locators:
            try:
                return drv.find_element(by, value)
            except NoSuchElementException:
                continue
        return False

    try:
        return WebDriverWait(driver, timeout, poll_frequency=0.3).until(_locate)
    except TimeoutException:
        by, value = primary
        raise NoSuchElementException(
            f"None of the locators matched within {timeout}s (primary + {len(fallbacks)} fallbacks): {by}={value}"
        )


# Test input data, kept out of the test body so it changes in one place (and can be
# parameterised or pulled from a fixture later) instead of being coupled inline. Each
# (field, value) a case types gets a unique key, so a positive and a negative case on
# the same field both survive here instead of one overwriting the other.
TEST_DATA = {
    "email": "test@example.com",
    "password": "Password123!",
    "search_products": "test",
    "email_2": "not-an-email",
    "password_2": "1",
}


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = "com.example.shop"
    options.app_activity = ".MainActivity"
    # A fresh session per test with a reset app = isolated, parallel-safe state.
    options.set_capability("noReset", False)
    # Run anywhere without regenerating: point at a different Appium/cloud-grid hub
    # with MOBISCOUT_APPIUM_SERVER, and merge extra capabilities (e.g. a
    # BrowserStack/Sauce options block) from MOBISCOUT_EXTRA_CAPS (a JSON object).
    for _cap, _value in json.loads(os.environ.get("MOBISCOUT_EXTRA_CAPS", "{}")).items():
        options.set_capability(_cap, _value)
    _server = os.environ.get("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723")
    drv = webdriver.Remote(_server, options=options)
    yield drv
    drv.quit()


def test_welcome_back_screen_shows_expected_controls(driver):
    """The welcome back screen shows its expected controls"""
    # Open app
    driver.activate_app("com.example.shop")
    # Welcome back is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome back\")"), []).is_displayed()
    # Email is visible
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).is_displayed()
    # Email is enabled
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).is_enabled()
    # Password is visible
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).is_displayed()
    # Password is enabled
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).is_enabled()
    # Remember me is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/remember"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")]).is_displayed()
    # Remember me is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/remember"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")]).is_enabled()
    # Sign in is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).is_displayed()
    # Sign in is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).is_enabled()
    # Forgot password? is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/forgot"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Forgot password?\")")]).is_displayed()
    # Forgot password? is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/forgot"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Forgot password?\")")]).is_enabled()

def test_search_products_screen_shows_expected_controls(driver):
    """The search products screen shows its expected controls"""
    # Open app
    driver.activate_app("com.example.shop")
    # Navigate: tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Search products is visible
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).is_displayed()
    # Search products is enabled
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).is_enabled()
    # Running Shoes is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/p_shoes"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")]).is_displayed()
    # Running Shoes is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/p_shoes"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")]).is_enabled()
    # Backpack is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/p_bag"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")]).is_displayed()
    # Backpack is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/p_bag"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")]).is_enabled()
    # Cart is visible
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).is_displayed()
    # Cart is enabled
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).is_enabled()

def test_running_shoes_screen_shows_expected_controls(driver):
    """The running shoes screen shows its expected controls"""
    # Open app
    driver.activate_app("com.example.shop")
    # Navigate: tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Navigate: tap Running Shoes
    _find(driver, (AppiumBy.ID, "com.example.shop:id/p_shoes"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")]).click()
    _settle(driver)
    # Running Shoes is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")"), []).is_displayed()
    # Add to cart is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/add"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")]).is_displayed()
    # Add to cart is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/add"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")]).is_enabled()

def test_your_cart_screen_shows_expected_controls(driver):
    """The your cart screen shows its expected controls"""
    # Open app
    driver.activate_app("com.example.shop")
    # Navigate: tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Navigate: tap Cart
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).click()
    _settle(driver)
    # Your cart is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")"), []).is_displayed()
    # Place order is visible
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/order"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")]).is_displayed()
    # Place order is enabled
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/order"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")]).is_enabled()

def test_tapping_sign_in_opens_search_products(driver):
    """Tapping Sign in opens the search products screen"""
    # Open app
    driver.activate_app("com.example.shop")
    # Tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Destination screen is shown
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).is_displayed()

def test_journey_from_sign_in_to_add_to_cart(driver):
    """Multi-step path (4 screens): screen 1 → screen 2 → screen 3 → screen 4"""
    # Open app
    driver.activate_app("com.example.shop")
    # Type into Email
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).send_keys(TEST_DATA["email"])
    _settle(driver)
    # Type into Password
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).send_keys(TEST_DATA["password"])
    _settle(driver)
    # Toggle Remember me
    _find(driver, (AppiumBy.ID, "com.example.shop:id/remember"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")]).click()
    _settle(driver)
    # Tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Reached screen 2
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).is_displayed()
    # Type into Search products
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).send_keys(TEST_DATA["search_products"])
    _settle(driver)
    # Tap Running Shoes
    _find(driver, (AppiumBy.ID, "com.example.shop:id/p_shoes"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")]).click()
    _settle(driver)
    # Reached screen 3
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")"), []).is_displayed()
    # Tap Add to cart
    _find(driver, (AppiumBy.ID, "com.example.shop:id/add"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")]).click()
    _settle(driver)
    # Reached screen 4
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")"), []).is_displayed()

def test_journey_from_sign_in_to_cart(driver):
    """Multi-step path (3 screens): screen 1 → screen 2 → screen 4"""
    # Open app
    driver.activate_app("com.example.shop")
    # Type into Email
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).send_keys(TEST_DATA["email"])
    _settle(driver)
    # Type into Password
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).send_keys(TEST_DATA["password"])
    _settle(driver)
    # Toggle Remember me
    _find(driver, (AppiumBy.ID, "com.example.shop:id/remember"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")]).click()
    _settle(driver)
    # Tap Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Reached screen 2
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).is_displayed()
    # Type into Search products
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]).send_keys(TEST_DATA["search_products"])
    _settle(driver)
    # Tap Cart
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).click()
    _settle(driver)
    # Reached screen 4
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")"), []).is_displayed()

def test_rejects_invalid_input_on_welcome_back(driver):
    """Submitting invalid data on the welcome back form is rejected"""
    # Open app
    driver.activate_app("com.example.shop")
    # Type invalid data into Email
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).send_keys(TEST_DATA["email_2"])
    _settle(driver)
    # Type invalid data into Password
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).send_keys(TEST_DATA["password_2"])
    _settle(driver)
    # Submit Sign in
    _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).click()
    _settle(driver)
    # Invalid input is rejected — the form did not advance
    assert _find(driver, (AppiumBy.ID, "com.example.shop:id/signin"), [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")]).is_displayed()

