"""
Cucumber-JVM renderers — Java (Maven) and Kotlin (Gradle) — on top of the JVM page objects.

Both read the same feature files as every other BDD target and run on the JUnit Platform::

    pom.xml | build.gradle.kts
    src/test/resources/features/<screen>.feature     one per screen
    src/test/<lang>/mobiscout/RunCucumberTest         the JUnit Platform suite
    src/test/<lang>/mobiscout/support/Session, Hooks  one session per run + app restart per scenario
    src/test/<lang>/mobiscout/pages/                  the page objects
    src/test/<lang>/mobiscout/steps/<Screen>Steps     one call on a page object per step

A step definition is one call on a page object::

    @When("I enter {string} into Email")
    public void enterEmail(String value) {
        new WelcomeBackPage(driver()).enterEmail(value);
    }
"""

from __future__ import annotations

from typing import Dict, List, Set, Tuple

from framework.codegen.bdd_model import BddModel, StepDef, build_bdd_model, render_feature
from framework.codegen.emitters._java_common import java_str
from framework.codegen.emitters._kotlin_common import kotlin_str
from framework.codegen.emitters._naming import camel, pascal, snake
from framework.codegen.framework_java import _env as _java_env
from framework.codegen.framework_java import java_value, render_java
from framework.codegen.framework_kotlin import _env as _kotlin_env
from framework.codegen.framework_kotlin import kotlin_value, render_kotlin
from framework.codegen.framework_model import FrameworkModel
from framework.codegen.scaffold import APPIUM_JAVA_CLIENT_VERSION, SELENIUM_VERSION

CUCUMBER_VERSION = "7.34.9"
JUNIT_VERSION = "5.14.4"

_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."
_FEATURES = "src/test/resources/features"
_ANNOTATION = {"Given": "Given", "When": "When", "Then": "Then"}


def _method(d: StepDef) -> str:
    """The step method's name — what the step does, unique within its page's step class."""
    page, el = pascal(d.page), pascal(d.element or "")
    return {
        "arrive": f"on{page}Screen",
        "tap": f"tap{el}",
        "enter": f"enter{el}",
        "enter_long": f"enter{len(d.sample or '')}CharactersInto{el}",
        "is_displayed": f"see{page}Screen",
        "stays": f"stillOn{page}Screen",
        "has": f"see{el}",
        "lacks": f"notSee{el}",
        "text_is": f"{camel(d.element or '')}Shows",
        "is_enabled": f"{camel(d.element or '')}IsEnabled",
        "app_running": "appIsRunning",
        "back": "goBack",
    }[d.op]


def _call(bm: BddModel, d: StepDef, new: str, driver: str) -> Tuple[str, Set[str]]:
    """(the step's one statement without its terminator, the page classes it constructs).
    ``new`` is the constructor prefix (``"new "`` in Java), ``driver`` the session accessor."""
    fm = bm.fm
    page = fm.page(d.page)
    el, cls = d.element or "", page.class_name
    obj = f"{new}{cls}({driver})"
    if d.op == "arrive":
        if not d.path:
            return f"assertTrue({obj}.isDisplayed())", {cls}
        start = fm.page(d.path[0].page).class_name
        chain = "".join(f".tap{pascal(c.element or '')}()" for c in d.path)
        return f"assertTrue({new}{start}({driver}){chain}.isDisplayed())", {start}
    statement = {
        "tap": f"{obj}.tap{pascal(el)}()",
        "enter": f"{obj}.enter{pascal(el)}(value)",
        "enter_long": f"{obj}.enter{pascal(el)}({java_value(d.sample) if new else kotlin_value(d.sample)})",
        "is_displayed": f"assertTrue({obj}.isDisplayed())",
        "stays": f"assertTrue({obj}.isDisplayed())",
        "has": f"assertTrue({obj}.has{pascal(el)}())",
        "lacks": f"assertTrue({obj}.lacks{pascal(el)}())",
        "text_is": f"assertEquals(value, {obj}.{camel(el)}Text())",
        "is_enabled": f"assertTrue({obj}.{camel(el)}IsEnabled())",
        "app_running": f"assertTrue({obj}.isAppRunning())",
        "back": f"{obj}.goBack()",
    }[d.op]
    return statement, {cls}


def _asserts(statements: List[str]) -> List[str]:
    """The JUnit assertions the statements use."""
    return [a for a in ("assertEquals", "assertTrue") if any(s.startswith(f"{a}(") for s in statements)]


def _java_steps(bm: BddModel, page_name: str) -> str:
    """The Java step class driving one page."""
    defs = bm.steps_for(page_name)
    classes: Set[str] = set()
    statements: List[str] = []
    blocks: List[str] = []
    for d in defs:
        statement, built = _call(bm, d, "new ", "driver()")
        classes |= built
        statements.append(statement)
        param = "String value" if d.has_param else ""
        blocks.append(
            f"    @{_ANNOTATION[d.keyword]}({java_str(d.text)})\n"
            f"    public void {_method(d)}({param}) {{\n        {statement};\n    }}\n"
        )
    static = [f"import static org.junit.jupiter.api.Assertions.{a};" for a in _asserts(statements)]
    static.insert(0, "import static mobiscout.support.Session.driver;")
    keywords = sorted({_ANNOTATION[d.keyword] for d in defs})
    imports = [f"import io.cucumber.java.en.{k};" for k in keywords]
    imports += [f"import mobiscout.pages.{c};" for c in sorted(classes)]
    title = bm.fm.page(page_name).title
    return (
        "package mobiscout.steps;\n\n"
        + "\n".join(sorted(static))
        + "\n\n"
        + "\n".join(sorted(imports))
        + f"\n\n/**\n * Steps on the {title} screen — each one a call on a page object.\n *\n * <p>{_HEADER}\n */\n"
        + f"public class {pascal(page_name)}Steps {{\n\n"
        + "\n".join(blocks)
        + "}\n"
    )


def _kotlin_steps(bm: BddModel, page_name: str) -> str:
    """The Kotlin step class driving one page."""
    defs = bm.steps_for(page_name)
    classes: Set[str] = set()
    statements: List[str] = []
    blocks: List[str] = []
    for d in defs:
        statement, built = _call(bm, d, "", "Session.driver")
        classes |= built
        statements.append(statement)
        param = "value: String" if d.has_param else ""
        blocks.append(
            f"    @{_ANNOTATION[d.keyword]}({kotlin_str(d.text)})\n"
            f"    fun {_method(d)}({param}) {{\n        {statement}\n    }}\n"
        )
    keywords = sorted({_ANNOTATION[d.keyword] for d in defs})
    imports = [f"io.cucumber.java.en.{k}" for k in keywords]
    imports += [f"mobiscout.pages.{c}" for c in classes]
    imports += ["mobiscout.support.Session"]
    imports += [f"org.junit.jupiter.api.Assertions.{a}" for a in _asserts(statements)]
    title = bm.fm.page(page_name).title
    return (
        "package mobiscout.steps\n\n"
        + "".join(f"import {i}\n" for i in sorted(imports))
        + f"\n/**\n * Steps on the {title} screen — each one a call on a page object.\n *\n * {_HEADER}\n */\n"
        + f"class {pascal(page_name)}Steps {{\n\n"
        + "\n".join(blocks)
        + "}\n"
    )


def _features(bm: BddModel) -> Dict[str, str]:
    """One feature file per screen, on the test classpath."""
    return {f"{_FEATURES}/{snake(f.page)}.feature": render_feature(f, bm.fm.app_name) for f in bm.features}


def _step_pages(bm: BddModel) -> List[str]:
    """Pages some step drives, in page order."""
    used = {d.page for d in bm.steps}
    return [p.name for p in bm.fm.pages if p.name in used]


def _versions() -> dict:
    """The dependency versions every Cucumber-JVM kit pins."""
    return {
        "appium_version": APPIUM_JAVA_CLIENT_VERSION,
        "selenium_version": SELENIUM_VERSION,
        "cucumber_version": CUCUMBER_VERSION,
        "junit_version": JUNIT_VERSION,
    }


def render_java_cucumber(fm: FrameworkModel) -> Dict[str, str]:
    """The Cucumber (Java, JUnit Platform) suite on the page objects, as a Maven project."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    src = "src/test/java/mobiscout"
    env = _java_env()
    ios = fm.platform.value == "ios"
    files = {p: c for p, c in render_java(fm).items() if p.startswith(f"{src}/pages/")}
    files["pom.xml"] = env.get_template("cucumber-pom.xml.j2").render(**_versions())
    files[f"{src}/RunCucumberTest.java"] = env.get_template("RunCucumberTest.java.j2").render()
    files[f"{src}/support/Session.java"] = env.get_template("Session.java.j2").render(
        ios=ios, app_package=fm.app_package, app_activity=fm.app_activity, launch_args=fm.launch_args
    )
    files[f"{src}/support/Hooks.java"] = env.get_template("Hooks.java.j2").render()
    files.update(_features(bm))
    for p in _step_pages(bm):
        files[f"{src}/steps/{pascal(p)}Steps.java"] = _java_steps(bm, p)
    return files


def render_kotlin_cucumber(fm: FrameworkModel) -> Dict[str, str]:
    """The Cucumber (Kotlin, JUnit Platform) suite on the page objects, as a Gradle project."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    src = "src/test/kotlin/mobiscout"
    keep = (f"{src}/pages/", f"{src}/support/Session.kt", "settings.gradle.kts")
    files = {p: c for p, c in render_kotlin(fm).items() if p.startswith(keep)}
    env = _kotlin_env()
    files["build.gradle.kts"] = env.get_template("cucumber.build.gradle.kts.j2").render(**_versions())
    files[f"{src}/RunCucumberTest.kt"] = env.get_template("RunCucumberTest.kt.j2").render()
    files[f"{src}/support/Hooks.kt"] = env.get_template("Hooks.kt.j2").render()
    files.update(_features(bm))
    for p in _step_pages(bm):
        files[f"{src}/steps/{pascal(p)}Steps.kt"] = _kotlin_steps(bm, p)
    return files
