"""
JavaScript (WebdriverIO v9 + Mocha) renderer for the Page-Object framework model.

The layout WebdriverIO's own boilerplate uses::

    package.json, wdio.conf.js            one session per worker + a cold app restart per test
    test/pageobjects/base.page.js         locating / waiting / acting, written once
    test/pageobjects/<screen>.page.js     a page class exported as a singleton
    test/specs/<screen>.e2e.js            specs about that screen, reading like intent

Pages are singletons (``export default new LoginPage()``), as in WebdriverIO's boilerplate, since
``$`` and ``driver`` are globals — specs just call them::

    await welcomeBackPage.enterEmail('test@example.com');
    await welcomeBackPage.tapSignIn();
    expect(await catalogPage.isDisplayed()).toBe(true);
"""

from __future__ import annotations

import json
import os
import re
from typing import Dict, List, Optional, Set

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from framework.codegen.emitters._js_common import js_str, selector_array
from framework.codegen.emitters._naming import camel, pascal
from framework.codegen.framework_model import Call, FrameworkModel, PageDef, Scenario

_TEMPLATES = os.path.join(os.path.dirname(__file__), "templates", "framework", "js")
_PAGES = "test/pageobjects"
_SPECS = "test/specs"
_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."


def _jsdoc(text: Optional[str]) -> str:
    """Text safe inside a JSDoc comment."""
    return " ".join((text or "").replace("*/", "* /").split())


def _js_opt_str(value: Optional[str]) -> str:
    """A JS string literal, or ``null`` for ``None``."""
    return "null" if value is None else js_str(value)


def _js_list(values: List[str]) -> str:
    """A JS array literal of strings."""
    return "[" + ", ".join(js_str(v) for v in values) + "]"


def _env() -> Environment:
    """The Jinja environment for the WebdriverIO framework templates."""
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters.update(
        js_str=js_str, js_opt_str=_js_opt_str, js_list=_js_list, jsdoc=_jsdoc, selector_array=selector_array
    )
    return env


def _kebab(name: str) -> str:
    """``WelcomeBack`` -> ``welcome-back``, ``URLSettings`` -> ``url-settings``."""
    spaced = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", spaced).lower()


def _lower_first(name: str) -> str:
    """``WelcomeBack`` -> ``welcomeBack``; a leading acronym stays readable (``URLx`` -> ``urlX``)."""
    run = re.match(r"^([A-Z]+)(?=[A-Z][a-z]|$)", name)
    if run:
        return run.group(1).lower() + name[len(run.group(1)) :]
    return name[:1].lower() + name[1:]


def _module(page: PageDef) -> str:
    """The page module's file name (``welcome-back.page.js``)."""
    return f"{_kebab(page.name)}.page.js"


def _var(page: PageDef) -> str:
    """The name a page's singleton is imported under (``welcomeBackPage``)."""
    return f"{_lower_first(page.name)}Page"


def _methods(fm: FrameworkModel, page: PageDef) -> List[dict]:
    """Public methods: an action per tappable/typeable element, queries only where a spec asks."""
    used_taps = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "tap"}
    used_enters = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "enter"}
    methods: List[dict] = []
    for e in page.elements:
        base = {
            "key": e.key,
            "label": e.label or e.key.replace("_", " "),
            "pascal": pascal(e.key),
            "camel": camel(e.key),
        }
        if e.role == "input" or e.key in used_enters:
            methods.append({**base, "kind": "enter"})
        elif e.role == "tap" or e.key in used_taps:
            target = fm.page(e.navigates_to) if e.navigates_to and e.navigates_to != page.name else None
            methods.append(
                {
                    **base,
                    "kind": "tap",
                    "target": target.class_name if target else None,
                    "target_var": _var(target) if target else None,
                    "target_title": target.title if target else None,
                }
            )
    for kind, key in sorted(page.queries):
        e = page.element(key)
        methods.append(
            {
                "kind": kind,
                "key": key,
                "label": e.label or key.replace("_", " "),
                "pascal": pascal(key),
                "camel": camel(key),
            }
        )
    return methods


def _imports(fm: FrameworkModel, methods: List[dict]) -> List[dict]:
    """The other pages a page's navigating taps return (imported for their singletons)."""
    names = sorted({m["target"] for m in methods if m.get("target")})
    pages = [p for p in fm.pages if p.class_name in names]
    return [{"var": _var(p), "module": _module(p)} for p in pages]


def _render_call(fm: FrameworkModel, call: Call) -> str:
    """One scenario step as a JS statement on the page singleton."""
    page = fm.page(call.page)
    var, el = _var(page), call.element or ""
    if call.op == "tap":
        return f"await {var}.tap{pascal(el)}();"
    if call.op == "enter":
        return f"await {var}.enter{pascal(el)}({js_str(call.value or '')});"
    if call.op == "is_displayed":
        return f"expect(await {var}.isDisplayed()).toBe(true);"
    if call.op == "has":
        return f"expect(await {var}.has{pascal(el)}()).toBe(true);"
    if call.op == "lacks":
        return f"expect(await {var}.lacks{pascal(el)}()).toBe(true);"
    if call.op == "text_is":
        return f"expect(await {var}.{camel(el)}Text()).toBe({js_str(call.value or '')});"
    if call.op == "app_running":
        return f"expect(await {var}.isAppRunning()).toBe(true);"
    return f"expect(await {var}.{camel(el)}IsEnabled()).toBe(true);"  # is_enabled


def _render_spec(fm: FrameworkModel, page: PageDef, scenarios: List[Scenario]) -> str:
    """One Mocha spec file holding the scenarios about ``page``."""
    used: Set[str] = {c.page for s in scenarios for c in s.calls}
    titles: Set[str] = set()
    blocks: List[str] = []
    for sc in scenarios:
        title = sc.title or sc.name.replace("_", " ")
        if sc.defect:
            title = f"{title} @defect"  # WebdriverIO's tag-in-title convention (--mochaOpts.grep)
        if title in titles:  # Mocha allows it, but a duplicate title hides which one failed
            title = f"{title} ({sc.name.replace('_', ' ')})"
        titles.add(title)
        body = "".join(f"        {_render_call(fm, c)}\n" for c in sc.calls)
        blocks.append(f"    it({js_str(title)}, async () => {{\n{body}    }});\n")
    imports = "".join(f"import {_var(p)} from '../pageobjects/{_module(p)}';\n" for p in fm.pages if p.name in used)
    return (
        f"/**\n * Specs for the {_jsdoc(page.title)} screen.\n *\n * {_HEADER}\n */\n\n"
        + imports
        + f"\ndescribe({js_str(page.title + ' screen')}, () => {{\n"
        + "\n".join(blocks)
        + "});\n"
    )


def package_json(ios: bool, framework: str = "mocha") -> str:
    """The npm manifest (ESM, WebdriverIO v9 + the ``framework`` adapter + the appium service)."""
    manifest = {
        "name": "mobile-tests",
        "version": "1.0.0",
        "private": True,
        "type": "module",
        "scripts": {"test": "wdio run wdio.conf.js"},
        "devDependencies": {
            "@wdio/cli": "^9.0.0",
            "@wdio/local-runner": "^9.0.0",
            f"@wdio/{framework}-framework": "^9.0.0",
            "@wdio/appium-service": "^9.0.0",
            "@wdio/spec-reporter": "^9.0.0",
            "appium": "^2.11.0",
            ("appium-xcuitest-driver" if ios else "appium-uiautomator2-driver"): "*",
        },
    }
    return json.dumps(manifest, indent=2) + "\n"


def render_wdio_conf(fm: FrameworkModel, cucumber: bool) -> str:
    """``wdio.conf.js``: one session per worker and an app restart per test (Mocha) or per
    scenario (Cucumber)."""
    return (
        _env()
        .get_template("wdio.conf.js.j2")
        .render(
            ios=fm.platform.value == "ios",
            app_package=fm.app_package,
            app_activity=fm.app_activity,
            launch_args=fm.launch_args,
            cucumber=cucumber,
        )
    )


def render_js(fm: FrameworkModel) -> Dict[str, str]:
    """The WebdriverIO Page-Object framework as an npm project (relative path -> source)."""
    if not fm.pages:
        return {}
    env = _env()
    platform = fm.platform.value
    ios = platform == "ios"
    busy = "//XCUIElementTypeActivityIndicator" if ios else "//android.widget.ProgressBar"
    files: Dict[str, str] = {
        "package.json": package_json(ios),
        "wdio.conf.js": render_wdio_conf(fm, cucumber=False),
        f"{_PAGES}/base.page.js": env.get_template("base.page.js.j2").render(
            ios=ios, busy=busy, app_package=fm.app_package
        ),
    }
    page_tpl = env.get_template("page.js.j2")
    for page in fm.pages:
        methods = _methods(fm, page)
        files[f"{_PAGES}/{_module(page)}"] = page_tpl.render(
            page=page, platform=platform, methods=methods, imports=_imports(fm, methods)
        )
    by_group: Dict[str, List[Scenario]] = {}
    for sc in fm.scenarios:
        by_group.setdefault(sc.group, []).append(sc)
    for page in fm.pages:
        if page.name in by_group:
            files[f"{_SPECS}/{_kebab(page.name)}.e2e.js"] = _render_spec(fm, page, by_group[page.name])
    return files
