"""
Python (pytest + Appium) renderer for the Page-Object framework model.

Layout::

    conftest.py              one Appium session per run + a cold app restart per test
    pages/base_page.py       locating / waiting / acting / settling, written once
    pages/<screen>_page.py   private locators + intention methods per screen
    tests/test_<screen>.py   scenarios about that screen, reading like intent

Tests bind page objects to variables and follow navigation the way a person writes them::

    login_page = LoginPage(driver)
    login_page.enter_email("test@example.com")
    catalog_page = login_page.tap_sign_in()
    assert catalog_page.is_displayed()
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional, Sequence, Set

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from framework.codegen.emitters._naming import snake
from framework.codegen.emitters._python_common import locator_chain, py_str
from framework.codegen.framework_model import Call, FrameworkModel, PageDef, Scenario, repeated

_TEMPLATES = os.path.join(os.path.dirname(__file__), "templates", "framework", "python")
_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."

#: What every Python suite needs to drive Appium; each suite adds its runner.
PYTHON_REQUIREMENTS = "Appium-Python-Client>=4.0.0,<7.0.0\nselenium>=4.15.0,<5.0.0\n"


def _doc(text: Optional[str]) -> str:
    """Text safe inside a double-quoted docstring."""
    return " ".join((text or "").replace("\\", "/").replace('"', "'").split())


def _py_opt_str(value: Optional[str]) -> str:
    """A Python string literal, or ``None`` for ``None``."""
    return "None" if value is None else py_str(value)


def _py_list(values: List[str]) -> str:
    """A Python list literal of strings."""
    return "[" + ", ".join(py_str(v) for v in values) + "]"


def _env() -> Environment:
    """The Jinja environment for the Python framework templates."""
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters.update(py_str=py_str, py_opt_str=_py_opt_str, py_list=_py_list, doc=_doc, locator_chain=locator_chain)
    return env


def py_value(value: Optional[str]) -> str:
    """A typed value as Python — a long single-character run as ``"x" * 300``."""
    run = repeated(value)
    return f"{py_str(run[0])} * {run[1]}" if run else py_str(value or "")


def page_module(page: PageDef) -> str:
    """The page's module name (``login_page``)."""
    return snake(page.class_name)


def _var(page: PageDef) -> str:
    """The page's variable name in tests (``login_page``)."""
    return f"{snake(page.name)}_page"


def _methods(fm: FrameworkModel, page: PageDef) -> List[dict]:
    """The public methods a page exposes: an action per tappable/typeable element (its
    capabilities, as a hand-written page has), queries only where a scenario asks."""
    used_taps = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "tap"}
    used_enters = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "enter"}
    methods: List[dict] = []
    for e in page.elements:
        label = e.label or e.key.replace("_", " ")
        if e.role == "input" or e.key in used_enters:
            methods.append({"kind": "enter", "key": e.key, "label": label})
        elif e.role == "tap" or e.key in used_taps:
            target = fm.page(e.navigates_to) if e.navigates_to else None
            methods.append(
                {
                    "kind": "tap",
                    "key": e.key,
                    "label": label,
                    "target": target.class_name if target else None,
                    "target_module": page_module(target) if target else None,
                    "target_title": target.title if target else None,
                }
            )
    for kind, key in sorted(page.queries):
        label = page.element(key).label or key.replace("_", " ")
        methods.append({"kind": kind, "key": key, "label": label})
    return methods


def _render_call(
    fm: FrameworkModel, call: Call, bound: Dict[str, str], constructed: Set[str], later_pages: Set[str]
) -> List[str]:
    """One scenario step as Python lines, binding page variables on first use.

    A navigating tap binds the page it returns only when a later step uses that page —
    so a negative case (invalid input, the tap must NOT navigate) doesn't claim it
    arrived somewhere, and no test carries an unused variable."""
    page = fm.page(call.page)
    lines: List[str] = []
    var = bound.get(page.name)
    if var is None:
        var = bound[page.name] = _var(page)
        constructed.add(page.name)
        lines.append(f"{var} = {page.class_name}(driver)")
    el = call.element
    if call.op == "tap":
        target = page.element(el).navigates_to if el else None
        if target and target in later_pages and target != page.name:
            target_var = bound[target] = _var(fm.page(target))
            lines.append(f"{target_var} = {var}.tap_{el}()")
        else:
            lines.append(f"{var}.tap_{el}()")
    elif call.op == "enter":
        lines.append(f"{var}.enter_{el}({py_value(call.value)})")
    elif call.op == "is_displayed":
        lines.append(f"assert {var}.is_displayed()")
    elif call.op == "has":
        lines.append(f"assert {var}.has_{el}()")
    elif call.op == "lacks":
        lines.append(f"assert {var}.lacks_{el}()")
    elif call.op == "text_is":
        lines.append(f"assert {var}.{el}_text() == {py_str(call.value or '')}")
    elif call.op == "is_enabled":
        lines.append(f"assert {var}.{el}_is_enabled()")
    elif call.op == "app_running":
        lines.append(f"assert {var}.is_app_running()")
    elif call.op == "back":
        lines.append(f"{var}.go_back()")
    return lines


def _render_test_module(fm: FrameworkModel, page: PageDef, scenarios: List[Scenario]) -> str:
    """One pytest module holding the scenarios about ``page``."""
    bodies: List[str] = []
    imported: Set[str] = set()
    for sc in scenarios:
        if sc.skip:  # could not be built: say so where the test would be, never drop it
            bodies.append(
                f"@pytest.mark.skip(reason={py_str(sc.skip)})\n"
                f"def test_{sc.name}(driver):\n"
                f'    """{_doc(sc.description)}"""\n'
            )
            continue
        bound: Dict[str, str] = {}
        constructed: Set[str] = set()
        lines: List[str] = []
        for i, call in enumerate(sc.calls):
            later = {c.page for c in sc.calls[i + 1 :]}
            lines.extend(_render_call(fm, call, bound, constructed, later))
        imported |= constructed
        marker = "@pytest.mark.defect\n" if sc.defect else ""
        marker += "".join(f"@pytest.mark.{p}\n" for p in sc.platforms or [])
        bodies.append(
            f"{marker}def test_{sc.name}(driver):\n"
            f'    """{_doc(sc.description)}"""\n' + "".join(f"    {ln}\n" for ln in lines)
        )
    imports = "".join(f"from pages.{page_module(p)} import {p.class_name}\n" for p in fm.pages if p.name in imported)
    if any(sc.defect or sc.skip or sc.platforms for sc in scenarios):
        imports = "import pytest\n\n" + imports
    return (
        f'"""\nTests for the {_doc(page.title)} screen.\n\n{_HEADER}\n"""\n\n' + imports + "\n\n" + "\n\n".join(bodies)
    )


def _platforms(fm: FrameworkModel) -> dict:
    """Template context for a cross-platform kit (``multi``: pick the platform at run time)."""
    return {"multi": bool(fm.apps), "apps": fm.apps, "platforms": list(fm.apps)}


def render_python_pages(fm: FrameworkModel, step_modules: Sequence[str] = ()) -> Dict[str, str]:
    """The shared half of every Python framework: the driver fixtures (``conftest.py``,
    registering ``step_modules`` as plugins for a pytest-bdd suite) and the page objects."""
    env = _env()
    platform = fm.platform.value
    busy = "//XCUIElementTypeActivityIndicator" if platform == "ios" else "//android.widget.ProgressBar"
    files: Dict[str, str] = {
        "conftest.py": env.get_template("conftest.py.j2").render(
            platform=platform,
            app_package=fm.app_package,
            app_activity=fm.app_activity,
            launch_args=fm.launch_args,
            step_modules=list(step_modules),
            **_platforms(fm),
        ),
        "pages/__init__.py": "",
        "pages/base_page.py": env.get_template("base_page.py.j2").render(
            busy_xpath=busy, platform=platform, app_package=fm.app_package, **_platforms(fm)
        ),
    }
    page_tpl = env.get_template("page.py.j2")
    for page in fm.pages:
        files[f"pages/{page_module(page)}.py"] = page_tpl.render(
            page=page, platform=platform, methods=_methods(fm, page), **_platforms(fm)
        )
    return files


def render_behave_environment(fm: FrameworkModel) -> str:
    """Behave's ``environment.py`` — the same session setup as the pytest fixtures, as hooks."""
    return (
        _env()
        .get_template("environment.py.j2")
        .render(
            platform=fm.platform.value,
            app_package=fm.app_package,
            app_activity=fm.app_activity,
            launch_args=fm.launch_args,
            **_platforms(fm),
        )
    )


def render_python(fm: FrameworkModel) -> Dict[str, str]:
    """The pytest Page-Object framework (relative path -> source)."""
    if not fm.pages:
        return {}
    files = render_python_pages(fm)
    files["requirements.txt"] = PYTHON_REQUIREMENTS + "pytest>=8.0.0\n"
    by_group: Dict[str, List[Scenario]] = {}
    for sc in [*fm.scenarios, *fm.skipped]:
        by_group.setdefault(sc.group, []).append(sc)
    if by_group:
        files["tests/__init__.py"] = ""
        for page in fm.pages:
            if page.name in by_group:
                files[f"tests/test_{snake(page.name)}.py"] = _render_test_module(fm, page, by_group[page.name])
    return files
