"""
C# (.NET 10 + Appium .NET client) renderers for the Page-Object framework model: NUnit tests,
and Reqnroll (the SpecFlow successor) BDD on the same page objects.

Standard SDK-style project::

    MobileTests.csproj
    Support/Session.cs            one Appium session per run, reopened if it died
    Support/BaseTest.cs           NUnit: a cold app restart before every test
    SessionLifetime.cs            NUnit: closes the session after the run
    Support/Hooks.cs              Reqnroll: restart per scenario, close after the run
    Pages/BasePage.cs             locating / waiting / acting, written once
    Pages/<Screen>Page.cs         private locators + intention methods
    Tests/<Screen>Tests.cs        NUnit: scenarios about that screen
    Features/<screen>.feature     Reqnroll: the same declarative features as every BDD target
    StepDefinitions/<Screen>Steps.cs   Reqnroll: one call on a page object per step

Locators go through ``MobileBy`` — Selenium's own ``By.Id``/``By.ClassName`` turn into CSS
selectors under the W3C protocol, which an Appium resource-id or Android class name never
matches.
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional, Set, Tuple

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from framework.codegen.bdd_model import BddModel, StepDef, build_bdd_model, render_feature
from framework.codegen.emitters._java_common import java_str
from framework.codegen.emitters._naming import ios_text_xpath, pascal, snake, ua_escape
from framework.codegen.framework_java import _lower_first, _methods
from framework.codegen.framework_model import Call, FrameworkModel, PageDef, Scenario, repeated
from framework.codegen.ir import Selector, SelectorStrategy

_TEMPLATES = os.path.join(os.path.dirname(__file__), "templates", "framework", "csharp")
_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."

VERSIONS = {
    "appium": "9.0.0",
    "test_sdk": "18.10.1",
    "nunit": "4.6.1",
    "nunit_adapter": "6.3.0",
    "reqnroll": "3.3.4",
}

# C#'s regular string literal escapes exactly as Java's does (\\ \" \n \t \uXXXX).
cs_str = java_str

_MOBILE_BY = {
    SelectorStrategy.ID: "MobileBy.Id",
    SelectorStrategy.ACCESSIBILITY_ID: "MobileBy.AccessibilityId",
    SelectorStrategy.XPATH: "By.XPath",
    SelectorStrategy.CLASS_NAME: "MobileBy.ClassName",
    SelectorStrategy.TEXT: "MobileBy.AndroidUIAutomator",
}


def by_expr(sel: Selector, platform: str) -> str:
    """One locator as a C# ``By`` expression."""
    if sel.strategy is SelectorStrategy.TEXT:
        if platform == "ios":  # iOS has no UiAutomator text() — match @label/@name by XPath
            return f"By.XPath({cs_str(ios_text_xpath(sel.value))})"
        statement = f'new UiSelector().text("{ua_escape(sel.value)}")'
        return f"MobileBy.AndroidUIAutomator({cs_str(statement)})"
    return f"{_MOBILE_BY[sel.strategy]}({cs_str(sel.value)})"


def _by_items(sel: Selector, platform: str) -> str:
    """Primary + fallback locators for a collection expression."""
    return ", ".join(by_expr(s, platform) for s in [sel, *sel.fallbacks])


def _xmldoc(text: Optional[str]) -> str:
    """Text safe inside an XML doc comment."""
    cleaned = (text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return " ".join(cleaned.split())


def cs_value(value: Optional[str]) -> str:
    """A typed value as C# — a long single-character run as ``new string('x', 300)``."""
    run = repeated(value)
    if run:
        char = run[0].replace("\\", "\\\\").replace("'", "\\'")
        return f"new string('{char}', {run[1]})"
    return cs_str(value or "")


def _env() -> Environment:
    """The Jinja environment for the C# framework templates."""
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters.update(
        cs_str=cs_str,
        cs_opt_str=lambda v: "null" if v is None else cs_str(v),
        cs_str_list=lambda vs: ", ".join(cs_str(v) for v in vs),
        xmldoc=_xmldoc,
        by_items=_by_items,
    )
    return env


def _var(page: PageDef) -> str:
    """The page's local variable name (``welcomeBackPage``)."""
    return f"{_lower_first(page.name)}Page"


def _render_call(fm: FrameworkModel, call: Call, declared: Set[str], later_pages: Set[str]) -> List[str]:
    """One scenario step as C# statements; a page ``var`` is declared on first use, and a
    navigating tap binds the page it returns only when a later step uses it."""
    page = fm.page(call.page)
    var, el = _var(page), pascal(call.element or "")
    lines: List[str] = []
    if page.name not in declared:
        declared.add(page.name)
        lines.append(f"var {var} = new {page.class_name}(Driver);")
    if call.op == "tap":
        target = page.element(call.element or "").navigates_to
        if target and target != page.name and target in later_pages and target not in declared:
            declared.add(target)
            lines.append(f"var {_var(fm.page(target))} = {var}.Tap{el}();")
        else:
            lines.append(f"{var}.Tap{el}();")
    elif call.op == "enter":
        lines.append(f"{var}.Enter{el}({cs_value(call.value)});")
    elif call.op == "back":
        lines.append(f"{var}.GoBack();")
    elif call.op == "text_is":
        lines.append(f"Assert.That({var}.{el}Text(), Is.EqualTo({cs_str(call.value or '')}));")
    else:
        check = {
            "is_displayed": "IsDisplayed()",
            "has": f"Has{el}()",
            "lacks": f"Lacks{el}()",
            "is_enabled": f"{el}IsEnabled()",
            "app_running": "IsAppRunning()",
        }[call.op]
        lines.append(f"Assert.That({var}.{check}, Is.True);")
    return lines


def _render_test_class(fm: FrameworkModel, page: PageDef, scenarios: List[Scenario]) -> str:
    """One NUnit fixture holding the scenarios about ``page``."""
    blocks: List[str] = []
    for sc in scenarios:
        doc = f"    /// <summary>{_xmldoc(sc.description)}</summary>\n"
        if sc.skip:  # could not be built: say so where the test would be, never drop it
            blocks.append(
                f"{doc}    [Test, Ignore({cs_str(sc.skip)})]\n    public void {pascal(sc.name)}()\n    {{\n    }}\n"
            )
            continue
        declared: Set[str] = set()
        lines: List[str] = []
        for i, call in enumerate(sc.calls):
            lines.extend(_render_call(fm, call, declared, {c.page for c in sc.calls[i + 1 :]}))
        attrs = '[Test, Category("defect")]' if sc.defect else "[Test]"
        body = "".join(f"        {ln}\n" for ln in lines)
        blocks.append(f"{doc}    {attrs}\n    public void {pascal(sc.name)}()\n    {{\n{body}    }}\n")
    return (
        "using MobileTests.Pages;\nusing MobileTests.Support;\nusing NUnit.Framework;\n\n"
        "namespace MobileTests.Tests;\n\n"
        f"/// <summary>Tests for the {_xmldoc(page.title)} screen.</summary>\n"
        f"/// <remarks>{_HEADER}</remarks>\n"
        f"public sealed class {page.name}Tests : BaseTest\n{{\n" + "\n".join(blocks) + "}\n"
    )


def _base(fm: FrameworkModel, reqnroll: bool) -> Dict[str, str]:
    """What both C# suites share: the project, the session and the page objects."""
    env = _env()
    platform = fm.platform.value
    ios = platform == "ios"
    driver = "IOSDriver" if ios else "AndroidDriver"
    busy = "//XCUIElementTypeActivityIndicator" if ios else "//android.widget.ProgressBar"
    files: Dict[str, str] = {
        "MobileTests.csproj": env.get_template("MobileTests.csproj.j2").render(versions=VERSIONS, reqnroll=reqnroll),
        "Support/Session.cs": env.get_template("Session.cs.j2").render(
            ios=ios,
            driver=driver,
            app_package=fm.app_package,
            app_activity=fm.app_activity,
            launch_args=fm.launch_args,
        ),
        "Pages/BasePage.cs": env.get_template("BasePage.cs.j2").render(
            ios=ios, driver=driver, busy=busy, app_package=fm.app_package
        ),
    }
    page_tpl = env.get_template("Page.cs.j2")
    for page in fm.pages:
        files[f"Pages/{page.class_name}.cs"] = page_tpl.render(
            page=page, platform=platform, driver=driver, methods=_methods(fm, page)
        )
    return files


def render_csharp(fm: FrameworkModel) -> Dict[str, str]:
    """The NUnit Page-Object framework as a .NET test project (relative path -> source)."""
    if not fm.pages:
        return {}
    env = _env()
    ios = fm.platform.value == "ios"
    files = _base(fm, reqnroll=False)
    files["Support/BaseTest.cs"] = env.get_template("BaseTest.cs.j2").render(
        ios=ios, driver="IOSDriver" if ios else "AndroidDriver"
    )
    files["SessionLifetime.cs"] = env.get_template("SessionLifetime.cs.j2").render()
    by_group: Dict[str, List[Scenario]] = {}
    for sc in [*fm.scenarios, *fm.skipped]:
        by_group.setdefault(sc.group, []).append(sc)
    for page in fm.pages:
        if page.name in by_group:
            files[f"Tests/{page.name}Tests.cs"] = _render_test_class(fm, page, by_group[page.name])
    return files


# --- Reqnroll ------------------------------------------------------------------------------


def _step_method(d: StepDef) -> str:
    """The step method's name — what the step does, unique within its page's step class."""
    page, el = pascal(d.page), pascal(d.element or "")
    return {
        "arrive": f"On{page}Screen",
        "tap": f"Tap{el}",
        "enter": f"Enter{el}",
        "enter_long": f"Enter{len(d.sample or '')}CharactersInto{el}",
        "is_displayed": f"See{page}Screen",
        "stays": f"StillOn{page}Screen",
        "has": f"See{el}",
        "lacks": f"NotSee{el}",
        "text_is": f"{el}Shows",
        "is_enabled": f"{el}IsEnabled",
        "app_running": "AppIsRunning",
        "back": "GoBack",
    }[d.op]


def _step_body(bm: BddModel, d: StepDef) -> Tuple[str, Set[str]]:
    """(the step's one expression, the page classes it constructs)."""
    fm = bm.fm
    page = fm.page(d.page)
    el, obj = pascal(d.element or ""), f"new {page.class_name}(Session.Driver)"
    if d.op == "arrive":
        if not d.path:
            return f"Assert.That({obj}.IsDisplayed(), Is.True)", {page.class_name}
        start = fm.page(d.path[0].page).class_name
        chain = "".join(f".Tap{pascal(c.element or '')}()" for c in d.path)
        return f"Assert.That(new {start}(Session.Driver){chain}.IsDisplayed(), Is.True)", {start}
    expression = {
        "tap": f"{obj}.Tap{el}()",
        "enter": f"{obj}.Enter{el}(value)",
        "enter_long": f"{obj}.Enter{el}({cs_value(d.sample)})",
        "back": f"{obj}.GoBack()",
        "text_is": f"Assert.That({obj}.{el}Text(), Is.EqualTo(value))",
        "is_displayed": f"Assert.That({obj}.IsDisplayed(), Is.True)",
        "stays": f"Assert.That({obj}.IsDisplayed(), Is.True)",
        "has": f"Assert.That({obj}.Has{el}(), Is.True)",
        "lacks": f"Assert.That({obj}.Lacks{el}(), Is.True)",
        "is_enabled": f"Assert.That({obj}.{el}IsEnabled(), Is.True)",
        "app_running": f"Assert.That({obj}.IsAppRunning(), Is.True)",
    }[d.op]
    return expression, {page.class_name}


def _steps_class(bm: BddModel, page_name: str) -> str:
    """The Reqnroll step-definition class driving one page."""
    blocks: List[str] = []
    for d in bm.steps_for(page_name):
        expression, _ = _step_body(bm, d)
        param = "string value" if d.has_param else ""
        blocks.append(
            f"    [{d.keyword}({cs_str(d.text)})]\n" f"    public void {_step_method(d)}({param}) => {expression};\n"
        )
    title = bm.fm.page(page_name).title
    return (
        "using MobileTests.Pages;\nusing MobileTests.Support;\nusing NUnit.Framework;\nusing Reqnroll;\n\n"
        "namespace MobileTests.StepDefinitions;\n\n"
        f"/// <summary>Steps on the {_xmldoc(title)} screen — each one a call on a page object.</summary>\n"
        f"/// <remarks>{_HEADER}</remarks>\n"
        f"[Binding]\npublic sealed class {pascal(page_name)}Steps\n{{\n" + "\n".join(blocks) + "}\n"
    )


def render_reqnroll(fm: FrameworkModel) -> Dict[str, str]:
    """The Reqnroll (NUnit) BDD suite on the page objects, as a .NET test project."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    files = _base(fm, reqnroll=True)
    files["Support/Hooks.cs"] = _env().get_template("Hooks.cs.j2").render()
    for f in bm.features:
        files[f"Features/{snake(f.page)}.feature"] = render_feature(f, fm.app_package)
    used = {d.page for d in bm.steps}
    for p in fm.pages:
        if p.name in used:
            files[f"StepDefinitions/{pascal(p.name)}Steps.cs"] = _steps_class(bm, p.name)
    return files
