"""
Python BDD renderers — pytest-bdd and Behave — on top of the Page-Object framework.

Both share the pytest framework's page objects and read the same feature files; they differ
only in how step definitions reach the driver and how a suite is wired::

    pytest-bdd                                  Behave
    conftest.py        driver fixtures           features/environment.py  session + restart hooks
    pages/             page objects              pages/                   page objects
    features/*.feature one per screen            features/*.feature       one per screen
    steps/<page>_steps.py                        features/steps/<page>_steps.py
    tests/test_features.py  binds the features

A step definition is one call on a page object::

    @when("I tap Sign in")
    def tap_sign_in(driver):
        WelcomeBackPage(driver).tap_sign_in()
"""

from __future__ import annotations

from typing import Dict, List, Set, Tuple

from framework.codegen.bdd_model import PARAM, BddModel, StepDef, build_bdd_model, render_feature
from framework.codegen.emitters._naming import snake
from framework.codegen.emitters._python_common import py_str
from framework.codegen.framework_model import FrameworkModel
from framework.codegen.framework_python import (
    PYTHON_REQUIREMENTS,
    page_module,
    py_value,
    render_behave_environment,
    render_python_pages,
)

_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."


def _fn_name(d: StepDef) -> str:
    """The step function's name — what the step does, unique within its page module."""
    page = snake(d.page)
    el = d.element or ""
    return {
        "arrive": f"on_{page}_screen",
        "tap": f"tap_{el}",
        "enter": f"enter_{el}",
        "enter_long": f"enter_{len(d.sample or '')}_characters_into_{el}",
        "is_displayed": f"see_{page}_screen",
        "stays": f"still_on_{page}_screen",
        "has": f"see_{el}",
        "lacks": f"not_see_{el}",
        "text_is": f"{el}_shows",
        "is_enabled": f"{el}_is_enabled",
        "app_running": "app_is_running",
        "back": "go_back",
    }[d.op]


def _body(bm: BddModel, d: StepDef, driver: str) -> Tuple[List[str], Set[str]]:
    """(the step's statements, the page names it constructs)."""
    fm = bm.fm
    page = fm.page(d.page)
    el = d.element or ""
    if d.op == "arrive":
        if not d.path:
            return [f"assert {page.class_name}({driver}).is_displayed()"], {d.page}
        start = fm.page(d.path[0].page)
        chain = "".join(f".tap_{c.element}()" for c in d.path)
        return [f"assert {start.class_name}({driver}){chain}.is_displayed()"], {start.name}
    call = {
        "tap": f"{page.class_name}({driver}).tap_{el}()",
        "enter": f"{page.class_name}({driver}).enter_{el}(value)",
        "enter_long": f"{page.class_name}({driver}).enter_{el}({py_value(d.sample)})",
        "is_displayed": f"assert {page.class_name}({driver}).is_displayed()",
        "stays": f"assert {page.class_name}({driver}).is_displayed()",
        "has": f"assert {page.class_name}({driver}).has_{el}()",
        "lacks": f"assert {page.class_name}({driver}).lacks_{el}()",
        "text_is": f"assert {page.class_name}({driver}).{el}_text() == value",
        "is_enabled": f"assert {page.class_name}({driver}).{el}_is_enabled()",
        "app_running": f"assert {page.class_name}({driver}).is_app_running()",
        "back": f"{page.class_name}({driver}).go_back()",
    }[d.op]
    return [call], {d.page}


def _quote(text: str) -> str:
    """A string literal the way black writes it: double quotes, unless the text holds one
    (a step's quoted parameter) and no single quote — then single quotes, no escapes."""
    if '"' in text and "'" not in text:
        return f"'{text}'"
    return py_str(text)


def _pattern(d: StepDef) -> str:
    """The step's parse-style pattern (the value, if any, captured as ``value``)."""
    return d.text.replace(PARAM, '"{value}"')


def _step_module(bm: BddModel, page_name: str, flavour: str) -> str:
    """The step definitions driving one page, for ``flavour`` "pytest_bdd" or "behave"."""
    behave = flavour == "behave"
    driver = "context.driver" if behave else "driver"
    first = "context" if behave else "driver"
    defs = bm.steps_for(page_name)
    keywords = sorted({d.keyword.lower() for d in defs})
    constructed: Set[str] = set()
    blocks: List[str] = []
    for d in defs:
        lines, built = _body(bm, d, driver)
        constructed |= built
        if behave:
            decorator = f"@{d.keyword.lower()}({_quote(_pattern(d))})"
        elif d.has_param:
            decorator = f"@{d.keyword.lower()}(parsers.parse({_quote(_pattern(d))}))"
        else:
            decorator = f"@{d.keyword.lower()}({_quote(d.text)})"
        args = f"{first}, value" if d.has_param else first
        blocks.append(f"{decorator}\ndef {_fn_name(d)}({args}):\n" + "".join(f"    {ln}\n" for ln in lines))
    title = bm.fm.page(page_name).title
    if behave:
        imports = f"from behave import {', '.join(keywords)}\n"
    else:
        extra = ["parsers"] if any(d.has_param for d in defs) else []
        imports = f"from pytest_bdd import {', '.join(sorted(keywords + extra))}\n"
    used = sorted((page_module(p), p.class_name) for p in bm.fm.pages if p.name in constructed)
    pages = "".join(f"from pages.{module} import {cls}\n" for module, cls in used)
    return (
        f'"""\nSteps on the {title} screen — each one a call on a page object.\n\n{_HEADER}\n"""\n\n'
        f"{imports}\n{pages}\n\n" + "\n\n".join(blocks)
    )


def _features(bm: BddModel, directory: str) -> Dict[str, str]:
    """One feature file per screen."""
    return {f"{directory}/{snake(f.page)}.feature": render_feature(f, bm.fm.app_package) for f in bm.features}


def _step_pages(bm: BddModel) -> List[str]:
    """Pages some step drives, in page order."""
    used = {d.page for d in bm.steps}
    return [p.name for p in bm.fm.pages if p.name in used]


def render_pytest_bdd(fm: FrameworkModel) -> Dict[str, str]:
    """The pytest-bdd suite on the Page-Object framework (relative path -> source)."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    step_pages = _step_pages(bm)
    files = render_python_pages(fm, [f"steps.{snake(p)}_steps" for p in step_pages])
    files.update(_features(bm, "features"))
    files["steps/__init__.py"] = ""
    for p in step_pages:
        files[f"steps/{snake(p)}_steps.py"] = _step_module(bm, p, "pytest_bdd")
    files["tests/__init__.py"] = ""
    files["tests/test_features.py"] = (
        f'"""\nRuns every scenario in features/ — the steps are registered in conftest.py.\n\n{_HEADER}\n"""\n\n'
        "from pytest_bdd import scenarios\n\n"
        'scenarios("../features")\n'
    )
    files["requirements.txt"] = PYTHON_REQUIREMENTS + "pytest>=8.0.0\npytest-bdd>=7.0.0\n"
    return files


def render_behave(fm: FrameworkModel) -> Dict[str, str]:
    """The Behave suite on the Page-Object framework (relative path -> source)."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    files = render_python_pages(fm)
    del files["conftest.py"]  # Behave wires the session through its hooks instead
    files["features/environment.py"] = render_behave_environment(fm)
    files.update(_features(bm, "features"))
    for p in _step_pages(bm):
        files[f"features/steps/{snake(p)}_steps.py"] = _step_module(bm, p, "behave")
    files["requirements.txt"] = PYTHON_REQUIREMENTS + "behave>=1.2.6\n"
    return files
