"""
Kotlin (JUnit 5 + Appium java-client) renderer for the Page-Object framework model.

Standard Gradle layout::

    build.gradle.kts, settings.gradle.kts
    src/test/kotlin/mobiscout/support/Session.kt     one Appium session for the whole run
    src/test/kotlin/mobiscout/support/BaseTest.kt    a cold app restart before every test
    src/test/kotlin/mobiscout/pages/BasePage.kt      locating / waiting / acting, written once
    src/test/kotlin/mobiscout/pages/<Screen>Page.kt  private locators + intention methods
    src/test/kotlin/mobiscout/tests/<Screen>Test.kt  scenarios about that screen

Tests are named as sentences (Kotlin's backticked test names) and follow navigation through
typed page objects::

    @Test
    fun `the catalog screen shows its expected controls`() {
        val welcomeBackPage = WelcomeBackPage(driver)
        val catalogPage = welcomeBackPage.tapSignIn()
        assertTrue(catalogPage.isDisplayed())
    }
"""

from __future__ import annotations

import os
import re
from typing import Dict, List, Optional, Set

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from framework.codegen.emitters._kotlin_common import by_expr, kotlin_str
from framework.codegen.emitters._naming import camel, pascal
from framework.codegen.framework_java import _methods, _var
from framework.codegen.framework_model import Call, FrameworkModel, PageDef, Scenario
from framework.codegen.ir import Selector
from framework.codegen.scaffold import APPIUM_JAVA_CLIENT_VERSION, SELENIUM_VERSION

_TEMPLATES = os.path.join(os.path.dirname(__file__), "templates", "framework", "kotlin")
_SRC = "src/test/kotlin/mobiscout"
_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."

#: Characters a JVM method name — and so a backticked Kotlin test name — cannot contain.
_ILLEGAL_IN_NAME = re.compile(r"[.;\[\]/<>:\\`]")


def _kdoc(text: Optional[str]) -> str:
    """Text safe inside a KDoc comment (no comment terminator, no link brackets)."""
    cleaned = (text or "").replace("*/", "* /").replace("[", "(").replace("]", ")")
    return " ".join(cleaned.split())


def _kotlin_opt_str(value: Optional[str]) -> str:
    """A Kotlin string literal, or ``null`` for ``None``."""
    return "null" if value is None else kotlin_str(value)


def _kotlin_str_list(values: List[str]) -> str:
    """Kotlin string literals joined for a ``listOf(...)`` argument list."""
    return ", ".join(kotlin_str(v) for v in values)


def _by_items(sel: Selector, platform: str) -> str:
    """Primary + fallback ``AppiumBy`` expressions for a ``listOf(...)``."""
    return ", ".join(by_expr(s, platform) for s in [sel, *sel.fallbacks])


def _env() -> Environment:
    """The Jinja environment for the Kotlin framework templates."""
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters.update(
        kotlin_str=kotlin_str,
        kotlin_opt_str=_kotlin_opt_str,
        kotlin_str_list=_kotlin_str_list,
        kdoc=_kdoc,
        by_items=_by_items,
    )
    return env


def _test_name(scenario: Scenario) -> str:
    """The scenario's description as a backticked-name-safe sentence."""
    text = scenario.description.rstrip(".") or scenario.name.replace("_", " ")
    return " ".join(_ILLEGAL_IN_NAME.sub(" ", text).split())


def _render_call(fm: FrameworkModel, call: Call, declared: Set[str], later_pages: Set[str]) -> List[str]:
    """One scenario step as Kotlin statements. A page ``val`` is declared on first use; a
    navigating tap binds the page it returns only when a later step uses it and it is not bound
    yet (page objects are stateless, so an existing one stays valid on return)."""
    page = fm.page(call.page)
    var = _var(page)
    lines: List[str] = []
    if page.name not in declared:
        declared.add(page.name)
        lines.append(f"val {var} = {page.class_name}(driver)")
    el = call.element or ""
    if call.op == "tap":
        target = page.element(el).navigates_to
        if target and target != page.name and target in later_pages and target not in declared:
            declared.add(target)
            lines.append(f"val {_var(fm.page(target))} = {var}.tap{pascal(el)}()")
        else:
            lines.append(f"{var}.tap{pascal(el)}()")
    elif call.op == "enter":
        lines.append(f"{var}.enter{pascal(el)}({kotlin_str(call.value or '')})")
    elif call.op == "is_displayed":
        lines.append(f"assertTrue({var}.isDisplayed())")
    elif call.op == "has":
        lines.append(f"assertTrue({var}.has{pascal(el)}())")
    elif call.op == "lacks":
        lines.append(f"assertTrue({var}.lacks{pascal(el)}())")
    elif call.op == "text_is":
        lines.append(f"assertEquals({kotlin_str(call.value or '')}, {var}.{camel(el)}Text())")
    elif call.op == "is_enabled":
        lines.append(f"assertTrue({var}.{camel(el)}IsEnabled())")
    return lines


def _render_test_class(fm: FrameworkModel, page: PageDef, scenarios: List[Scenario]) -> str:
    """One JUnit 5 test class holding the scenarios about ``page``."""
    names: Set[str] = set()
    bodies: List[str] = []
    for sc in scenarios:
        name = _test_name(sc)
        if name in names:  # the same sentence twice would not compile
            name = f"{name} ({sc.name.replace('_', ' ')})"
        names.add(name)
        declared: Set[str] = set()
        lines: List[str] = []
        for i, call in enumerate(sc.calls):
            later = {c.page for c in sc.calls[i + 1 :]}
            lines.extend(_render_call(fm, call, declared, later))
        body = "".join(f"        {ln}\n" for ln in lines)
        bodies.append(f"    @Test\n    fun `{name}`() {{\n{body}    }}\n")
    source = "\n".join(bodies)
    used = {c.page for s in scenarios for c in s.calls}
    asserts = [a for a in ("assertEquals", "assertTrue") if f"{a}(" in source]
    imports = [f"mobiscout.pages.{p.class_name}" for p in fm.pages if p.name in used]
    imports += ["mobiscout.support.BaseTest"]
    imports += [f"org.junit.jupiter.api.Assertions.{a}" for a in asserts]
    imports += ["org.junit.jupiter.api.Test"]
    return (
        "package mobiscout.tests\n\n"
        + "".join(f"import {i}\n" for i in sorted(imports))
        + f"\n/**\n * Tests for the {_kdoc(page.title)} screen.\n *\n * {_HEADER}\n */\n"
        + f"class {page.name}Test : BaseTest() {{\n\n"
        + source
        + "}\n"
    )


def render_kotlin(fm: FrameworkModel) -> Dict[str, str]:
    """The JUnit 5 Page-Object framework as a Gradle project (relative path -> source)."""
    if not fm.pages:
        return {}
    env = _env()
    platform = fm.platform.value
    ios = platform == "ios"
    busy = "//XCUIElementTypeActivityIndicator" if ios else "//android.widget.ProgressBar"
    files: Dict[str, str] = {
        "build.gradle.kts": env.get_template("build.gradle.kts.j2").render(
            appium_version=APPIUM_JAVA_CLIENT_VERSION, selenium_version=SELENIUM_VERSION
        ),
        "settings.gradle.kts": 'rootProject.name = "mobile-tests"\n',
        f"{_SRC}/support/Session.kt": env.get_template("Session.kt.j2").render(
            ios=ios, app_package=fm.app_package, app_activity=fm.app_activity, launch_args=fm.launch_args
        ),
        f"{_SRC}/support/BaseTest.kt": env.get_template("BaseTest.kt.j2").render(ios=ios),
        f"{_SRC}/pages/BasePage.kt": env.get_template("BasePage.kt.j2").render(ios=ios, busy=busy),
    }
    page_tpl = env.get_template("Page.kt.j2")
    for page in fm.pages:
        files[f"{_SRC}/pages/{page.class_name}.kt"] = page_tpl.render(
            page=page, platform=platform, methods=_methods(fm, page)
        )
    by_group: Dict[str, List[Scenario]] = {}
    for sc in fm.scenarios:
        by_group.setdefault(sc.group, []).append(sc)
    for page in fm.pages:
        if page.name in by_group:
            files[f"{_SRC}/tests/{page.name}Test.kt"] = _render_test_class(fm, page, by_group[page.name])
    return files
