"""
Cucumber (WebdriverIO v9) renderer on top of the JavaScript page objects.

The same feature files as every BDD target, run by WebdriverIO's Cucumber adapter::

    package.json, wdio.conf.js                     one session per worker + app restart per scenario
    test/pageobjects/                              the page objects (singletons)
    features/<screen>.feature                      one per screen
    features/step-definitions/<screen>.steps.js    one call on a page object per step

A step definition is one call on a page object::

    When('I enter {string} into Email', async (value) => {
        await welcomeBackPage.enterEmail(value);
    });
"""

from __future__ import annotations

from typing import Dict, List, Set, Tuple

from framework.codegen.bdd_model import BddModel, StepDef, build_bdd_model, render_feature
from framework.codegen.emitters._js_common import js_str
from framework.codegen.emitters._naming import camel, pascal, snake
from framework.codegen.framework_js import _kebab, _module, _var, js_value, package_json, render_js, render_wdio_conf
from framework.codegen.framework_model import FrameworkModel

_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."
_STEPS = "features/step-definitions"


def _statements(bm: BddModel, d: StepDef) -> Tuple[List[str], Set[str]]:
    """(the step's statements, the pages whose singletons it uses)."""
    fm = bm.fm
    page = fm.page(d.page)
    var, el = _var(page), d.element or ""
    if d.op == "arrive":
        # Taps return the next page, but pages are singletons: name each one directly.
        taps = [f"await {_var(fm.page(c.page))}.tap{pascal(c.element or '')}();" for c in d.path]
        used = {c.page for c in d.path} | {d.page}
        return [*taps, f"expect(await {var}.isDisplayed()).toBe(true);"], used
    statement = {
        "tap": f"await {var}.tap{pascal(el)}();",
        "enter": f"await {var}.enter{pascal(el)}(value);",
        "enter_long": f"await {var}.enter{pascal(el)}({js_value(d.sample)});",
        "is_displayed": f"expect(await {var}.isDisplayed()).toBe(true);",
        "stays": f"expect(await {var}.isDisplayed()).toBe(true);",
        "has": f"expect(await {var}.has{pascal(el)}()).toBe(true);",
        "lacks": f"expect(await {var}.lacks{pascal(el)}()).toBe(true);",
        "text_is": f"expect(await {var}.{camel(el)}Text()).toBe(value);",
        "is_enabled": f"expect(await {var}.{camel(el)}IsEnabled()).toBe(true);",
        "app_running": f"expect(await {var}.isAppRunning()).toBe(true);",
        "back": f"await {var}.goBack();",
    }[d.op]
    return [statement], {d.page}


def _step_file(bm: BddModel, page_name: str) -> str:
    """The step definitions driving one page."""
    defs = bm.steps_for(page_name)
    used: Set[str] = set()
    blocks: List[str] = []
    for d in defs:
        lines, touched = _statements(bm, d)
        used |= touched
        args = "value" if d.has_param else ""
        body = "".join(f"    {ln}\n" for ln in lines)
        blocks.append(f"{d.keyword}({js_str(d.text)}, async ({args}) => {{\n{body}}});\n")
    keywords = [k for k in ("Given", "When", "Then") if any(d.keyword == k for d in defs)]
    pages = "".join(
        f"import {_var(p)} from '../../test/pageobjects/{_module(p)}';\n" for p in bm.fm.pages if p.name in used
    )
    title = bm.fm.page(page_name).title
    return (
        f"/**\n * Steps on the {title} screen — each one a call on a page object.\n *\n * {_HEADER}\n */\n\n"
        f"import {{ {', '.join(keywords)} }} from '@wdio/cucumber-framework';\n\n" + pages + "\n" + "\n".join(blocks)
    )


def render_js_cucumber(fm: FrameworkModel) -> Dict[str, str]:
    """The WebdriverIO Cucumber suite on the page objects, as an npm project."""
    bm = build_bdd_model(fm)
    if not bm.features:
        return {}
    files = {p: c for p, c in render_js(fm).items() if p.startswith("test/pageobjects/")}
    files["package.json"] = package_json(fm.platform.value == "ios", framework="cucumber")
    files["wdio.conf.js"] = render_wdio_conf(fm, cucumber=True)
    for f in bm.features:
        files[f"features/{snake(f.page)}.feature"] = render_feature(f, fm.app_name)
    used = {d.page for d in bm.steps}
    for p in fm.pages:
        if p.name in used:
            files[f"{_STEPS}/{_kebab(p.name)}.steps.js"] = _step_file(bm, p.name)
    return files
