"""
Java (TestNG + Appium java-client 9) renderer for the Page-Object framework model.

Standard Maven layout::

    pom.xml, testng.xml
    src/test/java/mobiscout/support/BaseTest.java    one session per suite + app restart per test
    src/test/java/mobiscout/pages/BasePage.java      locating / waiting / acting, written once
    src/test/java/mobiscout/pages/<Screen>Page.java  private locators + intention methods
    src/test/java/mobiscout/tests/<Screen>Test.java  scenarios about that screen

Tests read like intent and follow navigation through typed page objects::

    WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
    CatalogPage catalogPage = welcomeBackPage.tapSignIn();
    assertTrue(catalogPage.isDisplayed());
"""

from __future__ import annotations

import os
import re
from typing import Dict, List, Optional, Set

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from framework.codegen.emitters._java_common import by_expr, java_str
from framework.codegen.emitters._naming import camel, pascal
from framework.codegen.framework_model import Call, FrameworkModel, PageDef, Scenario
from framework.codegen.ir import Selector

_TEMPLATES = os.path.join(os.path.dirname(__file__), "templates", "framework", "java")
_SRC = "src/test/java/mobiscout"
_HEADER = "Auto-generated by Mobiscout. Regenerate rather than hand-edit."

_TESTNG_XML = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">\n'
    "<!-- Auto-generated by Mobiscout. Regenerate rather than hand-edit. -->\n"
    '<suite name="Mobiscout">\n'
    '  <test name="app">\n'
    "    <packages>\n"
    '      <package name="mobiscout.tests"/>\n'
    "    </packages>\n"
    "  </test>\n"
    "</suite>\n"
)


def _javadoc(text: Optional[str]) -> str:
    """Text safe inside a Javadoc comment (no comment terminator, no HTML/braces)."""
    cleaned = (text or "").replace("*/", "* /").replace("<", "&lt;").replace(">", "&gt;")
    return " ".join(cleaned.replace("{", "(").replace("}", ")").split())


def _java_opt_str(value: Optional[str]) -> str:
    """A Java string literal, or ``null`` for ``None``."""
    return "null" if value is None else java_str(value)


def _java_str_list(values: List[str]) -> str:
    """Java string literals joined for a ``List.of(...)`` argument list."""
    return ", ".join(java_str(v) for v in values)


def _by_items(sel: Selector, platform: str) -> str:
    """Primary + fallback ``AppiumBy`` expressions for a ``List.of(...)``."""
    return ", ".join(by_expr(s, platform) for s in [sel, *sel.fallbacks])


def _env() -> Environment:
    """The Jinja environment for the Java framework templates."""
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )
    env.filters.update(
        java_str=java_str,
        java_opt_str=_java_opt_str,
        java_str_list=_java_str_list,
        javadoc=_javadoc,
        by_items=_by_items,
    )
    return env


def _lower_first(name: str) -> str:
    """Decapitalise a PascalCase stem for a variable, keeping a leading acronym readable:
    ``WelcomeBack`` -> ``welcomeBack``, ``URLSettings`` -> ``urlSettings``, ``OK`` -> ``ok``."""
    run = re.match(r"^([A-Z]+)(?=[A-Z][a-z]|$)", name)
    if run:
        return run.group(1).lower() + name[len(run.group(1)) :]
    return name[:1].lower() + name[1:]


def _var(page: PageDef) -> str:
    """The page's variable name — camelCase per Java convention, never the class name."""
    return f"{_lower_first(page.name)}Page"


def _methods(fm: FrameworkModel, page: PageDef) -> List[dict]:
    """Public methods: an action per tappable/typeable element (the page's capabilities, as
    a hand-written page has), queries only where a scenario asks."""
    used_taps = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "tap"}
    used_enters = {c.element for s in fm.scenarios for c in s.calls if c.page == page.name and c.op == "enter"}
    methods: List[dict] = []
    for e in page.elements:
        label = e.label or e.key.replace("_", " ")
        base = {"key": e.key, "label": label, "pascal": pascal(e.key), "camel": camel(e.key)}
        if e.role == "input" or e.key in used_enters:
            methods.append({**base, "kind": "enter"})
        elif e.role == "tap" or e.key in used_taps:
            target = fm.page(e.navigates_to) if e.navigates_to else None
            methods.append(
                {
                    **base,
                    "kind": "tap",
                    "target": target.class_name if target else None,
                    "target_title": target.title if target else None,
                }
            )
    for kind, key in sorted(page.queries):
        e = page.element(key)
        methods.append(
            {
                "kind": kind,
                "key": key,
                "label": e.label or key.replace("_", " "),
                "pascal": pascal(key),
                "camel": camel(key),
            }
        )
    return methods


def _render_call(
    fm: FrameworkModel,
    call: Call,
    declared: Dict[str, str],
    used_pages: Set[str],
    used_asserts: Set[str],
    later_pages: Set[str],
) -> List[str]:
    """One scenario step as Java statements. A page variable is declared (typed) on first
    use; a navigating tap binds the page it returns only when a later step uses it."""
    page = fm.page(call.page)
    lines: List[str] = []
    var = declared.get(page.name)
    if var is None:
        var = declared[page.name] = _var(page)
        used_pages.add(page.name)
        lines.append(f"{page.class_name} {var} = new {page.class_name}(driver);")
    el = call.element or ""
    if call.op == "tap":
        target = page.element(el).navigates_to
        if target and target in later_pages and target != page.name:
            tpage = fm.page(target)
            used_pages.add(target)
            if target in declared:
                lines.append(f"{declared[target]} = {var}.tap{pascal(el)}();")
            else:
                declared[target] = _var(tpage)
                lines.append(f"{tpage.class_name} {declared[target]} = {var}.tap{pascal(el)}();")
        else:
            lines.append(f"{var}.tap{pascal(el)}();")
    elif call.op == "enter":
        lines.append(f"{var}.enter{pascal(el)}({java_str(call.value or '')});")
    elif call.op == "is_displayed":
        used_asserts.add("assertTrue")
        lines.append(f"assertTrue({var}.isDisplayed());")
    elif call.op == "has":
        used_asserts.add("assertTrue")
        lines.append(f"assertTrue({var}.has{pascal(el)}());")
    elif call.op == "lacks":
        used_asserts.add("assertTrue")
        lines.append(f"assertTrue({var}.lacks{pascal(el)}());")
    elif call.op == "text_is":
        used_asserts.add("assertEquals")
        lines.append(f"assertEquals({var}.{camel(el)}Text(), {java_str(call.value or '')});")
    elif call.op == "is_enabled":
        used_asserts.add("assertTrue")
        lines.append(f"assertTrue({var}.{camel(el)}IsEnabled());")
    elif call.op == "app_running":
        used_asserts.add("assertTrue")
        lines.append(f"assertTrue({var}.isAppRunning());")
    return lines


def _render_test_class(fm: FrameworkModel, page: PageDef, scenarios: List[Scenario]) -> str:
    """One TestNG test class holding the scenarios about ``page``."""
    cls = f"{page.name}Test"
    used_pages: Set[str] = set()
    used_asserts: Set[str] = set()
    bodies: List[str] = []
    for sc in scenarios:
        declared: Dict[str, str] = {}
        lines: List[str] = []
        for i, call in enumerate(sc.calls):
            later = {c.page for c in sc.calls[i + 1 :]}
            lines.extend(_render_call(fm, call, declared, used_pages, used_asserts, later))
        body = "".join(f"        {ln}\n" for ln in lines)
        bodies.append(
            f"    /** {_javadoc(sc.description)} */\n"
            + ('    @Test(groups = "defect")\n' if sc.defect else "    @Test\n")
            + f"    public void {camel(sc.name)}() {{\n{body}    }}\n"
        )
    static = "".join(f"import static org.testng.Assert.{a};\n" for a in sorted(used_asserts))
    pages = "".join(f"import mobiscout.pages.{p.class_name};\n" for p in fm.pages if p.name in used_pages)
    return (
        "package mobiscout.tests;\n\n"
        f"{static}\n"
        f"{pages}"
        "import mobiscout.support.BaseTest;\n"
        "import org.testng.annotations.Test;\n\n"
        f"/**\n * Tests for the {_javadoc(page.title)} screen.\n *\n * <p>{_HEADER}\n */\n"
        f"public class {cls} extends BaseTest {{\n\n" + "\n".join(bodies) + "}\n"
    )


def render_java(fm: FrameworkModel) -> Dict[str, str]:
    """The TestNG Page-Object framework as a Maven project (relative path -> source)."""
    if not fm.pages:
        return {}
    env = _env()
    platform = fm.platform.value
    ios = platform == "ios"
    busy = "//XCUIElementTypeActivityIndicator" if ios else "//android.widget.ProgressBar"
    files: Dict[str, str] = {
        "pom.xml": env.get_template("pom.xml.j2").render(),
        "testng.xml": _TESTNG_XML,
        f"{_SRC}/support/BaseTest.java": env.get_template("BaseTest.java.j2").render(
            ios=ios, app_package=fm.app_package, app_activity=fm.app_activity, launch_args=fm.launch_args
        ),
        f"{_SRC}/pages/BasePage.java": env.get_template("BasePage.java.j2").render(
            ios=ios, busy=busy, app_package=fm.app_package
        ),
    }
    page_tpl = env.get_template("Page.java.j2")
    for page in fm.pages:
        files[f"{_SRC}/pages/{page.class_name}.java"] = page_tpl.render(
            page=page, platform=platform, methods=_methods(fm, page)
        )
    by_group: Dict[str, List[Scenario]] = {}
    for sc in fm.scenarios:
        by_group.setdefault(sc.group, []).append(sc)
    for page in fm.pages:
        if page.name in by_group:
            files[f"{_SRC}/tests/{page.name}Test.java"] = _render_test_class(fm, page, by_group[page.name])
    return files
