"""
Project scaffolding — wrap generated tests in a runnable project.

The emitters produce test files; this adds the shell around them (dependency
manifest, runner config, README) so a crawl output is `npm install && npm test`
away from running, instead of a folder of loose specs. One scaffold = one
platform (run the crawl per platform into its own output dir).

    scaffold_files(model, target, server) -> {relative_path: content}
"""

from __future__ import annotations

import json
from typing import Callable, Dict

from framework.codegen.ir import Platform, TestModel


def _js_webdriverio(model: TestModel, server: str) -> Dict[str, str]:
    is_ios = model.platform is Platform.IOS
    driver_pkg = "appium-xcuitest-driver" if is_ios else "appium-uiautomator2-driver"
    port = 4723
    try:
        port = int(server.rsplit(":", 1)[1].split("/")[0])
    except (IndexError, ValueError):
        pass

    if is_ios:
        cap = (
            "    platformName: 'iOS',\n"
            "    'appium:automationName': 'XCUITest',\n"
            f"    'appium:bundleId': '{model.app_package}',\n"
            "    'appium:deviceName': 'iPhone 15',\n"
        )
    else:
        activity = f"    'appium:appActivity': '{model.app_activity}',\n" if model.app_activity else ""
        cap = (
            "    platformName: 'Android',\n"
            "    'appium:automationName': 'UiAutomator2',\n"
            f"    'appium:appPackage': '{model.app_package}',\n"
            f"{activity}"
            "    'appium:deviceName': 'Android Device',\n"
        )

    package_json = {
        "name": "mobile-tests",
        "version": "1.0.0",
        "description": f"Appium/WebdriverIO tests generated for {model.app_package}",
        "private": True,
        "scripts": {"test": "wdio run wdio.conf.js"},
        "devDependencies": {
            "@wdio/cli": "^9.0.0",
            "@wdio/local-runner": "^9.0.0",
            "@wdio/mocha-framework": "^9.0.0",
            "@wdio/appium-service": "^9.0.0",
            "@wdio/spec-reporter": "^9.0.0",
            "appium": "^2.11.0",
            driver_pkg: "*",
        },
    }
    wdio_conf = (
        "// WebdriverIO config generated by Mobile Test Recorder.\n"
        "// Requires a booted device/emulator. The appium service starts the\n"
        "// Appium server for you; adjust deviceName/udid for your device.\n"
        "exports.config = {\n"
        "  runner: 'local',\n"
        f"  port: {port},\n"
        "  specs: ['./js_webdriverio/**/*.js'],\n"
        "  maxInstances: 1,\n"
        "  capabilities: [{\n"
        f"{cap}"
        "  }],\n"
        "  services: ['appium'],\n"
        "  framework: 'mocha',\n"
        "  reporters: ['spec'],\n"
        "  mochaOpts: { ui: 'bdd', timeout: 90000 },\n"
        "};\n"
    )
    readme = (
        "# Generated mobile tests (WebdriverIO + Appium)\n\n"
        f"App under test: `{model.app_package}` "
        f"({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        "npm install\n"
        f"appium driver install {'xcuitest' if is_ios else 'uiautomator2'}   # once\n"
        "# boot your device/emulator and launch the app, then:\n"
        "npm test\n"
        "```\n\n"
        "Specs are in `js_webdriverio/`. Re-run `observe crawl ... --scaffold` to refresh.\n"
    )
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "wdio.conf.js": wdio_conf,
        "README.md": readme,
    }


def _python_pytest(model: TestModel, server: str) -> Dict[str, str]:
    is_ios = model.platform is Platform.IOS
    requirements = "Appium-Python-Client>=4.0.0,<5.0.0\npytest>=8.0.0\nselenium>=4.15.0\n"
    pytest_ini = "[pytest]\ntestpaths = python_pytest\npython_files = test_*.py\n"
    readme = (
        "# Generated mobile tests (pytest + Appium)\n\n"
        f"App under test: `{model.app_package}` ({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        "python -m venv .venv && source .venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        f"appium driver install {'xcuitest' if is_ios else 'uiautomator2'}   # once\n"
        "appium &   # start the Appium server\n"
        "# boot your device/emulator and launch the app, then:\n"
        "pytest\n"
        "```\n\n"
        "Each test file spins up its own Appium session against "
        f"`{server}`. Re-run `observe crawl ... --scaffold` to refresh.\n"
    )
    return {"requirements.txt": requirements, "pytest.ini": pytest_ini, "README.md": readme}


SCAFFOLDERS: Dict[str, Callable[[TestModel, str], Dict[str, str]]] = {
    "js_webdriverio": _js_webdriverio,
    "js_cucumber": _js_webdriverio,
    "python_pytest": _python_pytest,
    "python_pytest_bdd": _python_pytest,
}


def scaffold_files(model: TestModel, target: str, server: str = "http://localhost:4723") -> Dict[str, str]:
    """Project-shell files for a target, or {} if that target has no scaffolder."""
    fn = SCAFFOLDERS.get(target)
    return fn(model, server) if fn else {}


def available_scaffolds() -> list:
    return sorted(SCAFFOLDERS)
