"""
Project scaffolding — wrap generated tests in a runnable project.

The emitters produce test files; this adds the shell around them (dependency
manifest, runner config, README) so a crawl output is `npm install && npm test`
away from running, instead of a folder of loose specs. One scaffold = one
platform (run the crawl per platform into its own output dir).

    scaffold_files(model, target, server) -> {relative_path: content}
"""

from __future__ import annotations

import json
from typing import Callable, Dict

from framework.codegen.emitters._naming import pascal
from framework.codegen.ir import Platform, TestModel


def _js_webdriverio(model: TestModel, server: str, target: str) -> Dict[str, str]:
    is_ios = model.platform is Platform.IOS
    # The same scaffolder backs both the mocha (js_webdriverio) and cucumber
    # (js_cucumber) targets; the WDIO framework, spec glob and framework dep all
    # depend on which one, and the specs live under the target's own directory.
    is_cucumber = target == "js_cucumber"
    driver_pkg = "appium-xcuitest-driver" if is_ios else "appium-uiautomator2-driver"
    framework_pkg = "@wdio/cucumber-framework" if is_cucumber else "@wdio/mocha-framework"
    port = 4723
    try:
        port = int(server.rsplit(":", 1)[1].split("/")[0])
    except (IndexError, ValueError):
        pass

    if is_ios:
        # Launch arguments used during the crawl (e.g. skip a login gate) belong in
        # the capabilities, or every spec starts at the gate the crawl skipped.
        launch_args = ""
        if model.launch_args:
            joined = ", ".join(json.dumps(a) for a in model.launch_args)
            launch_args = f"    'appium:processArguments': {{ args: [{joined}] }},\n"
        cap = (
            "    platformName: 'iOS',\n"
            "    'appium:automationName': 'XCUITest',\n"
            f"    'appium:bundleId': '{model.app_package}',\n"
            f"{launch_args}"
            "    'appium:deviceName': 'iPhone 15',\n"
        )
    else:
        activity = f"    'appium:appActivity': '{model.app_activity}',\n" if model.app_activity else ""
        cap = (
            "    platformName: 'Android',\n"
            "    'appium:automationName': 'UiAutomator2',\n"
            f"    'appium:appPackage': '{model.app_package}',\n"
            f"{activity}"
            "    'appium:deviceName': 'Android Device',\n"
        )

    package_json = {
        "name": "mobile-tests",
        "version": "1.0.0",
        "description": f"Appium/WebdriverIO tests generated for {model.app_package}",
        "private": True,
        "scripts": {"test": "wdio run wdio.conf.js"},
        "devDependencies": {
            "@wdio/cli": "^9.0.0",
            "@wdio/local-runner": "^9.0.0",
            framework_pkg: "^9.0.0",
            "@wdio/appium-service": "^9.0.0",
            "@wdio/spec-reporter": "^9.0.0",
            "appium": "^2.11.0",
            driver_pkg: "*",
        },
    }
    if is_cucumber:
        # Cucumber runs .feature files; the step definitions are loaded via require.
        specs_glob = f"./{target}/**/*.feature"
        framework_block = (
            "  framework: 'cucumber',\n"
            f"  cucumberOpts: {{ require: ['./{target}/**/*.steps.js'], timeout: 90000 }},\n"
        )
    else:
        specs_glob = f"./{target}/**/*.js"
        framework_block = "  framework: 'mocha',\n  mochaOpts: { ui: 'bdd', timeout: 90000 },\n"
    wdio_conf = (
        "// WebdriverIO config generated by Mobiscout.\n"
        "// Requires a booted device/emulator. The appium service starts the\n"
        "// Appium server for you; adjust deviceName/udid for your device.\n"
        "exports.config = {\n"
        "  runner: 'local',\n"
        f"  port: {port},\n"
        f"  specs: ['{specs_glob}'],\n"
        "  maxInstances: 1,\n"
        "  capabilities: [{\n"
        f"{cap}"
        "  }],\n"
        "  services: ['appium'],\n"
        "  reporters: ['spec'],\n"
        f"{framework_block}"
        "};\n"
    )
    readme = (
        "# Generated mobile tests (WebdriverIO + Appium)\n\n"
        f"App under test: `{model.app_package}` "
        f"({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        "npm install\n"
        f"appium driver install {'xcuitest' if is_ios else 'uiautomator2'}   # once\n"
        "# boot your device/emulator and launch the app, then:\n"
        "npm test\n"
        "```\n\n"
        f"Specs are in `{target}/`. Re-run `mobiscout crawl ... --scaffold` to refresh.\n"
    )
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "wdio.conf.js": wdio_conf,
        "README.md": readme,
    }


def _python_pytest(model: TestModel, server: str, target: str) -> Dict[str, str]:
    is_ios = model.platform is Platform.IOS
    # The BDD target's tests import pytest-bdd and live in a differently-named
    # directory, so both the requirements and pytest's testpaths depend on target.
    is_bdd = target == "python_pytest_bdd"
    # The generated code uses the options/AppiumBy API, which is stable across client 4–6;
    # the kit-execution tests run it against 6.x, so don't pin users to a stale 4.x.
    requirements = "Appium-Python-Client>=4.0.0,<7.0.0\npytest>=8.0.0\nselenium>=4.15.0,<5.0.0\n"
    if is_bdd:
        requirements += "pytest-bdd>=7.0.0\n"
    pytest_ini = f"[pytest]\ntestpaths = {target}\npython_files = test_*.py\n"
    readme = (
        "# Generated mobile tests (pytest + Appium)\n\n"
        f"App under test: `{model.app_package}` ({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        "python -m venv .venv && source .venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        f"appium driver install {'xcuitest' if is_ios else 'uiautomator2'}   # once\n"
        "appium &   # start the Appium server\n"
        "# boot your device/emulator and launch the app, then:\n"
        "pytest\n"
        "```\n\n"
        "Each test file spins up its own Appium session against the server in "
        "`MOBISCOUT_APPIUM_SERVER` (default `http://localhost:4723`); the crawl used "
        f"`{server}`. Re-run `mobiscout crawl ... --scaffold` to refresh.\n"
    )
    return {"requirements.txt": requirements, "pytest.ini": pytest_ini, "README.md": readme}


def _java_maven(model: TestModel, server: str, target: str) -> Dict[str, str]:
    """Maven project shell for the Java targets (TestNG or Cucumber).

    The emitters write files under ``<target>/mobiscout/`` (e.g. ``mobiscout/CrawlFlow.java``)
    matching their ``package mobiscout`` — so ``<target>/`` is a valid source root and the
    files compile in place. The run is driven from a ``testng.xml`` that names the class by
    its FQN (``mobiscout.CrawlFlow``); ``mvn`` compiles everything under ``<target>/``.
    (The package is ``mobiscout`` rather than ``generated`` because ``generated/`` is a
    near-universal .gitignore rule — a user committing these tests would lose them.)
    """
    is_ios = model.platform is Platform.IOS
    is_cucumber = target == "java_cucumber"
    cls = pascal(model.name)
    driver = "xcuitest" if is_ios else "uiautomator2"

    files: Dict[str, str] = {}
    if is_cucumber:
        run_class = "RunCucumberTest"
        files[f"{target}/mobiscout/{run_class}.java"] = (
            "package mobiscout;\n\n"
            "import io.cucumber.testng.AbstractTestNGCucumberTests;\n"
            "import io.cucumber.testng.CucumberOptions;\n\n"
            f'@CucumberOptions(features = "{target}", glue = "mobiscout")\n'
            f"public class {run_class} extends AbstractTestNGCucumberTests {{\n}}\n"
        )
        suite_class = f"mobiscout.{run_class}"
        extra_deps = (
            "    <dependency>\n"
            "      <groupId>io.cucumber</groupId>\n"
            "      <artifactId>cucumber-java</artifactId>\n"
            "      <version>7.18.1</version>\n"
            "      <scope>test</scope>\n"
            "    </dependency>\n"
            "    <dependency>\n"
            "      <groupId>io.cucumber</groupId>\n"
            "      <artifactId>cucumber-testng</artifactId>\n"
            "      <version>7.18.1</version>\n"
            "      <scope>test</scope>\n"
            "    </dependency>\n"
        )
    else:
        suite_class = f"mobiscout.{cls}"
        extra_deps = (
            "    <dependency>\n"
            "      <groupId>org.testng</groupId>\n"
            "      <artifactId>testng</artifactId>\n"
            "      <version>7.10.2</version>\n"
            "      <scope>test</scope>\n"
            "    </dependency>\n"
        )

    files["testng.xml"] = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">\n'
        '<suite name="MobiscoutGenerated">\n'
        '  <test name="crawl">\n'
        "    <classes>\n"
        f'      <class name="{suite_class}"/>\n'
        "    </classes>\n"
        "  </test>\n"
        "</suite>\n"
    )
    files["pom.xml"] = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<project xmlns="http://maven.apache.org/POM/4.0.0"\n'
        '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
        '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 '
        'http://maven.apache.org/xsd/maven-4.0.0.xsd">\n'
        "  <modelVersion>4.0.0</modelVersion>\n"
        "  <groupId>com.mobiscout.generated</groupId>\n"
        "  <artifactId>mobile-tests</artifactId>\n"
        "  <version>1.0.0</version>\n"
        "  <properties>\n"
        "    <maven.compiler.source>17</maven.compiler.source>\n"
        "    <maven.compiler.target>17</maven.compiler.target>\n"
        "    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n"
        "  </properties>\n"
        "  <dependencies>\n"
        "    <dependency>\n"
        "      <groupId>io.appium</groupId>\n"
        "      <artifactId>java-client</artifactId>\n"
        "      <version>9.3.0</version>\n"
        "      <scope>test</scope>\n"
        "    </dependency>\n"
        f"{extra_deps}"
        "  </dependencies>\n"
        "  <build>\n"
        f"    <testSourceDirectory>${{project.basedir}}/{target}</testSourceDirectory>\n"
        "    <plugins>\n"
        "      <plugin>\n"
        "        <groupId>org.apache.maven.plugins</groupId>\n"
        "        <artifactId>maven-surefire-plugin</artifactId>\n"
        "        <version>3.2.5</version>\n"
        "        <configuration>\n"
        "          <suiteXmlFiles>\n"
        "            <suiteXmlFile>testng.xml</suiteXmlFile>\n"
        "          </suiteXmlFiles>\n"
        "        </configuration>\n"
        "      </plugin>\n"
        "    </plugins>\n"
        "  </build>\n"
        "</project>\n"
    )
    files["README.md"] = (
        f"# Generated mobile tests (Java + {'Cucumber' if is_cucumber else 'TestNG'} + Appium)\n\n"
        f"App under test: `{model.app_package}` ({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        f"appium driver install {driver}   # once\n"
        "appium &   # start the Appium server\n"
        "# boot your device/emulator and launch the app, then:\n"
        "mvn test\n"
        "```\n\n"
        f"Tests are in `{target}/mobiscout/` (package `mobiscout`) and run via `testng.xml`. "
        "Sessions target the server in `MOBISCOUT_APPIUM_SERVER` (default "
        f"`http://localhost:4723`); the crawl used `{server}`. "
        "Re-run `mobiscout crawl ... --scaffold` to refresh.\n"
    )
    return files


def _kotlin_gradle(model: TestModel, server: str, target: str) -> Dict[str, str]:
    """Gradle (Kotlin DSL) project shell for the Appium Kotlin target — a plain JVM
    test module that drives Appium over JUnit 5. JUnit's platform discovers tests by
    scanning compiled classes, so the flat ``<target>/`` layout needs no path tricks."""
    is_ios = model.platform is Platform.IOS
    driver = "xcuitest" if is_ios else "uiautomator2"
    build = (
        "plugins {\n"
        '    kotlin("jvm") version "2.0.21"\n'
        "}\n\n"
        "repositories { mavenCentral() }\n\n"
        "dependencies {\n"
        '    testImplementation("io.appium:java-client:9.3.0")\n'
        '    testImplementation("org.junit.jupiter:junit-jupiter:5.11.0")\n'
        "}\n\n"
        "sourceSets {\n"
        f'    test {{ kotlin.srcDir("{target}") }}\n'
        "}\n\n"
        "tasks.test { useJUnitPlatform() }\n"
    )
    readme = (
        "# Generated mobile tests (Kotlin + Appium)\n\n"
        f"App under test: `{model.app_package}` ({'iOS' if is_ios else 'Android'}).\n\n"
        "## Run\n\n"
        "```bash\n"
        f"appium driver install {driver}   # once\n"
        "appium &   # start the Appium server\n"
        "# boot your device/emulator and launch the app, then:\n"
        "gradle test\n"
        "```\n\n"
        f"Tests are in `{target}/`. Sessions target the server in "
        "`MOBISCOUT_APPIUM_SERVER` (default `http://localhost:4723`); the crawl used "
        f"`{server}`. Re-run `mobiscout crawl ... --scaffold` to refresh.\n"
    )
    return {
        "build.gradle.kts": build,
        "settings.gradle.kts": 'rootProject.name = "mobile-tests"\n',
        "README.md": readme,
    }


def _kotlin_espresso(model: TestModel, server: str, target: str) -> Dict[str, str]:
    """Espresso is on-device Android instrumentation — it runs inside the app's own
    Gradle module (``src/androidTest``), not as a standalone project. So the scaffold
    is the dependency block plus instructions to drop the generated test into the app,
    not a runnable project of its own (an honest shell beats a broken one)."""
    cls = pascal(model.name)
    snippet = (
        "// Merge into your Android app module's build.gradle(.kts), and move\n"
        f"// {target}/mobiscout/{cls}Test.kt into src/androidTest/java/mobiscout/.\n"
        "dependencies {\n"
        '    androidTestImplementation("androidx.test.ext:junit:1.2.1")\n'
        '    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")\n'
        '    androidTestImplementation("androidx.test:runner:1.6.2")\n'
        "}\n\n"
        "android {\n"
        "    defaultConfig {\n"
        '        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"\n'
        "    }\n"
        "}\n"
    )
    readme = (
        "# Generated Espresso tests (Kotlin)\n\n"
        f"App under test: `{model.app_package}` (Android).\n\n"
        "Espresso runs **inside your app's** instrumented test suite, so there is no\n"
        "standalone project. To use the generated test:\n\n"
        f"1. Move `{target}/mobiscout/{cls}Test.kt` into your app module's `src/androidTest/java/mobiscout/`.\n"
        "2. Merge `espresso.gradle.kts` into that module's `build.gradle(.kts)`.\n"
        "3. Run `./gradlew connectedAndroidTest` with an emulator/device attached.\n"
    )
    return {"espresso.gradle.kts": snippet, "README.md": readme}


SCAFFOLDERS: Dict[str, Callable[[TestModel, str, str], Dict[str, str]]] = {
    "js_webdriverio": _js_webdriverio,
    "js_cucumber": _js_webdriverio,
    "python_pytest": _python_pytest,
    "python_pytest_bdd": _python_pytest,
    "java_testng": _java_maven,
    "java_cucumber": _java_maven,
    "kotlin_appium": _kotlin_gradle,
    "kotlin_espresso": _kotlin_espresso,
}


def scaffold_files(model: TestModel, target: str, server: str = "http://localhost:4723") -> Dict[str, str]:
    """Project-shell files for a target, or {} if that target has no scaffolder.

    The target name is threaded to the scaffolder so runner config points at the
    target's own directory (tests live under ``<target>/``) and pulls the matching
    dependencies (pytest-bdd / cucumber-framework for the BDD targets).
    """
    fn = SCAFFOLDERS.get(target)
    return fn(model, server, target) if fn else {}


def available_scaffolds() -> list:
    return sorted(SCAFFOLDERS)
