/**
 * SearchProductsPage — the Search products screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import BasePage from './base.page.js';
import runningShoesPage from './running-shoes.page.js';
import yourCartPage from './your-cart.page.js';

class SearchProductsPage extends BasePage {
    constructor() {
        super({
            screen: 'Search products',
            identity: 'search_products',
            locators: {
                'search_products': ['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'],
                'running_shoes': ['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'],
                'backpack': ['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'],
                'cart': ['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'],
            },
        });
    }

    /** Type `value` into Search products. */
    async enterSearchProducts(value) {
        await this._type('search_products', value);
        return this;
    }

    /** Tap Running Shoes — opens the Running Shoes screen. */
    async tapRunningShoes() {
        await this._tap('running_shoes');
        return runningShoesPage;
    }

    /** Tap Backpack. */
    async tapBackpack() {
        await this._tap('backpack');
        return this;
    }

    /** Tap Cart — opens the Your cart screen. */
    async tapCart() {
        await this._tap('cart');
        return yourCartPage;
    }

    /** Whether Backpack is shown. */
    async hasBackpack() {
        return this._isVisible('backpack');
    }

    /** Whether Cart is shown. */
    async hasCart() {
        return this._isVisible('cart');
    }

    /** Whether Running Shoes is shown. */
    async hasRunningShoes() {
        return this._isVisible('running_shoes');
    }
}

export default new SearchProductsPage();
