/**
 * WelcomeBackPage — the Welcome back screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import BasePage from './base.page.js';
import searchProductsPage from './search-products.page.js';

class WelcomeBackPage extends BasePage {
    constructor() {
        super({
            screen: 'Welcome back',
            identity: 'welcome_back',
            locators: {
                'welcome_back': ['android=new UiSelector().text("Welcome back")'],
                'email': ['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'],
                'password': ['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'],
                'remember_me': ['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'],
                'sign_in': ['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'],
                'forgot_password': ['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'],
            },
        });
    }

    /** Type `value` into Email. */
    async enterEmail(value) {
        await this._type('email', value);
        return this;
    }

    /** Type `value` into Password. */
    async enterPassword(value) {
        await this._type('password', value);
        return this;
    }

    /** Tap Remember me. */
    async tapRememberMe() {
        await this._tap('remember_me');
        return this;
    }

    /** Tap Sign in — opens the Search products screen. */
    async tapSignIn() {
        await this._tap('sign_in');
        return searchProductsPage;
    }

    /** Tap Forgot password?. */
    async tapForgotPassword() {
        await this._tap('forgot_password');
        return this;
    }

    /** Whether Email is shown. */
    async hasEmail() {
        return this._isVisible('email');
    }

    /** Whether Forgot password? is shown. */
    async hasForgotPassword() {
        return this._isVisible('forgot_password');
    }

    /** Whether Password is shown. */
    async hasPassword() {
        return this._isVisible('password');
    }

    /** Whether Remember me is shown. */
    async hasRememberMe() {
        return this._isVisible('remember_me');
    }

    /** Whether Sign in is shown. */
    async hasSignIn() {
        return this._isVisible('sign_in');
    }
}

export default new WelcomeBackPage();
