/**
 * YourCartPage — the Your cart screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import BasePage from './base.page.js';

class YourCartPage extends BasePage {
    constructor() {
        super({
            screen: 'Your cart',
            identity: 'your_cart',
            locators: {
                'your_cart': ['android=new UiSelector().text("Your cart")'],
                'place_order': ['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'],
            },
        });
    }

    /** Tap Place order. */
    async tapPlaceOrder() {
        await this._tap('place_order');
        return this;
    }

    /** Whether Place order is shown. */
    async hasPlaceOrder() {
        return this._isVisible('place_order');
    }
}

export default new YourCartPage();
