/*
 * Step definitions for CrawlFlow — auto-generated by Mobiscout.
 * Auto-generated from an autonomous crawl (state + navigation).
 * Cucumber.js + WebdriverIO. The `driver`/`expect` globals come from the
 * WebdriverIO cucumber framework adapter.
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */

const { Given, When, Then } = require('@cucumber/cucumber');

const APP_PACKAGE = 'com.example.shop';

// Friendly target name -> ranked selectors (primary first, then fallbacks).
const LOCATORS = {
    'Welcome back': ['android=new UiSelector().text("Welcome back")'],
    'Email': ['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'],
    'Password': ['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'],
    'Remember me': ['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'],
    'Sign in': ['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'],
    'Forgot password?': ['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'],
    'Search products': ['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'],
    'Running Shoes': ['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'],
    'Backpack': ['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'],
    'Cart': ['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'],
    'Add to cart': ['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'],
    'Your cart': ['android=new UiSelector().text("Your cart")'],
    'Place order': ['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'],
};

// Condition-based wait budget (ms) — poll for the element instead of a fixed
// pause, so steps stay in sync with async UI without flaking at machine speed.
const TIMEOUT = 10000;

// Resolve a friendly target to an element, waiting for it to appear and
// self-healing through its ranked selectors (each poll tries every selector).
async function find(target) {
    let found = null;
    await driver.waitUntil(
        async () => {
            for (const selector of LOCATORS[target]) {
                const el = await driver.$(selector);
                if (await el.isExisting()) {
                    found = el;
                    return true;
                }
            }
            return false;
        },
        { timeout: TIMEOUT, interval: 300, timeoutMsg: `No locator matched for target: ${target}` }
    );
    return found;
}

Given('the app is launched', async () => {
    await driver.activateApp(APP_PACKAGE);
});

When('I enter {string} into {string}', async (text, target) => {
    await (await find(target)).setValue(text);
});

When('I tap {string}', async (target) => {
    await (await find(target)).click();
});

When('I swipe {word}', async (direction) => {
    const size = await driver.getWindowSize();
    await driver.execute('mobile: swipeGesture', { left: Math.round(size.width * 0.1), top: Math.round(size.height * 0.1), width: Math.round(size.width * 0.8), height: Math.round(size.height * 0.8), direction, percent: 0.75 });
});

When('I wait {int} seconds', async (seconds) => {
    // Condition-based: wait for the screen to render rather than a fixed pause.
    await driver.waitUntil(async () => (await driver.$$('//*')).length > 0, { timeout: seconds * 1000, interval: 300 });
});

When('I press back', async () => {
    await driver.back();
});

When('I long-press {string}', async (target) => {
    await driver.execute('mobile: longClickGesture', { elementId: (await find(target)).elementId, duration: 1000 });
});

When('I scroll to {string}', async (target) => {
    await $(`android=new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().textContains("${target}"))`);
});

When('I open the deep link {string}', async (url) => {
    await driver.url(url);
});

When('I press the {string} key', async (key) => {
    const codes = { BACK: 4, HOME: 3, ENTER: 66, TAB: 61, SEARCH: 84, APP_SWITCH: 187, DEL: 67 };
    await driver.pressKeyCode(codes[key.toUpperCase()] || 0);
});

When('I switch to the {word} context', async (ctx) => {
    // Hybrid apps host web content in a WebView; drive it by switching the Appium
    // context to the WEBVIEW handle and back to native.
    if (ctx === 'web') {
        await driver.switchContext((await driver.getContexts()).find((c) => String(c).toUpperCase().includes('WEBVIEW')));
    } else {
        await driver.switchContext('NATIVE_APP');
    }
});

Then('{string} is visible', async (target) => {
    await expect(await find(target)).toBeDisplayed();
});

Then('{string} text is {string}', async (target, expected) => {
    await expect(await find(target)).toHaveText(expected);
});

Then('{string} is enabled', async (target) => {
    await expect(await find(target)).toBeEnabled();
});
