/*
 * Step definitions for CrawlFlow — auto-generated by Mobile Test Recorder.
 * Auto-generated from an autonomous crawl (state + navigation).
 * Cucumber.js + WebdriverIO. The `driver`/`expect` globals come from the
 * WebdriverIO cucumber framework adapter.
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */

const { Given, When, Then } = require('@cucumber/cucumber');

const APP_PACKAGE = 'com.example.shop';

// Friendly target name -> ranked selectors (primary first, then fallbacks).
const LOCATORS = {
    'Welcome back': ['android=new UiSelector().text("Welcome back")'],
    'Email': ['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'],
    'Password': ['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'],
    'Remember me': ['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'],
    'Sign in': ['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'],
    'Search products': ['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'],
    'Running Shoes': ['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'],
    'Backpack': ['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'],
    'Cart': ['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'],
    'Add to cart': ['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'],
    'Your cart': ['android=new UiSelector().text("Your cart")'],
    'Place order': ['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'],
};

// Resolve a friendly target to an element via its ranked selectors (self-healing).
async function find(target) {
    for (const selector of LOCATORS[target]) {
        const el = await driver.$(selector);
        if (await el.isExisting()) {
            return el;
        }
    }
    throw new Error(`No locator matched for target: ${target}`);
}

Given('the app is launched', async () => {
    await driver.activateApp(APP_PACKAGE);
});

When('I enter {string} into {string}', async (text, target) => {
    await (await find(target)).setValue(text);
});

When('I tap {string}', async (target) => {
    await (await find(target)).click();
});

When('I wait {int} seconds', async (seconds) => {
    await driver.pause(seconds * 1000);
});

When('I press back', async () => {
    await driver.back();
});

Then('{string} is visible', async (target) => {
    await expect(await find(target)).toBeDisplayed();
});

Then('{string} text is {string}', async (target, expected) => {
    await expect(await find(target)).toHaveText(expected);
});

Then('{string} is enabled', async (target) => {
    await expect(await find(target)).toBeEnabled();
});
