/*
 * LoginFlowSteps — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * Cucumber-JVM step definitions for LoginFlow.feature.
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import io.cucumber.java.After;
import io.cucumber.java.Before;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.URL;
import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class LoginFlowSteps {

    private static final String APP_PACKAGE = "com.example.app";

    // Friendly target name -> ranked locators (primary first, then fallbacks).
    private static final Map<String, By[]> LOCATORS = new HashMap<>();
    static {
        LOCATORS.put("user_field", new By[]{AppiumBy.id("user_field"), AppiumBy.xpath("//input[1]")});
        LOCATORS.put("login_btn", new By[]{AppiumBy.accessibilityId("login_btn")});
        LOCATORS.put("Welcome", new By[]{AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")")});
    }

    private AppiumDriver driver;

    // Run anywhere without regenerating: point at a different Appium/cloud-grid
    // hub with MOBISCOUT_APPIUM_SERVER.
    private static final String SERVER =
        System.getenv().getOrDefault("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723");

    @Before
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        options.setAppPackage(APP_PACKAGE);
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL(SERVER), options);
    }

    @After
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Resolve a friendly target to an element via its ranked locators. */
    private static final Duration TIMEOUT = Duration.ofSeconds(10);

    /**
     * Locate an element, waiting for it to appear and self-healing through its
     * ranked locators — a condition-based wait, not an instant lookup that flakes.
     */
    private WebElement find(String target) {
        try {
            return new WebDriverWait(driver, TIMEOUT).until(d -> {
                for (By by : LOCATORS.get(target)) {
                    try {
                        return d.findElement(by);
                    } catch (NoSuchElementException ignored) {
                    }
                }
                return null;
            });
        } catch (TimeoutException e) {
            throw new NoSuchElementException("No locator matched for target: " + target + " within " + TIMEOUT.getSeconds() + "s");
        }
    }

    @Given("the app is launched")
    public void theAppIsLaunched() {
        driver.activateApp(APP_PACKAGE);
    }

    @When("I enter {string} into {string}")
    public void iEnterInto(String text, String target) {
        find(target).sendKeys(text);
    }

    @When("I tap {string}")
    public void iTap(String target) {
        find(target).click();
    }

    @When("I swipe {word}")
    public void iSwipe(String direction) {
        org.openqa.selenium.Dimension size = driver.manage().window().getSize();
        Map<String, Object> swipeArgs = new HashMap<>();
        swipeArgs.put("left", (int) (size.getWidth() * 0.1));
        swipeArgs.put("top", (int) (size.getHeight() * 0.1));
        swipeArgs.put("width", (int) (size.getWidth() * 0.8));
        swipeArgs.put("height", (int) (size.getHeight() * 0.8));
        swipeArgs.put("direction", direction);
        swipeArgs.put("percent", 0.75);
        driver.executeScript("mobile: swipeGesture", swipeArgs);
    }

    @When("I wait {int} seconds")
    public void iWaitSeconds(Integer seconds) {
        // Condition-based: wait for the screen to render rather than a global implicit wait.
        new WebDriverWait(driver, Duration.ofSeconds(seconds)).until(d -> !d.findElements(By.xpath("//*")).isEmpty());
    }

    @When("I press back")
    public void iPressBack() {
        driver.navigate().back();
    }

    @When("I long-press {string}")
    public void iLongPress(String target) {
        new org.openqa.selenium.interactions.Actions(driver).clickAndHold(find(target)).pause(java.time.Duration.ofSeconds(1)).release().perform();
    }

    @When("I scroll to {string}")
    public void iScrollTo(String target) {
        driver.findElement(io.appium.java_client.AppiumBy.androidUIAutomator(
            "new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(new UiSelector().textContains(\"" + target + "\"))"));
    }

    @When("I open the deep link {string}")
    public void iOpenDeepLink(String url) {
        driver.get(url);
    }

    @When("I press the {string} key")
    public void iPressKey(String key) {
        ((io.appium.java_client.android.AndroidDriver) driver).pressKey(
            new io.appium.java_client.android.nativekey.KeyEvent(
                io.appium.java_client.android.nativekey.AndroidKey.valueOf(key.toUpperCase())));
    }

    @When("I switch to the {word} context")
    public void iSwitchContext(String ctx) {
        // Hybrid apps host web content in a WebView; drive it by switching the
        // Appium context to the WEBVIEW handle and back to native.
        io.appium.java_client.remote.SupportsContextSwitching cs =
            (io.appium.java_client.remote.SupportsContextSwitching) driver;
        if (ctx.equals("web")) {
            cs.context(cs.getContextHandles().stream()
                .filter(c -> c.toUpperCase().contains("WEBVIEW")).findFirst().orElse("NATIVE_APP"));
        } else {
            cs.context("NATIVE_APP");
        }
    }

    @Then("{string} is visible")
    public void isVisible(String target) {
        if (!find(target).isDisplayed()) {
            throw new AssertionError("Element not visible: " + target);
        }
    }

    @Then("{string} text is {string}")
    public void textIs(String target, String expected) {
        String actual = find(target).getText();
        if (!expected.equals(actual)) {
            throw new AssertionError("Expected text " + expected + " but got " + actual);
        }
    }

    @Then("{string} is enabled")
    public void isEnabled(String target) {
        if (!find(target).isEnabled()) {
            throw new AssertionError("Element not enabled: " + target);
        }
    }
}
