"""
Behave hooks.

Fast by design: ONE Appium session serves the whole run (opening a session costs 5-10 s),
and each scenario starts from a cold restart of the app (~1-2 s) — every scenario still
begins clean, without paying for a new session each time.

Run against another Appium server or a cloud grid with MOBISCOUT_APPIUM_SERVER.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

import os

from appium import webdriver
from appium.options.android import UiAutomator2Options

APP = "com.example.shop"
SERVER = os.environ.get("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723")


def _options():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = APP
    options.app_activity = ".MainActivity"
    # Window animations only cost time in a test run.
    options.set_capability("appium:disableWindowAnimation", True)
    # Keep the app's data between tests; each test restarts the app itself (below).
    options.set_capability("appium:noReset", True)
    return options


class Session:
    """The Appium session the whole run shares, reopened if it died.

    Opening a session costs 5-10 s, so one serves every test. But an Appium server or driver
    that crashes must cost ONE test, not every test after it: before each test the session
    is checked with one cheap call and reopened if it is gone.
    """

    def __init__(self):
        self._driver = None

    def restart_app(self):
        """The live session with the app cold-restarted, so the test begins clean."""
        driver = self._live()
        try:
            driver.terminate_app(APP)
        except Exception:
            pass  # the app was not running
        driver.activate_app(APP)
        return driver

    def close(self):
        """End the session, if one is open."""
        if self._driver is not None:
            try:
                self._driver.quit()
            except Exception:
                pass  # already gone
            self._driver = None

    def _live(self):
        if self._driver is not None and not self._alive():
            self.close()
        if self._driver is None:
            self._driver = webdriver.Remote(SERVER, options=_options())
            try:
                # Don't wait for the UI to go idle after every command: a live app rarely
                # does, and the driver would otherwise stall up to 10 s per command.
                self._driver.update_settings({"waitForIdleTimeout": 100})
            except Exception:
                pass
        return self._driver

    def _alive(self):
        try:
            self._driver.query_app_state(APP)
            return True
        except Exception:
            return False


def before_all(context):
    """The session the whole run shares (opened on the first scenario)."""
    context.session = Session()


def before_scenario(context, scenario):
    """The live session (reopened if it died), with the app restarted so every scenario begins clean."""
    context.driver = context.session.restart_app()


def after_all(context):
    """Close the session."""
    context.session.close()
