Feature: Running Shoes screen
  What the Running Shoes screen of com.example.shop shows and does.
  Auto-generated by Mobiscout. Regenerate rather than hand-edit.

  Scenario: The running shoes screen shows its expected controls
    Given I am on the Running Shoes screen
    Then I see Running Shoes on the Running Shoes screen
    And I see the Running Shoes screen
