Feature: Welcome back screen
  What the Welcome back screen of com.example.shop shows and does.
  Auto-generated by Mobiscout. Regenerate rather than hand-edit.

  Background:
    Given I am on the Welcome back screen

  Scenario: The welcome back screen shows its expected controls
    Then I see Email
    And I see Password
    And I see Remember me
    And I see Sign in
    And I see Forgot password?

  Scenario Outline: Submitting the welcome back form with invalid data or empty fields is rejected
    When I enter "<email>" into Email
    And I enter "<password>" into Password
    And I tap Sign in
    Then I am still on the Welcome back screen

    Examples:
      | email | password |
      | not-an-email | 1 |
      |  |  |

  Scenario: The welcome back form survives too-long input
    When I enter 300 characters into Email
    And I enter 300 characters into Password
    And I tap Sign in
    Then the app is still running

  Scenario: The welcome back form survives special characters
    When I enter "!@#$%^&*()_+-=[]{};:,.?/~`'" into Email
    And I enter "!@#$%^&*()_+-=[]{};:,.?/~`'" into Password
    And I tap Sign in
    Then the app is still running
