"""
LoginFlow — auto-generated by Mobiscout.
Generated login flow used for golden tests.
App under test: com.example.app
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import json
import os

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds). We poll for the element instead of a
# fixed sleep or a global implicit wait (which silently fights explicit waits),
# so tests stay in sync with async UI without paying a worst-case sleep every step.
_TIMEOUT = 10

# A generic "busy" indicator per platform — used by _settle to wait out a
# transition. Not app-specific, so it's a no-op on screens that show no spinner.
_BUSY_XPATH = "//android.widget.ProgressBar"


def _settle(driver, timeout=_TIMEOUT):
    """Middle beat of ``act -> wait-busy-clears -> assert``: after an action that
    triggers a transition, wait for a loading/activity indicator to disappear so the
    next step doesn't act on a mid-transition screen or read a stale result. A no-op
    when nothing is spinning; a stuck indicator is tolerated, not failed."""
    try:
        WebDriverWait(driver, timeout, poll_frequency=0.3).until(
            lambda d: not d.find_elements(AppiumBy.XPATH, _BUSY_XPATH)
        )
    except TimeoutException:
        pass


def _find(driver, primary, fallbacks, timeout=_TIMEOUT):
    """Locate an element, waiting for it to appear and self-healing through ranked
    fallback locators.

    Each poll tries every locator (primary first) until one resolves or the wait
    times out — a real condition-based wait, so a slow/async screen no longer flakes
    the way an instant ``find_element`` does at machine speed.
    """
    locators = [primary, *fallbacks]

    def _locate(drv):
        for by, value in locators:
            try:
                return drv.find_element(by, value)
            except NoSuchElementException:
                continue
        return False

    try:
        return WebDriverWait(driver, timeout, poll_frequency=0.3).until(_locate)
    except TimeoutException:
        by, value = primary
        raise NoSuchElementException(
            f"None of the locators matched within {timeout}s (primary + {len(fallbacks)} fallbacks): {by}={value}"
        )


# Test input data, kept out of the test body so it changes in one place (and can be
# parameterised or pulled from a fixture later) instead of being coupled inline. Each
# (field, value) a case types gets a unique key, so a positive and a negative case on
# the same field both survive here instead of one overwriting the other.
TEST_DATA = {
    "user_field": "alice@example.com",
}


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = "com.example.app"
    options.app_activity = ".MainActivity"
    # A fresh session per test with a reset app = isolated, parallel-safe state.
    options.set_capability("noReset", False)
    # Run anywhere without regenerating: point at a different Appium/cloud-grid hub
    # with MOBISCOUT_APPIUM_SERVER, and merge extra capabilities (e.g. a
    # BrowserStack/Sauce options block) from MOBISCOUT_EXTRA_CAPS (a JSON object).
    for _cap, _value in json.loads(os.environ.get("MOBISCOUT_EXTRA_CAPS", "{}")).items():
        options.set_capability(_cap, _value)
    _server = os.environ.get("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723")
    drv = webdriver.Remote(_server, options=options)
    yield drv
    drv.quit()


def test_login(driver):
    """User can log in with valid credentials"""
    # Open app
    driver.activate_app("com.example.app")
    # Enter email
    _find(driver, (AppiumBy.ID, "user_field"), [(AppiumBy.XPATH, "//input[1]")]).send_keys(TEST_DATA["user_field"])
    _settle(driver)
    # Tap login
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "login_btn"), []).click()
    _settle(driver)
    # Wait for home
    # Condition-based: wait for the screen to render rather than sleeping a fixed time.
    WebDriverWait(driver, 3).until(lambda d: d.find_elements(AppiumBy.XPATH, "//*"))
    # Swipe up to reveal content
    _size = driver.get_window_size()
    driver.execute_script("mobile: swipeGesture", {"left": int(_size["width"] * 0.1), "top": int(_size["height"] * 0.1), "width": int(_size["width"] * 0.8), "height": int(_size["height"] * 0.8), "direction": "up", "percent": 0.75})
    _settle(driver)
    # Dismiss a dialog
    driver.back()
    _settle(driver)
    # Welcome message shown
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome\")"), []).is_displayed()

