"""
LoginFlow — auto-generated by Mobiscout.
Generated login flow used for golden tests.
App under test: com.example.app
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import json
import os

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException, WebDriverException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds). We poll for the element instead of a
# fixed sleep or a global implicit wait (which silently fights explicit waits),
# so tests stay in sync with async UI without paying a worst-case sleep every step.
_TIMEOUT = 10
# How many times _find scrolls looking for an off-screen element before giving up.
_SCROLL_TRIES = 4


def _scroll_down(driver):
    """One scroll-down gesture — used by _find to bring a below-the-fold element into
    view. Platform-aware: iOS uses `mobile: scroll`, Android `mobile: scrollGesture`."""
    _s = driver.get_window_size()
    driver.execute_script("mobile: scrollGesture", {
        "left": int(_s["width"] * 0.1), "top": int(_s["height"] * 0.2),
        "width": int(_s["width"] * 0.8), "height": int(_s["height"] * 0.6),
        "direction": "down", "percent": 0.8,
    })

# A generic "busy" indicator per platform — used by _settle to wait out a
# transition. Not app-specific, so it's a no-op on screens that show no spinner.
_BUSY_XPATH = "//android.widget.ProgressBar"


def _settle(driver, timeout=_TIMEOUT):
    """Middle beat of ``act -> wait-busy-clears -> assert``: after an action that
    triggers a transition, wait for a loading/activity indicator to disappear so the
    next step doesn't act on a mid-transition screen or read a stale result. A no-op
    when nothing is spinning; a stuck indicator is tolerated, not failed."""
    try:
        WebDriverWait(driver, timeout, poll_frequency=0.3).until(
            lambda d: not d.find_elements(AppiumBy.XPATH, _BUSY_XPATH)
        )
    except TimeoutException:
        pass
    # A raised soft keyboard is a transient input surface, not part of the screen under
    # test. With the usual adjustResize window mode it shrinks the layout, which can drop a
    # bottom-anchored control (a FAB, a bottom bar) out of the queryable accessibility tree
    # entirely; and even when the control survives, it sits behind the IME so is_displayed()
    # reads False. Either way the next assert flakes on a control that genuinely belongs to
    # the screen (observed on Omni-Notes: the search screen's FAB, present ~40% of reads).
    # Dismissing the keyboard as part of settling makes the screen deterministic. Best-effort:
    # a driver that can't report/close the keyboard is left as-is rather than failed.
    try:
        if driver.is_keyboard_shown():
            driver.hide_keyboard()
    except Exception:
        pass


def _find(driver, primary, fallbacks, timeout=_TIMEOUT):
    """Locate an element, waiting for it to appear and self-healing through ranked
    fallback locators.

    Each poll tries every locator (primary first) until one resolves or the wait
    times out — a real condition-based wait, so a slow/async screen no longer flakes
    the way an instant ``find_element`` does at machine speed.
    """
    locators = [primary, *fallbacks]

    def _locate(drv):
        for by, value in locators:
            try:
                return drv.find_element(by, value)
            except NoSuchElementException:
                continue
            except WebDriverException as exc:
                # An animating screen (a splash, an onboarding carousel) can keep the
                # accessibility tree busy: UiAutomator2 then answers "Timed out waiting
                # for the root AccessibilityNodeInfo" instead of "not found". That is
                # transient, so keep polling within the wait budget rather than failing
                # a test for something that resolves a moment later.
                if "AccessibilityNodeInfo" not in str(exc):
                    raise
                return False
        return False

    try:
        return WebDriverWait(driver, timeout, poll_frequency=0.3).until(_locate)
    except TimeoutException:
        pass

    # Below the fold: the element may just need scrolling into view. Scroll down a few
    # times, retrying after each — so a tap/assert on an off-screen control (a long
    # list, a form field under the keyboard) isn't a false NoSuchElement.
    for _ in range(_SCROLL_TRIES):
        try:
            _scroll_down(driver)
        except Exception:
            break
        found = _locate(driver)
        if found:
            return found

    by, value = primary
    raise NoSuchElementException(
        f"None of the locators matched within {timeout}s + {_SCROLL_TRIES} scrolls "
        f"(primary + {len(fallbacks)} fallbacks): {by}={value}"
    )


# Test input data, kept out of the test body so it changes in one place (and can be
# parameterised or pulled from a fixture later) instead of being coupled inline. Each
# (field, value) a case types gets a unique key, so a positive and a negative case on
# the same field both survive here instead of one overwriting the other.
TEST_DATA = {
    "user_field": "alice@example.com",
}


def _make_driver():
    """Open one Appium session against the device/simulator."""
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = "com.example.app"
    options.app_activity = ".MainActivity"
    options.set_capability("noReset", False)
    # Starting a session is by far the slow part (~30 s vs a ~3 s app-data reset, measured),
    # and on a loaded machine UiAutomator2's server occasionally misses the default 30 s and
    # the session ERRORS before the test runs ("instrumentation process cannot be
    # initialized"), which reads as a broken test rather than a slow emulator. Appium's own
    # advice for that message is a longer launch budget — free when the server starts promptly.
    options.set_capability("uiautomator2ServerLaunchTimeout", 90_000)
    options.set_capability("uiautomator2ServerInstallTimeout", 90_000)
    # Run anywhere without regenerating: point at a different Appium/cloud-grid hub
    # with MOBISCOUT_APPIUM_SERVER, and merge extra capabilities (e.g. a
    # BrowserStack/Sauce options block) from MOBISCOUT_EXTRA_CAPS (a JSON object).
    for _cap, _value in json.loads(os.environ.get("MOBISCOUT_EXTRA_CAPS", "{}")).items():
        options.set_capability(_cap, _value)
    _server = os.environ.get("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723")
    return webdriver.Remote(_server, options=options)


def _reset_app(drv):
    """Return the app to first-run state before a test.

    `noReset` alone does NOT clear an already-installed app's data, so tests would inherit
    whatever the last one left behind — and these tests came from a crawl that itself
    changed things (it taps buttons: adds items, dismisses onboarding, leaves a sheet open).
    A case asserting the first screen then fails for a reason unrelated to the app being
    broken. Clearing makes the starting point the one the crawl described.

    Set MOBISCOUT_KEEP_APP_DATA=1 to keep the device's existing state instead (e.g. an app
    that needs a manually provisioned account).
    """
    if os.environ.get("MOBISCOUT_KEEP_APP_DATA") == "1":
        return
    try:
        drv.execute_script("mobile: clearApp", {"appId": "com.example.app"})
        # Relaunch by explicit component, not activateApp: an app that declares more than one
        # launcher entry (a debug build shipping LeakCanary adds a second icon) makes
        # Android's launcher resolution ambiguous, and activateApp then quietly fails —
        # leaving whatever app was already on screen, so the test would run against the wrong
        # app instead of failing.
        drv.execute_script(
            "mobile: startActivity",
            {"intent": "com.example.app/.MainActivity"},
        )
    except Exception:
        pass  # older driver, or an app that can't be cleared — run against live state


@pytest.fixture(scope="session")
def _appium():
    """One Appium session for the whole run.

    Creating a session is the expensive part (see _make_driver), so sharing it across tests
    turns a kit's runtime from session-cost × N into session-cost + reset × N — a large win
    on a kit of any size — while the per-test reset in the `driver` fixture keeps each test
    isolated from the last. Under pytest-xdist this is one session per worker.
    """
    drv = _make_driver()
    yield drv
    drv.quit()


@pytest.fixture()
def driver(_appium):
    """The shared session, returned to first-run state before each test."""
    _reset_app(_appium)
    return _appium


def test_login(driver):
    "User can log in with valid credentials"
    # Open app
    driver.activate_app("com.example.app")
    # Enter email
    _find(driver, (AppiumBy.ID, "user_field"), [(AppiumBy.XPATH, "//input[1]")]).send_keys(TEST_DATA["user_field"])
    _settle(driver)
    # Tap login
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "login_btn"), []).click()
    _settle(driver)
    # Wait for home
    # Condition-based: wait for the screen to render rather than sleeping a fixed time.
    WebDriverWait(driver, 3).until(lambda d: d.find_elements(AppiumBy.XPATH, "//*"))
    # Swipe up to reveal content
    _size = driver.get_window_size()
    driver.execute_script("mobile: swipeGesture", {"left": int(_size["width"] * 0.1), "top": int(_size["height"] * 0.1), "width": int(_size["width"] * 0.8), "height": int(_size["height"] * 0.8), "direction": "up", "percent": 0.75})
    _settle(driver)
    # Dismiss a dialog
    driver.back()
    _settle(driver)
    # Welcome message shown
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome\")"), []).is_displayed()

