"""
LoginFlow — auto-generated by Mobiscout.
Generated login flow used for golden tests.
App under test: com.example.app
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds). We poll for the element instead of a
# fixed sleep or a global implicit wait (which silently fights explicit waits),
# so tests stay in sync with async UI without paying a worst-case sleep every step.
_TIMEOUT = 10


def _find(driver, primary, fallbacks, timeout=_TIMEOUT):
    """Locate an element, waiting for it to appear and self-healing through ranked
    fallback locators.

    Each poll tries every locator (primary first) until one resolves or the wait
    times out — a real condition-based wait, so a slow/async screen no longer flakes
    the way an instant ``find_element`` does at machine speed.
    """
    locators = [primary, *fallbacks]

    def _locate(drv):
        for by, value in locators:
            try:
                return drv.find_element(by, value)
            except NoSuchElementException:
                continue
        return False

    try:
        return WebDriverWait(driver, timeout, poll_frequency=0.3).until(_locate)
    except TimeoutException:
        by, value = primary
        raise NoSuchElementException(
            f"None of the locators matched within {timeout}s (primary + {len(fallbacks)} fallbacks): {by}={value}"
        )


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = "com.example.app"
    options.app_activity = ".MainActivity"
    drv = webdriver.Remote("http://localhost:4723", options=options)
    yield drv
    drv.quit()


def test_login(driver):
    """User can log in with valid credentials"""
    # Open app
    driver.activate_app("com.example.app")
    # Enter email
    _find(driver, (AppiumBy.ID, "user_field"), [(AppiumBy.XPATH, "//input[1]")]).send_keys("alice@example.com")
    # Tap login
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "login_btn"), []).click()
    # Wait for home
    # Condition-based: wait for the screen to render rather than sleeping a fixed time.
    WebDriverWait(driver, 3).until(lambda d: d.find_elements(AppiumBy.XPATH, "//*"))
    # Dismiss a dialog
    driver.back()
    # Welcome message shown
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome\")"), []).is_displayed()

