package mobiscout.tests;

import static org.testng.Assert.assertTrue;

import mobiscout.pages.WelcomeBackPage;
import mobiscout.pages.SearchProductsPage;
import mobiscout.pages.RunningShoesPage;
import mobiscout.support.BaseTest;
import org.testng.annotations.Test;

/**
 * Tests for the Running Shoes screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class RunningShoesTest extends BaseTest {

    /** The running shoes screen shows its expected controls. */
    @Test
    public void runningShoesScreenShowsExpectedControls() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        SearchProductsPage searchProductsPage = welcomeBackPage.tapSignIn();
        RunningShoesPage runningShoesPage = searchProductsPage.tapRunningShoes();
        assertTrue(runningShoesPage.hasRunningShoes());
        assertTrue(runningShoesPage.isDisplayed());
    }
}
