package mobiscout.tests;

import static org.testng.Assert.assertTrue;

import mobiscout.pages.WelcomeBackPage;
import mobiscout.pages.SearchProductsPage;
import mobiscout.support.BaseTest;
import org.testng.annotations.Test;

/**
 * Tests for the Search products screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class SearchProductsTest extends BaseTest {

    /** The search products screen shows its expected controls. */
    @Test
    public void searchProductsScreenShowsExpectedControls() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        SearchProductsPage searchProductsPage = welcomeBackPage.tapSignIn();
        assertTrue(searchProductsPage.isDisplayed());
        assertTrue(searchProductsPage.hasRunningShoes());
        assertTrue(searchProductsPage.hasBackpack());
        assertTrue(searchProductsPage.hasCart());
    }
}
