package mobiscout.tests;

import static org.testng.Assert.assertTrue;

import mobiscout.pages.WelcomeBackPage;
import mobiscout.support.BaseTest;
import org.testng.annotations.Test;

/**
 * Tests for the Welcome back screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class WelcomeBackTest extends BaseTest {

    /** The welcome back screen shows its expected controls. */
    @Test
    public void welcomeBackScreenShowsExpectedControls() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        assertTrue(welcomeBackPage.isDisplayed());
        assertTrue(welcomeBackPage.hasEmail());
        assertTrue(welcomeBackPage.hasPassword());
        assertTrue(welcomeBackPage.hasRememberMe());
        assertTrue(welcomeBackPage.hasSignIn());
        assertTrue(welcomeBackPage.hasForgotPassword());
    }

    /** Submitting the welcome back form with invalid data is rejected. */
    @Test
    public void rejectsInvalidInputOnWelcomeBack() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("not-an-email");
        welcomeBackPage.enterPassword("1");
        welcomeBackPage.tapSignIn();
        assertTrue(welcomeBackPage.isDisplayed());
    }

    /** Submitting the welcome back form with empty fields is rejected. */
    @Test
    public void rejectsEmptyInputOnWelcomeBack() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("");
        welcomeBackPage.enterPassword("");
        welcomeBackPage.tapSignIn();
        assertTrue(welcomeBackPage.isDisplayed());
    }

    /** The welcome back form survives too-long input. */
    @Test
    public void survivesTooLongOnWelcomeBack() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("x".repeat(300));
        welcomeBackPage.enterPassword("x".repeat(300));
        welcomeBackPage.tapSignIn();
        assertTrue(welcomeBackPage.isAppRunning());
    }

    /** The welcome back form survives special characters. */
    @Test
    public void survivesSpecialCharactersOnWelcomeBack() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("!@#$%^&*()_+-=[]{};:,.?/~`'");
        welcomeBackPage.enterPassword("!@#$%^&*()_+-=[]{};:,.?/~`'");
        welcomeBackPage.tapSignIn();
        assertTrue(welcomeBackPage.isAppRunning());
    }
}
