package mobiscout.tests;

import static org.testng.Assert.assertTrue;

import mobiscout.pages.WelcomeBackPage;
import mobiscout.pages.SearchProductsPage;
import mobiscout.pages.RunningShoesPage;
import mobiscout.pages.YourCartPage;
import mobiscout.support.BaseTest;
import org.testng.annotations.Test;

/**
 * Tests for the Your cart screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class YourCartTest extends BaseTest {

    /** The your cart screen shows its expected controls. */
    @Test
    public void yourCartScreenShowsExpectedControls() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        SearchProductsPage searchProductsPage = welcomeBackPage.tapSignIn();
        YourCartPage yourCartPage = searchProductsPage.tapCart();
        assertTrue(yourCartPage.isDisplayed());
        assertTrue(yourCartPage.hasPlaceOrder());
    }

    /** The journey from Welcome back through Search products, Running Shoes to Your cart. */
    @Test
    public void journeyFromSignInToAddToCart() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("test@example.com");
        welcomeBackPage.enterPassword("Password123!");
        welcomeBackPage.tapRememberMe();
        SearchProductsPage searchProductsPage = welcomeBackPage.tapSignIn();
        assertTrue(searchProductsPage.isDisplayed());
        searchProductsPage.enterSearchProducts("test");
        RunningShoesPage runningShoesPage = searchProductsPage.tapRunningShoes();
        assertTrue(runningShoesPage.isDisplayed());
        YourCartPage yourCartPage = runningShoesPage.tapAddToCart();
        assertTrue(yourCartPage.isDisplayed());
    }

    /** The journey from Welcome back through Search products to Your cart. */
    @Test
    public void journeyFromSignInToCart() {
        WelcomeBackPage welcomeBackPage = new WelcomeBackPage(driver);
        welcomeBackPage.enterEmail("test@example.com");
        welcomeBackPage.enterPassword("Password123!");
        welcomeBackPage.tapRememberMe();
        SearchProductsPage searchProductsPage = welcomeBackPage.tapSignIn();
        assertTrue(searchProductsPage.isDisplayed());
        searchProductsPage.enterSearchProducts("test");
        YourCartPage yourCartPage = searchProductsPage.tapCart();
        assertTrue(yourCartPage.isDisplayed());
    }
}
