/**
 * Specs for the Running Shoes screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import welcomeBackPage from '../pageobjects/welcome-back.page.js';
import searchProductsPage from '../pageobjects/search-products.page.js';
import runningShoesPage from '../pageobjects/running-shoes.page.js';

describe('Running Shoes screen', () => {
    it('The running shoes screen shows its expected controls', async () => {
        await welcomeBackPage.tapSignIn();
        await searchProductsPage.tapRunningShoes();
        expect(await runningShoesPage.hasRunningShoes()).toBe(true);
        expect(await runningShoesPage.isDisplayed()).toBe(true);
    });
});
