/**
 * Specs for the Search products screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import welcomeBackPage from '../pageobjects/welcome-back.page.js';
import searchProductsPage from '../pageobjects/search-products.page.js';

describe('Search products screen', () => {
    it('The search products screen shows its expected controls', async () => {
        await welcomeBackPage.tapSignIn();
        expect(await searchProductsPage.isDisplayed()).toBe(true);
        expect(await searchProductsPage.hasRunningShoes()).toBe(true);
        expect(await searchProductsPage.hasBackpack()).toBe(true);
        expect(await searchProductsPage.hasCart()).toBe(true);
    });
});
