/**
 * Specs for the Welcome back screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import welcomeBackPage from '../pageobjects/welcome-back.page.js';

describe('Welcome back screen', () => {
    it('The welcome back screen shows its expected controls', async () => {
        expect(await welcomeBackPage.isDisplayed()).toBe(true);
        expect(await welcomeBackPage.hasEmail()).toBe(true);
        expect(await welcomeBackPage.hasPassword()).toBe(true);
        expect(await welcomeBackPage.hasRememberMe()).toBe(true);
        expect(await welcomeBackPage.hasSignIn()).toBe(true);
        expect(await welcomeBackPage.hasForgotPassword()).toBe(true);
    });

    it('Submitting the welcome back form with invalid data is rejected', async () => {
        await welcomeBackPage.enterEmail('not-an-email');
        await welcomeBackPage.enterPassword('1');
        await welcomeBackPage.tapSignIn();
        expect(await welcomeBackPage.isDisplayed()).toBe(true);
    });

    it('Submitting the welcome back form with empty fields is rejected', async () => {
        await welcomeBackPage.enterEmail('');
        await welcomeBackPage.enterPassword('');
        await welcomeBackPage.tapSignIn();
        expect(await welcomeBackPage.isDisplayed()).toBe(true);
    });

    it('The welcome back form survives too-long input', async () => {
        await welcomeBackPage.enterEmail('x'.repeat(300));
        await welcomeBackPage.enterPassword('x'.repeat(300));
        await welcomeBackPage.tapSignIn();
        expect(await welcomeBackPage.isAppRunning()).toBe(true);
    });

    it('The welcome back form survives special characters', async () => {
        await welcomeBackPage.enterEmail('!@#$%^&*()_+-=[]{};:,.?/~`\'');
        await welcomeBackPage.enterPassword('!@#$%^&*()_+-=[]{};:,.?/~`\'');
        await welcomeBackPage.tapSignIn();
        expect(await welcomeBackPage.isAppRunning()).toBe(true);
    });
});
