/**
 * Specs for the Your cart screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import welcomeBackPage from '../pageobjects/welcome-back.page.js';
import searchProductsPage from '../pageobjects/search-products.page.js';
import runningShoesPage from '../pageobjects/running-shoes.page.js';
import yourCartPage from '../pageobjects/your-cart.page.js';

describe('Your cart screen', () => {
    it('The your cart screen shows its expected controls', async () => {
        await welcomeBackPage.tapSignIn();
        await searchProductsPage.tapCart();
        expect(await yourCartPage.isDisplayed()).toBe(true);
        expect(await yourCartPage.hasPlaceOrder()).toBe(true);
    });

    it('The journey from Welcome back through Search products, Running Shoes to Your cart', async () => {
        await welcomeBackPage.enterEmail('test@example.com');
        await welcomeBackPage.enterPassword('Password123!');
        await welcomeBackPage.tapRememberMe();
        await welcomeBackPage.tapSignIn();
        expect(await searchProductsPage.isDisplayed()).toBe(true);
        await searchProductsPage.enterSearchProducts('test');
        await searchProductsPage.tapRunningShoes();
        expect(await runningShoesPage.isDisplayed()).toBe(true);
        await runningShoesPage.tapAddToCart();
        expect(await yourCartPage.isDisplayed()).toBe(true);
    });

    it('The journey from Welcome back through Search products to Your cart', async () => {
        await welcomeBackPage.enterEmail('test@example.com');
        await welcomeBackPage.enterPassword('Password123!');
        await welcomeBackPage.tapRememberMe();
        await welcomeBackPage.tapSignIn();
        expect(await searchProductsPage.isDisplayed()).toBe(true);
        await searchProductsPage.enterSearchProducts('test');
        await searchProductsPage.tapCart();
        expect(await yourCartPage.isDisplayed()).toBe(true);
    });
});
