package mobiscout.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.HasOnScreenKeyboard;
import io.appium.java_client.HidesKeyboard;
import io.appium.java_client.InteractsWithApps;
import io.appium.java_client.appmanagement.ApplicationState;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * Shared behaviour for every page object, written once.
 *
 * <p>Locating is ranked and self-healing (primary locator first, then fallbacks), waits on a
 * condition instead of sleeping (returns the moment the element is there) and scrolls to reach
 * a below-the-fold control. Acting settles the screen afterwards — a loading spinner gone, the
 * soft keyboard dismissed — so the next step never races a transition.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public abstract class BasePage {

    protected static final Duration TIMEOUT = Duration.ofSeconds(10);
    protected static final Duration POLL = Duration.ofMillis(250);
    protected static final Duration SETTLE_TIMEOUT = Duration.ofSeconds(5);
    private static final int SCROLL_TRIES = 4;
    private static final By BUSY = AppiumBy.xpath("//android.widget.ProgressBar");
    private static final String APP = "com.example.shop";

    protected final AppiumDriver driver;

    protected BasePage(AppiumDriver driver) {
        this.driver = driver;
    }

    /** The screen's title, for failure messages. */
    protected abstract String screen();

    /** The element distinctive to this screen, or {@code null} when none is. */
    protected abstract String identity();

    /** Ranked locators (primary first, then self-healing fallbacks) for an element. */
    protected abstract List<By> locators(String name);

    /** Whether this screen is the one on display, proven by an element only it has. */
    public boolean isDisplayed() {
        String id = identity();
        if (id == null) {
            throw new UnsupportedOperationException(
                    getClass().getSimpleName() + " has no element distinctive enough to identify it");
        }
        return isVisible(id);
    }

    /** Whether the app under test is still up in the foreground — it did not crash. */
    public boolean isAppRunning() {
        return ((InteractsWithApps) driver).queryAppState(APP) == ApplicationState.RUNNING_IN_FOREGROUND;
    }

    private WebElement locate(String name) {
        for (By by : locators(name)) {
            try {
                return driver.findElement(by);
            } catch (NoSuchElementException ignored) {
                // try the next, more fragile locator
            }
        }
        return null;
    }

    /** The element, waiting for it to appear and scrolling to reach it if needed. */
    protected WebElement find(String name) {
        try {
            return new WebDriverWait(driver, TIMEOUT, POLL).until(d -> locate(name));
        } catch (TimeoutException ignored) {
            // not on screen yet — it may be below the fold
        }
        for (int i = 0; i < SCROLL_TRIES; i++) {
            scrollDown();
            WebElement found = locate(name);
            if (found != null) {
                return found;
            }
        }
        throw new NoSuchElementException(
                "'" + name + "' not found on the " + screen() + " screen within " + TIMEOUT.getSeconds() + "s");
    }

    protected boolean isVisible(String name) {
        try {
            return find(name).isDisplayed();
        } catch (NoSuchElementException e) {
            return false;
        }
    }

    /** Whether the element is absent — returns the moment it is, not after the full timeout. */
    protected boolean isGone(String name) {
        try {
            return new WebDriverWait(driver, TIMEOUT, POLL).until(d -> locate(name) == null);
        } catch (TimeoutException e) {
            return false;
        }
    }

    protected String textOf(String name) {
        return find(name).getText();
    }

    protected boolean isEnabled(String name) {
        return find(name).isEnabled();
    }

    /** Press the system Back. */
    public void goBack() {
        driver.navigate().back();
        settle();
    }

    protected void tap(String name) {
        find(name).click();
        settle();
    }

    protected void type(String name, String value) {
        WebElement field = find(name);
        field.clear(); // replace, don't append to whatever the field held
        field.sendKeys(value);
        settle();
    }

    private void settle() {
        try {
            new WebDriverWait(driver, SETTLE_TIMEOUT, POLL).until(d -> d.findElements(BUSY).isEmpty());
        } catch (TimeoutException ignored) {
            // a stuck spinner is tolerated, not failed
        }
        try {
            if (driver instanceof HasOnScreenKeyboard && ((HasOnScreenKeyboard) driver).isKeyboardShown()) {
                ((HidesKeyboard) driver).hideKeyboard();
            }
        } catch (RuntimeException ignored) {
            // no keyboard to dismiss
        }
    }

    private void scrollDown() {
        Dimension size = driver.manage().window().getSize();
        driver.executeScript(
                "mobile: scrollGesture",
                Map.of(
                        "left", (int) (size.getWidth() * 0.1),
                        "top", (int) (size.getHeight() * 0.2),
                        "width", (int) (size.getWidth() * 0.8),
                        "height", (int) (size.getHeight() * 0.6),
                        "direction", "down",
                        "percent", 0.8));
    }
}
