package mobiscout.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import java.util.List;
import java.util.Map;
import org.openqa.selenium.By;

/**
 * The Running Shoes screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class RunningShoesPage extends BasePage {

    private static final Map<String, List<By>> LOCATORS = Map.ofEntries(
            Map.entry("running_shoes", List.of(AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"))),
            Map.entry("e_89_00", List.of(AppiumBy.androidUIAutomator("new UiSelector().text(\"$89.00\")"))),
            Map.entry("add_to_cart", List.of(AppiumBy.id("com.example.shop:id/add"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to cart\")")))
    );

    public RunningShoesPage(AppiumDriver driver) {
        super(driver);
    }

    @Override
    protected String screen() {
        return "Running Shoes";
    }

    @Override
    protected String identity() {
        return "add_to_cart";
    }

    @Override
    protected List<By> locators(String name) {
        return LOCATORS.get(name);
    }

    /** Tap Add to cart — opens the Your cart screen. */
    public YourCartPage tapAddToCart() {
        tap("add_to_cart");
        return new YourCartPage(driver);
    }

    /** Whether Running Shoes is shown. */
    public boolean hasRunningShoes() {
        return isVisible("running_shoes");
    }
}
