package mobiscout.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import java.util.List;
import java.util.Map;
import org.openqa.selenium.By;

/**
 * The Search products screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class SearchProductsPage extends BasePage {

    private static final Map<String, List<By>> LOCATORS = Map.ofEntries(
            Map.entry("search_products", List.of(AppiumBy.accessibilityId("Search products"), AppiumBy.id("com.example.shop:id/search"))),
            Map.entry("running_shoes", List.of(AppiumBy.id("com.example.shop:id/p_shoes"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Running Shoes\")"))),
            Map.entry("backpack", List.of(AppiumBy.id("com.example.shop:id/p_bag"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Backpack\")"))),
            Map.entry("cart", List.of(AppiumBy.accessibilityId("Cart"), AppiumBy.id("com.example.shop:id/cart")))
    );

    public SearchProductsPage(AppiumDriver driver) {
        super(driver);
    }

    @Override
    protected String screen() {
        return "Search products";
    }

    @Override
    protected String identity() {
        return "search_products";
    }

    @Override
    protected List<By> locators(String name) {
        return LOCATORS.get(name);
    }

    /** Type {@code value} into Search products. */
    public SearchProductsPage enterSearchProducts(String value) {
        type("search_products", value);
        return this;
    }

    /** Tap Running Shoes — opens the Running Shoes screen. */
    public RunningShoesPage tapRunningShoes() {
        tap("running_shoes");
        return new RunningShoesPage(driver);
    }

    /** Tap Backpack. */
    public SearchProductsPage tapBackpack() {
        tap("backpack");
        return this;
    }

    /** Tap Cart — opens the Your cart screen. */
    public YourCartPage tapCart() {
        tap("cart");
        return new YourCartPage(driver);
    }

    /** Whether Backpack is shown. */
    public boolean hasBackpack() {
        return isVisible("backpack");
    }

    /** Whether Cart is shown. */
    public boolean hasCart() {
        return isVisible("cart");
    }

    /** Whether Running Shoes is shown. */
    public boolean hasRunningShoes() {
        return isVisible("running_shoes");
    }
}
