package mobiscout.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import java.util.List;
import java.util.Map;
import org.openqa.selenium.By;

/**
 * The Welcome back screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class WelcomeBackPage extends BasePage {

    private static final Map<String, List<By>> LOCATORS = Map.ofEntries(
            Map.entry("welcome_back", List.of(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome back\")"))),
            Map.entry("email", List.of(AppiumBy.accessibilityId("Email"), AppiumBy.id("com.example.shop:id/email"))),
            Map.entry("password", List.of(AppiumBy.accessibilityId("Password"), AppiumBy.id("com.example.shop:id/password"))),
            Map.entry("remember_me", List.of(AppiumBy.id("com.example.shop:id/remember"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Remember me\")"))),
            Map.entry("sign_in", List.of(AppiumBy.id("com.example.shop:id/signin"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Sign in\")"))),
            Map.entry("forgot_password", List.of(AppiumBy.id("com.example.shop:id/forgot"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Forgot password?\")")))
    );

    public WelcomeBackPage(AppiumDriver driver) {
        super(driver);
    }

    @Override
    protected String screen() {
        return "Welcome back";
    }

    @Override
    protected String identity() {
        return "welcome_back";
    }

    @Override
    protected List<By> locators(String name) {
        return LOCATORS.get(name);
    }

    /** Type {@code value} into Email. */
    public WelcomeBackPage enterEmail(String value) {
        type("email", value);
        return this;
    }

    /** Type {@code value} into Password. */
    public WelcomeBackPage enterPassword(String value) {
        type("password", value);
        return this;
    }

    /** Tap Remember me. */
    public WelcomeBackPage tapRememberMe() {
        tap("remember_me");
        return this;
    }

    /** Tap Sign in — opens the Search products screen. */
    public SearchProductsPage tapSignIn() {
        tap("sign_in");
        return new SearchProductsPage(driver);
    }

    /** Tap Forgot password?. */
    public WelcomeBackPage tapForgotPassword() {
        tap("forgot_password");
        return this;
    }

    /** Whether Email is shown. */
    public boolean hasEmail() {
        return isVisible("email");
    }

    /** Whether Forgot password? is shown. */
    public boolean hasForgotPassword() {
        return isVisible("forgot_password");
    }

    /** Whether Password is shown. */
    public boolean hasPassword() {
        return isVisible("password");
    }

    /** Whether Remember me is shown. */
    public boolean hasRememberMe() {
        return isVisible("remember_me");
    }

    /** Whether Sign in is shown. */
    public boolean hasSignIn() {
        return isVisible("sign_in");
    }
}
