package mobiscout.pages;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import java.util.List;
import java.util.Map;
import org.openqa.selenium.By;

/**
 * The Your cart screen.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public class YourCartPage extends BasePage {

    private static final Map<String, List<By>> LOCATORS = Map.ofEntries(
            Map.entry("your_cart", List.of(AppiumBy.androidUIAutomator("new UiSelector().text(\"Your cart\")"))),
            Map.entry("place_order", List.of(AppiumBy.id("com.example.shop:id/order"), AppiumBy.androidUIAutomator("new UiSelector().text(\"Place order\")")))
    );

    public YourCartPage(AppiumDriver driver) {
        super(driver);
    }

    @Override
    protected String screen() {
        return "Your cart";
    }

    @Override
    protected String identity() {
        return "your_cart";
    }

    @Override
    protected List<By> locators(String name) {
        return LOCATORS.get(name);
    }

    /** Tap Place order. */
    public YourCartPage tapPlaceOrder() {
        tap("place_order");
        return this;
    }

    /** Whether Place order is shown. */
    public boolean hasPlaceOrder() {
        return isVisible("place_order");
    }
}
