/*
 * LoginFlow — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package generated

import io.appium.java_client.AppiumBy
import io.appium.java_client.android.AndroidDriver
import io.appium.java_client.android.options.UiAutomator2Options
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.openqa.selenium.By
import org.openqa.selenium.NoSuchElementException
import org.openqa.selenium.TimeoutException
import org.openqa.selenium.WebElement
import org.openqa.selenium.support.ui.WebDriverWait
import java.net.URL
import java.time.Duration

class LoginFlow {

    private lateinit var driver: AndroidDriver

    // Condition-based wait budget — poll for elements instead of a fixed sleep or
    // a global implicit wait, so tests stay in sync with async UI.
    private val TIMEOUT: Duration = Duration.ofSeconds(10)

    // Run anywhere without regenerating: point at a different Appium/cloud-grid
    // hub with MOBISCOUT_APPIUM_SERVER.
    private val SERVER: String = System.getenv("MOBISCOUT_APPIUM_SERVER") ?: "http://localhost:4723"

    @BeforeEach
    fun setUp() {
        val options = UiAutomator2Options()
        options.setPlatformName("Android")
        options.setAppPackage("com.example.app")
        options.setAppActivity(".MainActivity")
        driver = AndroidDriver(URL(SERVER), options)
    }

    @AfterEach
    fun tearDown() {
        driver.quit()
    }

    /** Locate an element, falling back through ranked alternatives (self-healing). */
    /**
     * Locate an element, waiting for it to appear and self-healing through ranked
     * alternatives — a condition-based wait, not an instant lookup that flakes.
     */
    private fun find(primary: By, fallbacks: Array<By>): WebElement {
        val locators = listOf(primary, *fallbacks)
        try {
            return WebDriverWait(driver, TIMEOUT).until { d ->
                var found: WebElement? = null
                for (by in locators) {
                    try {
                        found = d.findElement(by)
                        break
                    } catch (ignored: NoSuchElementException) {
                    }
                }
                found
            }!!
        } catch (e: TimeoutException) {
            throw NoSuchElementException("No locator matched within ${TIMEOUT.seconds}s (primary + ${fallbacks.size} fallbacks)")
        }
    }

    // A generic loading indicator (no app-specific knowledge) — used by settle().
    private val BUSY_XPATH: String = "//android.widget.ProgressBar"
    /**
     * Middle beat of act -> wait-busy-clears -> assert: after an action that triggers
     * a transition, wait for a loading/activity indicator to disappear so the next step
     * doesn't act on a mid-transition screen. No-op when nothing is spinning.
     */
    private fun settle() {
        try {
            WebDriverWait(driver, TIMEOUT).until { d -> d.findElements(By.xpath(BUSY_XPATH)).isEmpty() }
        } catch (ignored: TimeoutException) {
        }
    }

    @Test
    fun login() {
        // Open app
        driver.activateApp("com.example.app")
        // Enter email
        find(AppiumBy.id("user_field"), arrayOf(AppiumBy.xpath("//input[1]"))).sendKeys("alice@example.com")
        settle()
        // Tap login
        find(AppiumBy.accessibilityId("login_btn"), arrayOf()).click()
        settle()
        // Wait for home
        // Condition-based: wait for the screen to render rather than a global implicit wait.
        WebDriverWait(driver, Duration.ofSeconds(3)).until { d -> d.findElements(By.xpath("//*")).isNotEmpty() }
        // Swipe up to reveal content
        run {
            val swipeSize = driver.manage().window().size
            driver.executeScript("mobile: swipeGesture", mapOf<String, Any>("left" to (swipeSize.width * 0.1).toInt(), "top" to (swipeSize.height * 0.1).toInt(), "width" to (swipeSize.width * 0.8).toInt(), "height" to (swipeSize.height * 0.8).toInt(), "direction" to "up", "percent" to 0.75))
        }
        settle()
        // Dismiss a dialog
        driver.navigate().back()
        settle()
        // Welcome message shown
        Assertions.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")"), arrayOf()).isDisplayed)
    }

}
