package mobiscout.support;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import java.net.MalformedURLException;
import java.net.URI;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;

/**
 * Driver lifecycle for every test class.
 *
 * <p>Fast by design: ONE Appium session serves the whole suite (opening a session costs 5-10 s)
 * and each test starts from a cold restart of the app (~1-2 s) — every test still begins clean,
 * without paying for a new session each time. Run against another Appium server or a cloud grid
 * with {@code MOBISCOUT_APPIUM_SERVER}.
 *
 * <p>Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
public abstract class BaseTest {

    protected static final String APP = "com.example.shop";
    private static final String SERVER =
            System.getenv().getOrDefault("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723");

    protected static AndroidDriver driver;

    @BeforeSuite(alwaysRun = true)
    public void startSession() throws MalformedURLException {
        UiAutomator2Options options = new UiAutomator2Options()
                .setAppPackage(APP)
                .setAppActivity(".MainActivity")
                .setNoReset(true); // keep app data; each test restarts the app itself
        options.setCapability("appium:disableWindowAnimation", true); // animations only cost time
        driver = new AndroidDriver(URI.create(SERVER).toURL(), options);
        // Don't wait for the UI to go idle after every command: a live app rarely does, and
        // UiAutomator2 would otherwise stall up to 10 s per command.
        driver.setSetting("waitForIdleTimeout", 100);
    }

    @BeforeMethod(alwaysRun = true)
    public void restartApp() throws MalformedURLException {
        if (!alive()) {
            // Appium or the driver crashed: this test gets a new session instead of the whole
            // rest of the run failing on a dead one.
            endSession();
            startSession();
        }
        try {
            driver.terminateApp(APP);
        } catch (RuntimeException ignored) {
            // the app was not running
        }
        driver.activateApp(APP);
    }

    @AfterSuite(alwaysRun = true)
    public void endSession() {
        if (driver != null) {
            try {
                driver.quit();
            } catch (RuntimeException ignored) {
                // already gone
            }
            driver = null;
        }
    }

    /** Whether the session still answers — one cheap call. */
    private static boolean alive() {
        try {
            driver.queryAppState(APP);
            return true;
        } catch (RuntimeException e) {
            return false;
        }
    }
}
