// Auto-generated by Mobiscout. Regenerate rather than hand-edit.

import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("jvm") version "2.2.21"
}

repositories { mavenCentral() }

dependencies {
    testImplementation("io.appium:java-client:10.1.1")
    // Pin every Selenium artifact to the version this kit was compiled against: java-client
    // declares Selenium as an open range, and the newest Selenium has removed classes older
    // clients were built on.
    testImplementation(platform("org.seleniumhq.selenium:selenium-bom:4.49.0"))
    testImplementation(platform("org.junit:junit-bom:5.11.4"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java { targetCompatibility = JavaVersion.VERSION_17 }

kotlin { compilerOptions { jvmTarget.set(JvmTarget.JVM_17) } }

tasks.test {
    useJUnitPlatform()
    testLogging { events("passed", "skipped", "failed") }
}
