"""
RunningShoesPage — the Running Shoes screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from appium.webdriver.common.appiumby import AppiumBy

from pages.base_page import BasePage


class RunningShoesPage(BasePage):
    """The Running Shoes screen."""

    SCREEN = "Running Shoes"
    IDENTITY = "add_to_cart"
    LOCATORS = {
        "running_shoes": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
        "e_89_00": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"$89.00\")")],
        "add_to_cart": [(AppiumBy.ID, "com.example.shop:id/add"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")],
    }

    def tap_add_to_cart(self):
        """Tap Add to cart — opens the Your cart screen."""
        self._tap("add_to_cart")
        from pages.your_cart_page import YourCartPage

        return YourCartPage(self.driver)

    def has_running_shoes(self):
        """Whether Running Shoes is shown."""
        return self._is_visible("running_shoes")
