"""
SearchProductsPage — the Search products screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from appium.webdriver.common.appiumby import AppiumBy

from pages.base_page import BasePage


class SearchProductsPage(BasePage):
    """The Search products screen."""

    SCREEN = "Search products"
    IDENTITY = "search_products"
    LOCATORS = {
        "search_products": [(AppiumBy.ACCESSIBILITY_ID, "Search products"), (AppiumBy.ID, "com.example.shop:id/search")],
        "running_shoes": [(AppiumBy.ID, "com.example.shop:id/p_shoes"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
        "backpack": [(AppiumBy.ID, "com.example.shop:id/p_bag"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")],
        "cart": [(AppiumBy.ACCESSIBILITY_ID, "Cart"), (AppiumBy.ID, "com.example.shop:id/cart")],
    }

    def enter_search_products(self, value):
        """Type ``value`` into Search products."""
        self._type("search_products", value)
        return self

    def tap_running_shoes(self):
        """Tap Running Shoes — opens the Running Shoes screen."""
        self._tap("running_shoes")
        from pages.running_shoes_page import RunningShoesPage

        return RunningShoesPage(self.driver)

    def tap_backpack(self):
        """Tap Backpack."""
        self._tap("backpack")
        return self

    def tap_cart(self):
        """Tap Cart — opens the Your cart screen."""
        self._tap("cart")
        from pages.your_cart_page import YourCartPage

        return YourCartPage(self.driver)

    def has_backpack(self):
        """Whether Backpack is shown."""
        return self._is_visible("backpack")

    def has_cart(self):
        """Whether Cart is shown."""
        return self._is_visible("cart")

    def has_running_shoes(self):
        """Whether Running Shoes is shown."""
        return self._is_visible("running_shoes")
