"""
WelcomeBackPage — the Welcome back screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from appium.webdriver.common.appiumby import AppiumBy

from pages.base_page import BasePage


class WelcomeBackPage(BasePage):
    """The Welcome back screen."""

    SCREEN = "Welcome back"
    IDENTITY = "welcome_back"
    LOCATORS = {
        "welcome_back": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome back\")")],
        "email": [(AppiumBy.ACCESSIBILITY_ID, "Email"), (AppiumBy.ID, "com.example.shop:id/email")],
        "password": [(AppiumBy.ACCESSIBILITY_ID, "Password"), (AppiumBy.ID, "com.example.shop:id/password")],
        "remember_me": [(AppiumBy.ID, "com.example.shop:id/remember"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")],
        "sign_in": [(AppiumBy.ID, "com.example.shop:id/signin"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")],
        "forgot_password": [(AppiumBy.ID, "com.example.shop:id/forgot"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Forgot password?\")")],
    }

    def enter_email(self, value):
        """Type ``value`` into Email."""
        self._type("email", value)
        return self

    def enter_password(self, value):
        """Type ``value`` into Password."""
        self._type("password", value)
        return self

    def tap_remember_me(self):
        """Tap Remember me."""
        self._tap("remember_me")
        return self

    def tap_sign_in(self):
        """Tap Sign in — opens the Search products screen."""
        self._tap("sign_in")
        from pages.search_products_page import SearchProductsPage

        return SearchProductsPage(self.driver)

    def tap_forgot_password(self):
        """Tap Forgot password?."""
        self._tap("forgot_password")
        return self

    def has_email(self):
        """Whether Email is shown."""
        return self._is_visible("email")

    def has_forgot_password(self):
        """Whether Forgot password? is shown."""
        return self._is_visible("forgot_password")

    def has_password(self):
        """Whether Password is shown."""
        return self._is_visible("password")

    def has_remember_me(self):
        """Whether Remember me is shown."""
        return self._is_visible("remember_me")

    def has_sign_in(self):
        """Whether Sign in is shown."""
        return self._is_visible("sign_in")
