"""
Tests for the Welcome back screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pages.welcome_back_page import WelcomeBackPage


def test_welcome_back_screen_shows_expected_controls(driver):
    """The welcome back screen shows its expected controls."""
    welcome_back_page = WelcomeBackPage(driver)
    assert welcome_back_page.is_displayed()
    assert welcome_back_page.has_email()
    assert welcome_back_page.has_password()
    assert welcome_back_page.has_remember_me()
    assert welcome_back_page.has_sign_in()
    assert welcome_back_page.has_forgot_password()


def test_rejects_invalid_input_on_welcome_back(driver):
    """Submitting the welcome back form with invalid data is rejected."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("not-an-email")
    welcome_back_page.enter_password("1")
    welcome_back_page.tap_sign_in()
    assert welcome_back_page.is_displayed()


def test_rejects_empty_input_on_welcome_back(driver):
    """Submitting the welcome back form with empty fields is rejected."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("")
    welcome_back_page.enter_password("")
    welcome_back_page.tap_sign_in()
    assert welcome_back_page.is_displayed()


def test_survives_too_long_on_welcome_back(driver):
    """The welcome back form survives too-long input."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("x" * 300)
    welcome_back_page.enter_password("x" * 300)
    welcome_back_page.tap_sign_in()
    assert welcome_back_page.is_app_running()


def test_survives_special_characters_on_welcome_back(driver):
    """The welcome back form survives special characters."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("!@#$%^&*()_+-=[]{};:,.?/~`'")
    welcome_back_page.enter_password("!@#$%^&*()_+-=[]{};:,.?/~`'")
    welcome_back_page.tap_sign_in()
    assert welcome_back_page.is_app_running()
