"""
Tests for the Search products screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pages.welcome_back_page import WelcomeBackPage


def test_search_products_screen_shows_expected_controls(driver):
    """The search products screen shows its expected controls."""
    welcome_back_page = WelcomeBackPage(driver)
    search_products_page = welcome_back_page.tap_sign_in()
    assert search_products_page.is_displayed()
    assert search_products_page.has_running_shoes()
    assert search_products_page.has_backpack()
    assert search_products_page.has_cart()
