"""
Tests for the Running Shoes screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pages.welcome_back_page import WelcomeBackPage


def test_running_shoes_screen_shows_expected_controls(driver):
    """The running shoes screen shows its expected controls."""
    welcome_back_page = WelcomeBackPage(driver)
    search_products_page = welcome_back_page.tap_sign_in()
    running_shoes_page = search_products_page.tap_running_shoes()
    assert running_shoes_page.has_running_shoes()
    assert running_shoes_page.is_displayed()
