"""
Tests for the Your cart screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pages.welcome_back_page import WelcomeBackPage


def test_your_cart_screen_shows_expected_controls(driver):
    """The your cart screen shows its expected controls."""
    welcome_back_page = WelcomeBackPage(driver)
    search_products_page = welcome_back_page.tap_sign_in()
    your_cart_page = search_products_page.tap_cart()
    assert your_cart_page.is_displayed()
    assert your_cart_page.has_place_order()


def test_journey_from_sign_in_to_add_to_cart(driver):
    """The journey from Welcome back through Search products, Running Shoes to Your cart."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("test@example.com")
    welcome_back_page.enter_password("Password123!")
    welcome_back_page.tap_remember_me()
    search_products_page = welcome_back_page.tap_sign_in()
    assert search_products_page.is_displayed()
    search_products_page.enter_search_products("test")
    running_shoes_page = search_products_page.tap_running_shoes()
    assert running_shoes_page.is_displayed()
    your_cart_page = running_shoes_page.tap_add_to_cart()
    assert your_cart_page.is_displayed()


def test_journey_from_sign_in_to_cart(driver):
    """The journey from Welcome back through Search products to Your cart."""
    welcome_back_page = WelcomeBackPage(driver)
    welcome_back_page.enter_email("test@example.com")
    welcome_back_page.enter_password("Password123!")
    welcome_back_page.tap_remember_me()
    search_products_page = welcome_back_page.tap_sign_in()
    assert search_products_page.is_displayed()
    search_products_page.enter_search_products("test")
    your_cart_page = search_products_page.tap_cart()
    assert your_cart_page.is_displayed()
