"""
Runs every scenario in features/ — the steps are registered in conftest.py.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from pytest_bdd import scenarios

scenarios("../features")
