/*
 * CrawlFlow — auto-generated by Mobile Test Recorder.
 * Auto-generated from an autonomous crawl (state + navigation).
 * App under test: com.example.shop
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 *
 * WebdriverIO mobile spec (Mocha). Requires an Appium session configured in
 * wdio.conf.js with platformName 'Android', automationName 'UiAutomator2',
 * 'appium:appPackage' = com.example.shop.
 */

const APP_PACKAGE = 'com.example.shop';

// Locate an element, falling back through ranked selectors (self-healing).
async function find(selectors) {
    for (const selector of selectors) {
        const el = await driver.$(selector);
        if (await el.isExisting()) {
            return el;
        }
    }
    throw new Error(`No selector matched: ${selectors.join(', ')}`);
}

describe('CrawlFlow', () => {
    it('screen_1_state', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Welcome back is visible
        await expect(await find(['android=new UiSelector().text("Welcome back")'])).toBeDisplayed();
        // Email is visible
        await expect(await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).toBeDisplayed();
        // Email is enabled
        await expect(await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).toBeEnabled();
        // Password is visible
        await expect(await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).toBeDisplayed();
        // Password is enabled
        await expect(await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).toBeEnabled();
        // Remember me is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).toBeDisplayed();
        // Remember me is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).toBeEnabled();
        // Sign in is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).toBeDisplayed();
        // Sign in is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).toBeEnabled();
        // Forgot password? is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'])).toBeDisplayed();
        // Forgot password? is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('screen_2_state', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Search products is visible
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Search products is enabled
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeEnabled();
        // Running Shoes is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // Running Shoes is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).toBeEnabled();
        // Backpack is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'])).toBeDisplayed();
        // Backpack is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'])).toBeEnabled();
        // Cart is visible
        await expect(await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).toBeDisplayed();
        // Cart is enabled
        await expect(await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('screen_3_state', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Running Shoes is visible
        await expect(await find(['android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // $89.00 is visible
        await expect(await find(['android=new UiSelector().text("$89.00")'])).toBeDisplayed();
        // Add to cart is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).toBeDisplayed();
        // Add to cart is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('screen_4_state', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Your cart is visible
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
        // Place order is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'])).toBeDisplayed();
        // Place order is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('navigate_1', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        // Destination screen is shown
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
    });
});

describe('CrawlFlow', () => {
    it('path_1_2_3_4', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Type into Email
        await (await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).setValue('test@example.com');
        // Type into Password
        await (await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).setValue('Password123!');
        // Toggle Remember me
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).click();
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        // Reached screen 2
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Type into Search products
        await (await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).setValue('test');
        // Tap Running Shoes
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).click();
        // Reached screen 3
        await expect(await find(['android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // Tap Add to cart
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).click();
        // Reached screen 4
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
    });
});

describe('CrawlFlow', () => {
    it('path_1_2_4', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Type into Email
        await (await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).setValue('test@example.com');
        // Type into Password
        await (await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).setValue('Password123!');
        // Toggle Remember me
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).click();
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        // Reached screen 2
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Type into Search products
        await (await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).setValue('test');
        // Tap Cart
        await (await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).click();
        // Reached screen 4
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
    });
});

