/**
 * WebdriverIO config — auto-generated by Mobiscout. Regenerate rather than hand-edit.
 *
 * Fast by design: each worker keeps ONE Appium session for its specs (opening a session costs
 * 5-10 s) and every test starts from a cold restart of the app (~1-2 s), so each test still
 * begins clean. The appium service starts the Appium server for you.
 */

const APP = 'com.example.shop';

/**
 * Reopen the session if it no longer answers (Appium or the driver crashed): one crash costs
 * one test, not every test after it.
 */
async function ensureAlive() {
    try {
        await driver.queryAppState(APP);
    } catch {
        await driver.reloadSession();
    }
}

export const config = {
    runner: 'local',
    port: 4723,
    specs: ['./test/specs/**/*.e2e.js'],
    maxInstances: 1,
    capabilities: [
        {
            platformName: 'Android',
            'appium:automationName': 'UiAutomator2',
            'appium:appPackage': APP,
            'appium:appActivity': '.MainActivity',
            'appium:disableWindowAnimation': true, // animations only cost time
            // Don't wait for the UI to go idle after every command: a live app rarely does, and
            // UiAutomator2 would otherwise stall up to 10 s per command.
            'appium:settings[waitForIdleTimeout]': 100,
            'appium:noReset': true, // keep app data; each test restarts the app itself (below)
        },
    ],
    services: ['appium'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: { ui: 'bdd', timeout: 90000 },

    /** A fresh app for every test on the worker's shared session. */
    beforeTest: async () => {
        await ensureAlive();
        try {
            await driver.terminateApp(APP);
        } catch {
            // the app was not running
        }
        await driver.activateApp(APP);
    },
};
