"""
YourCartPage — the Your cart screen.

Auto-generated by Mobiscout. Regenerate rather than hand-edit.
"""

from appium.webdriver.common.appiumby import AppiumBy

from pages.base_page import BasePage


class YourCartPage(BasePage):
    """The Your cart screen."""

    SCREEN = "Your cart"
    IDENTITY = "your_cart"
    LOCATORS = {
        "your_cart": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")")],
        "place_order": [(AppiumBy.ID, "com.example.shop:id/order"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")],
    }

    def tap_place_order(self):
        """Tap Place order."""
        self._tap("place_order")
        return self

    def has_place_order(self):
        """Whether Place order is shown."""
        return self._is_visible("place_order")
