"""
RunningShoesPage — Page Object for the RunningShoes screen.
Auto-generated by Mobile Test Recorder. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


class RunningShoesPage:
    """Page object for the RunningShoes screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "running__shoes": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
        "e_89_00": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"$89.00\")")],
        "add_to_cart": [(AppiumBy.ID, "com.example.shop:id/add"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _find(self, name):
        """Locate an element by name, trying its ranked locators in order."""
        for by, value in self.LOCATORS[name]:
            try:
                return self.driver.find_element(by, value)
            except NoSuchElementException:
                continue
        raise NoSuchElementException(f"No locator matched for {name!r} on RunningShoes")

    def running__shoes(self):
        """Locate the running__shoes element."""
        return self._find("running__shoes")

    def e_89_00(self):
        """Locate the e_89_00 element."""
        return self._find("e_89_00")

    def add_to_cart(self):
        """Locate the add_to_cart element."""
        return self._find("add_to_cart")

