"""
Screen2Page — Page Object for the Screen2 screen.
Auto-generated by Mobiscout. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds) — poll for the element instead of a fixed
# sleep or a global implicit wait, so pages stay in sync with async UI.
TIMEOUT = 10
# How many times _find scrolls looking for an off-screen element before giving up.
SCROLL_TRIES = 4


class Screen2Page:
    """Page object for the Screen2 screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "search_products": [(AppiumBy.ACCESSIBILITY_ID, "Search products"), (AppiumBy.ID, "com.example.shop:id/search")],
        "running__shoes": [(AppiumBy.ID, "com.example.shop:id/p_shoes"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
        "backpack": [(AppiumBy.ID, "com.example.shop:id/p_bag"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")],
        "cart": [(AppiumBy.ACCESSIBILITY_ID, "Cart"), (AppiumBy.ID, "com.example.shop:id/cart")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _scroll_down(self):
        """One scroll-down gesture, best-effort across platforms (iOS `mobile: scroll`,
        Android `mobile: scrollGesture`) — used by _find to reach a below-the-fold element."""
        try:
            self.driver.execute_script("mobile: scroll", {"direction": "down"})
        except Exception:
            try:
                s = self.driver.get_window_size()
                self.driver.execute_script("mobile: scrollGesture", {
                    "left": int(s["width"] * 0.1), "top": int(s["height"] * 0.2),
                    "width": int(s["width"] * 0.8), "height": int(s["height"] * 0.6),
                    "direction": "down", "percent": 0.8,
                })
            except Exception:
                pass

    def _find(self, name):
        """Locate an element by name, waiting for it to appear and self-healing
        through its ranked locators — a condition-based wait, not an instant lookup
        that flakes on async screens. Scrolls to reach a below-the-fold element."""
        locators = self.LOCATORS[name]

        def _locate(driver):
            for by, value in locators:
                try:
                    return driver.find_element(by, value)
                except NoSuchElementException:
                    continue
            return False

        try:
            return WebDriverWait(self.driver, TIMEOUT, poll_frequency=0.3).until(_locate)
        except TimeoutException:
            pass
        for _ in range(SCROLL_TRIES):
            self._scroll_down()
            found = _locate(self.driver)
            if found:
                return found
        raise NoSuchElementException(f"No locator matched for {name!r} on Screen2 within {TIMEOUT}s")

    def search_products(self):
        """Locate the search_products element."""
        return self._find("search_products")

    def running__shoes(self):
        """Locate the running__shoes element."""
        return self._find("running__shoes")

    def backpack(self):
        """Locate the backpack element."""
        return self._find("backpack")

    def cart(self):
        """Locate the cart element."""
        return self._find("cart")

