"""
Screen2Page — Page Object for the Screen2 screen.
Auto-generated by Mobile Test Recorder. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


class Screen2Page:
    """Page object for the Screen2 screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "search_products": [(AppiumBy.ACCESSIBILITY_ID, "Search products"), (AppiumBy.ID, "com.example.shop:id/search")],
        "running__shoes": [(AppiumBy.ID, "com.example.shop:id/p_shoes"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
        "backpack": [(AppiumBy.ID, "com.example.shop:id/p_bag"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")],
        "cart": [(AppiumBy.ACCESSIBILITY_ID, "Cart"), (AppiumBy.ID, "com.example.shop:id/cart")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _find(self, name):
        """Locate an element by name, trying its ranked locators in order."""
        for by, value in self.LOCATORS[name]:
            try:
                return self.driver.find_element(by, value)
            except NoSuchElementException:
                continue
        raise NoSuchElementException(f"No locator matched for {name!r} on Screen2")

    def search_products(self):
        """Locate the search_products element."""
        return self._find("search_products")

    def running__shoes(self):
        """Locate the running__shoes element."""
        return self._find("running__shoes")

    def backpack(self):
        """Locate the backpack element."""
        return self._find("backpack")

    def cart(self):
        """Locate the cart element."""
        return self._find("cart")

