"""
WelcomeBackPage — Page Object for the WelcomeBack screen.
Auto-generated by Mobiscout. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds) — poll for the element instead of a fixed
# sleep or a global implicit wait, so pages stay in sync with async UI.
TIMEOUT = 10


class WelcomeBackPage:
    """Page object for the WelcomeBack screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "welcome_back": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome back\")")],
        "email": [(AppiumBy.ACCESSIBILITY_ID, "Email"), (AppiumBy.ID, "com.example.shop:id/email")],
        "password": [(AppiumBy.ACCESSIBILITY_ID, "Password"), (AppiumBy.ID, "com.example.shop:id/password")],
        "remember_me": [(AppiumBy.ID, "com.example.shop:id/remember"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")],
        "sign_in": [(AppiumBy.ID, "com.example.shop:id/signin"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")],
        "forgot_password": [(AppiumBy.ID, "com.example.shop:id/forgot"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Forgot password?\")")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _find(self, name):
        """Locate an element by name, waiting for it to appear and self-healing
        through its ranked locators — a condition-based wait, not an instant lookup
        that flakes on async screens."""
        locators = self.LOCATORS[name]

        def _locate(driver):
            for by, value in locators:
                try:
                    return driver.find_element(by, value)
                except NoSuchElementException:
                    continue
            return False

        try:
            return WebDriverWait(self.driver, TIMEOUT, poll_frequency=0.3).until(_locate)
        except TimeoutException:
            raise NoSuchElementException(f"No locator matched for {name!r} on WelcomeBack within {TIMEOUT}s")

    def welcome_back(self):
        """Locate the welcome_back element."""
        return self._find("welcome_back")

    def email(self):
        """Locate the email element."""
        return self._find("email")

    def password(self):
        """Locate the password element."""
        return self._find("password")

    def remember_me(self):
        """Locate the remember_me element."""
        return self._find("remember_me")

    def sign_in(self):
        """Locate the sign_in element."""
        return self._find("sign_in")

    def forgot_password(self):
        """Locate the forgot_password element."""
        return self._find("forgot_password")

