"""
YourCartPage — Page Object for the YourCart screen.
Auto-generated by Mobile Test Recorder. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


class YourCartPage:
    """Page object for the YourCart screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "your_cart": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")")],
        "place_order": [(AppiumBy.ID, "com.example.shop:id/order"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _find(self, name):
        """Locate an element by name, trying its ranked locators in order."""
        for by, value in self.LOCATORS[name]:
            try:
                return self.driver.find_element(by, value)
            except NoSuchElementException:
                continue
        raise NoSuchElementException(f"No locator matched for {name!r} on YourCart")

    def your_cart(self):
        """Locate the your_cart element."""
        return self._find("your_cart")

    def place_order(self):
        """Locate the place_order element."""
        return self._find("place_order")

