"""
YourCartPage — Page Object for the YourCart screen.
Auto-generated by Mobiscout. DO NOT EDIT BY HAND — regenerate instead.
"""

from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.support.ui import WebDriverWait

# Condition-based wait budget (seconds) — poll for the element instead of a fixed
# sleep or a global implicit wait, so pages stay in sync with async UI.
TIMEOUT = 10


class YourCartPage:
    """Page object for the YourCart screen."""

    # Ranked locators per element: primary first, then self-healing fallbacks.
    LOCATORS = {
        "your_cart": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")")],
        "place_order": [(AppiumBy.ID, "com.example.shop:id/order"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")],
    }

    def __init__(self, driver):
        self.driver = driver

    def _find(self, name):
        """Locate an element by name, waiting for it to appear and self-healing
        through its ranked locators — a condition-based wait, not an instant lookup
        that flakes on async screens."""
        locators = self.LOCATORS[name]

        def _locate(driver):
            for by, value in locators:
                try:
                    return driver.find_element(by, value)
                except NoSuchElementException:
                    continue
            return False

        try:
            return WebDriverWait(self.driver, TIMEOUT, poll_frequency=0.3).until(_locate)
        except TimeoutException:
            raise NoSuchElementException(f"No locator matched for {name!r} on YourCart within {TIMEOUT}s")

    def your_cart(self):
        """Locate the your_cart element."""
        return self._find("your_cart")

    def place_order(self):
        """Locate the place_order element."""
        return self._find("place_order")

