"""
API contract tests — auto-generated by Mobiscout from the app model.
Each test issues the request and checks the contract: the response status is one
the API documents (else that the server did not 5xx), and — when the response
shape is known — that a success body carries the documented fields.
Set API_BASE_URL to point at your backend.
DO NOT EDIT BY HAND — regenerate instead.
"""

import os

import pytest
import requests

BASE_URL = os.environ.get("API_BASE_URL", "https://api.example-shop.com").rstrip("/")


@pytest.fixture()
def session():
    s = requests.Session()
    yield s
    s.close()


def test_login(session):
    """POST /auth/login"""
    response = session.post(BASE_URL + "/auth/login", json={'email': 'test', 'password': 'test'})
    # Contract check: endpoint is reachable and the server did not 5xx.
    assert response.status_code < 500, f"server error {response.status_code}: {response.text[:200]}"

def test_list_products(session):
    """GET /products"""
    response = session.get(BASE_URL + "/products")
    # Contract check: endpoint is reachable and the server did not 5xx.
    assert response.status_code < 500, f"server error {response.status_code}: {response.text[:200]}"

def test_add_to_cart(session):
    """POST /cart/items"""
    response = session.post(BASE_URL + "/cart/items", json={'product_id': 'test', 'qty': 'test'})
    # Contract check: endpoint is reachable and the server did not 5xx.
    assert response.status_code < 500, f"server error {response.status_code}: {response.text[:200]}"

