/**
 * RunningShoesPage — the Running Shoes screen.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */

import BasePage from './base.page.js';
import yourCartPage from './your-cart.page.js';

class RunningShoesPage extends BasePage {
    constructor() {
        super({
            screen: 'Running Shoes',
            identity: 'add_to_cart',
            locators: {
                'running_shoes': ['android=new UiSelector().text("Running Shoes")'],
                'e_89_00': ['android=new UiSelector().text("$89.00")'],
                'add_to_cart': ['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'],
            },
        });
    }

    /** Tap Add to cart — opens the Your cart screen. */
    async tapAddToCart() {
        await this._tap('add_to_cart');
        return yourCartPage;
    }

    /** Whether Running Shoes is shown. */
    async hasRunningShoes() {
        return this._isVisible('running_shoes');
    }
}

export default new RunningShoesPage();
