/*
 * CrawlFlow — auto-generated by Mobiscout.
 * Auto-generated from an autonomous crawl (state + navigation).
 * App under test: com.example.shop
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 *
 * WebdriverIO mobile spec (Mocha). Requires an Appium session configured in
 * wdio.conf.js with platformName 'Android', automationName 'UiAutomator2',
 * 'appium:appPackage' = com.example.shop.
 */

const APP_PACKAGE = 'com.example.shop';
// Condition-based wait budget (ms) — poll for the element instead of a fixed
// pause, so specs stay in sync with async UI without flaking at machine speed.
const TIMEOUT = 10000;

// Locate an element, waiting for it to appear and self-healing through ranked
// selectors — each poll tries every selector until one exists or we time out.
async function find(selectors) {
    let found = null;
    await driver.waitUntil(
        async () => {
            for (const selector of selectors) {
                const el = await driver.$(selector);
                if (await el.isExisting()) {
                    found = el;
                    return true;
                }
            }
            return false;
        },
        { timeout: TIMEOUT, interval: 300, timeoutMsg: `No selector matched: ${selectors.join(', ')}` }
    );
    return found;
}

// A generic loading indicator (no app-specific knowledge) — used by settle().
const BUSY = '//android.widget.ProgressBar';

// Middle beat of act -> wait-busy-clears -> assert: after an action that triggers a
// transition, wait for a loading/activity indicator to disappear so the next step
// doesn't act on a mid-transition screen. A no-op when nothing is spinning; a stuck
// indicator is tolerated rather than failing the spec.
async function settle() {
    try {
        await driver.waitUntil(async () => (await driver.$$(BUSY)).length === 0, { timeout: TIMEOUT, interval: 300 });
    } catch (e) {
        // tolerate a persistent indicator
    }
}

describe('CrawlFlow', () => {
    it('welcome_back_screen_shows_expected_controls', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Welcome back is visible
        await expect(await find(['android=new UiSelector().text("Welcome back")'])).toBeDisplayed();
        // Email is visible
        await expect(await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).toBeDisplayed();
        // Email is enabled
        await expect(await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).toBeEnabled();
        // Password is visible
        await expect(await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).toBeDisplayed();
        // Password is enabled
        await expect(await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).toBeEnabled();
        // Remember me is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).toBeDisplayed();
        // Remember me is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).toBeEnabled();
        // Sign in is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).toBeDisplayed();
        // Sign in is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).toBeEnabled();
        // Forgot password? is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'])).toBeDisplayed();
        // Forgot password? is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/forgot")', 'android=new UiSelector().text("Forgot password?")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('search_products_screen_shows_expected_controls', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Navigate: tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Search products is visible
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Search products is enabled
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeEnabled();
        // Running Shoes is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // Running Shoes is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).toBeEnabled();
        // Backpack is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'])).toBeDisplayed();
        // Backpack is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/p_bag")', 'android=new UiSelector().text("Backpack")'])).toBeEnabled();
        // Cart is visible
        await expect(await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).toBeDisplayed();
        // Cart is enabled
        await expect(await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('running_shoes_screen_shows_expected_controls', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Navigate: tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Navigate: tap Running Shoes
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).click();
        await settle();
        // Running Shoes is visible
        await expect(await find(['android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // Add to cart is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).toBeDisplayed();
        // Add to cart is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('your_cart_screen_shows_expected_controls', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Navigate: tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Navigate: tap Cart
        await (await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).click();
        await settle();
        // Your cart is visible
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
        // Place order is visible
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'])).toBeDisplayed();
        // Place order is enabled
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/order")', 'android=new UiSelector().text("Place order")'])).toBeEnabled();
    });
});

describe('CrawlFlow', () => {
    it('tapping_sign_in_opens_search_products', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Destination screen is shown
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
    });
});

describe('CrawlFlow', () => {
    it('journey_from_sign_in_to_add_to_cart', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Type into Email
        await (await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).setValue('test@example.com');
        await settle();
        // Type into Password
        await (await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).setValue('Password123!');
        await settle();
        // Toggle Remember me
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).click();
        await settle();
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Reached screen 2
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Type into Search products
        await (await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).setValue('test');
        await settle();
        // Tap Running Shoes
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/p_shoes")', 'android=new UiSelector().text("Running Shoes")'])).click();
        await settle();
        // Reached screen 3
        await expect(await find(['android=new UiSelector().text("Running Shoes")'])).toBeDisplayed();
        // Tap Add to cart
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/add")', 'android=new UiSelector().text("Add to cart")'])).click();
        await settle();
        // Reached screen 4
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
    });
});

describe('CrawlFlow', () => {
    it('journey_from_sign_in_to_cart', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Type into Email
        await (await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).setValue('test@example.com');
        await settle();
        // Type into Password
        await (await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).setValue('Password123!');
        await settle();
        // Toggle Remember me
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/remember")', 'android=new UiSelector().text("Remember me")'])).click();
        await settle();
        // Tap Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Reached screen 2
        await expect(await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).toBeDisplayed();
        // Type into Search products
        await (await find(['~Search products', 'android=new UiSelector().resourceId("com.example.shop:id/search")'])).setValue('test');
        await settle();
        // Tap Cart
        await (await find(['~Cart', 'android=new UiSelector().resourceId("com.example.shop:id/cart")'])).click();
        await settle();
        // Reached screen 4
        await expect(await find(['android=new UiSelector().text("Your cart")'])).toBeDisplayed();
    });
});

describe('CrawlFlow', () => {
    it('rejects_invalid_input_on_welcome_back', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Type invalid data into Email
        await (await find(['~Email', 'android=new UiSelector().resourceId("com.example.shop:id/email")'])).setValue('not-an-email');
        await settle();
        // Type invalid data into Password
        await (await find(['~Password', 'android=new UiSelector().resourceId("com.example.shop:id/password")'])).setValue('1');
        await settle();
        // Submit Sign in
        await (await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).click();
        await settle();
        // Invalid input is rejected — the form did not advance
        await expect(await find(['android=new UiSelector().resourceId("com.example.shop:id/signin")', 'android=new UiSelector().text("Sign in")'])).toBeDisplayed();
    });
});

