package mobiscout.support

import io.appium.java_client.android.AndroidDriver
import org.junit.jupiter.api.BeforeEach

/**
 * Every test starts from a cold restart of the app on the shared [Session].
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
abstract class BaseTest {

    protected val driver: AndroidDriver
        get() = Session.driver

    @BeforeEach
    fun restartApp() {
        Session.ensureAlive() // a crashed session costs one test, not the rest of the run
        try {
            driver.terminateApp(Session.APP)
        } catch (ignored: RuntimeException) {
            // the app was not running
        }
        driver.activateApp(Session.APP)
    }
}
