package mobiscout.support

import io.appium.java_client.android.AndroidDriver
import io.appium.java_client.android.options.UiAutomator2Options
import java.net.URI

/**
 * The Appium session every test shares.
 *
 * Fast by design: ONE session serves the whole run (opening a session costs 5-10 s), opened on
 * first use and closed when the test JVM exits; the app is cold-restarted before each
 * test (~1-2 s), so every test still begins clean. Run against another Appium server or a cloud
 * grid with `MOBISCOUT_APPIUM_SERVER`.
 *
 * Auto-generated by Mobiscout. Regenerate rather than hand-edit.
 */
object Session {

    const val APP = "com.example.shop"

    private val server = System.getenv("MOBISCOUT_APPIUM_SERVER") ?: "http://localhost:4723"

    private var current: AndroidDriver? = null

    init {
        // Close whatever session is open when the test JVM exits.
        Runtime.getRuntime().addShutdownHook(Thread { close() })
    }

    /** The shared session, opened on first use — and again after [ensureAlive] dropped a dead one. */
    val driver: AndroidDriver
        @Synchronized get() = current ?: open().also { current = it }

    /**
     * Drop the session if it no longer answers (Appium or the driver crashed), so the next
     * [driver] opens a new one: one crash costs one test, not the rest of the run.
     */
    @Synchronized
    fun ensureAlive() {
        val session = current ?: return
        try {
            session.queryAppState(APP)
        } catch (e: RuntimeException) {
            close()
        }
    }

    @Synchronized
    private fun close() {
        try {
            current?.quit()
        } catch (ignored: RuntimeException) {
            // already gone
        }
        current = null
    }

    private fun open(): AndroidDriver {
        val options = UiAutomator2Options()
            .setAppPackage(APP)
            .setAppActivity(".MainActivity")
            .setNoReset(true) // keep app data; each test restarts the app itself
        options.setCapability("appium:disableWindowAnimation", true) // animations only cost time
        return AndroidDriver(URI.create(server).toURL(), options).apply {
            // Don't wait for the UI to go idle after every command: a live app rarely does, and
            // UiAutomator2 would otherwise stall up to 10 s per command.
            setSetting("waitForIdleTimeout", 100)
        }
    }
}
