Feature: Your cart screen
  What the Your cart screen of com.example.shop shows and does.
  Auto-generated by Mobiscout. Regenerate rather than hand-edit.

  Scenario: The your cart screen shows its expected controls
    Given I am on the Your cart screen
    Then I see Place order

  Scenario: The journey from Welcome back through Search products, Running Shoes to Your cart
    Given I am on the Welcome back screen
    When I enter "test@example.com" into Email
    And I enter "Password123!" into Password
    And I tap Remember me
    And I tap Sign in
    Then I see the Search products screen
    When I enter "test" into Search products
    And I tap Running Shoes
    Then I see the Running Shoes screen
    When I tap Add to cart
    Then I see the Your cart screen

  Scenario: The journey from Welcome back through Search products to Your cart
    Given I am on the Welcome back screen
    When I enter "test@example.com" into Email
    And I enter "Password123!" into Password
    And I tap Remember me
    And I tap Sign in
    Then I see the Search products screen
    When I enter "test" into Search products
    And I tap Cart
    Then I see the Your cart screen
