/*
 * LoginFlow — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 *
 * WebdriverIO mobile spec (Mocha). Requires an Appium session configured in
 * wdio.conf.js with platformName 'Android', automationName 'UiAutomator2',
 * 'appium:appPackage' = com.example.app.
 */

const APP_PACKAGE = 'com.example.app';
// Condition-based wait budget (ms) — poll for the element instead of a fixed
// pause, so specs stay in sync with async UI without flaking at machine speed.
const TIMEOUT = 10000;

// Locate an element, waiting for it to appear and self-healing through ranked
// selectors — each poll tries every selector until one exists or we time out.
async function find(selectors) {
    let found = null;
    await driver.waitUntil(
        async () => {
            for (const selector of selectors) {
                const el = await driver.$(selector);
                if (await el.isExisting()) {
                    found = el;
                    return true;
                }
            }
            return false;
        },
        { timeout: TIMEOUT, interval: 300, timeoutMsg: `No selector matched: ${selectors.join(', ')}` }
    );
    return found;
}

describe('LoginFlow', () => {
    it('login', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Enter email
        await (await find(['android=new UiSelector().resourceId("user_field")', '//input[1]'])).setValue('alice@example.com');
        // Tap login
        await (await find(['~login_btn'])).click();
        // Wait for home
        // Condition-based: wait for the screen to render rather than a fixed pause.
        await driver.waitUntil(async () => (await driver.$$('//*')).length > 0, { timeout: 3000, interval: 300 });
        // Dismiss a dialog
        await driver.back();
        // Welcome message shown
        await expect(await find(['android=new UiSelector().text("Welcome")'])).toBeDisplayed();
    });
});

