/*
 * LoginFlow — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 *
 * WebdriverIO mobile spec (Mocha). Requires an Appium session configured in
 * wdio.conf.js with platformName 'Android', automationName 'UiAutomator2',
 * 'appium:appPackage' = com.example.app.
 */

const APP_PACKAGE = 'com.example.app';
// Condition-based wait budget (ms) — poll for the element instead of a fixed
// pause, so specs stay in sync with async UI without flaking at machine speed.
const TIMEOUT = 10000;
// How many times find() scrolls looking for an off-screen element before giving up.
const SCROLL_TRIES = 4;

// One scroll-down gesture — used by find() to bring a below-the-fold element into view.
async function scrollDown() {
    const scrollSize = await driver.getWindowSize();
    await driver.execute('mobile: scrollGesture', { left: Math.round(scrollSize.width * 0.1), top: Math.round(scrollSize.height * 0.2), width: Math.round(scrollSize.width * 0.8), height: Math.round(scrollSize.height * 0.6), direction: 'down', percent: 0.8 });
}

// One pass over the ranked selectors — no waiting.
async function locate(selectors) {
    for (const selector of selectors) {
        const el = await driver.$(selector);
        if (await el.isExisting()) {
            return el;
        }
    }
    return null;
}

// Locate an element, waiting for it to appear and self-healing through ranked
// selectors — each poll tries every selector until one exists or we time out. On a
// miss, scroll and retry: a control below the fold is not a missing control, and the
// same crawl must not pass in one target and fail in another over that.
async function find(selectors) {
    let found = null;
    try {
        await driver.waitUntil(
            async () => {
                found = await locate(selectors);
                return found !== null;
            },
            { timeout: TIMEOUT, interval: 300 }
        );
        return found;
    } catch (e) {
        // not on screen yet — it may just need scrolling into view
    }
    for (let i = 0; i < SCROLL_TRIES; i += 1) {
        await scrollDown();
        found = await locate(selectors);
        if (found) {
            return found;
        }
    }
    throw new Error(`No selector matched within ${TIMEOUT}ms + ${SCROLL_TRIES} scrolls: ${selectors.join(', ')}`);
}

// A generic loading indicator (no app-specific knowledge) — used by settle().
const BUSY = '//android.widget.ProgressBar';

// Middle beat of act -> wait-busy-clears -> assert: after an action that triggers a
// transition, wait for a loading/activity indicator to disappear so the next step
// doesn't act on a mid-transition screen. A no-op when nothing is spinning; a stuck
// indicator is tolerated rather than failing the spec.
async function settle() {
    try {
        await driver.waitUntil(async () => (await driver.$$(BUSY)).length === 0, { timeout: TIMEOUT, interval: 300 });
    } catch (e) {
        // tolerate a persistent indicator
    }
}

// Reset app state before each test so cases stay independent — one WebdriverIO
// session is shared across the file, so without this a test would inherit whatever
// data an earlier test created (e.g. "list is empty" fails after a case that added a
// row). Mirrors the Python/Java/Kotlin kits. Set MOBISCOUT_KEEP_APP_DATA=1 to skip
// it for an app that needs a provisioned account.
async function resetApp() {
    if (process.env.MOBISCOUT_KEEP_APP_DATA === '1') {
        return;
    }
    try {
        await driver.execute('mobile: clearApp', { appId: APP_PACKAGE });
    } catch (e) {
        // clearApp isn't supported by every driver/version — tolerate and rely on relaunch.
    }
    await driver.activateApp(APP_PACKAGE);
}

describe('LoginFlow', () => {
    beforeEach(resetApp);
    it('login', async () => {
        // Open app
        await driver.activateApp(APP_PACKAGE);
        // Enter email
        await (await find(['android=new UiSelector().resourceId("user_field")', '//input[1]'])).setValue('alice@example.com');
        await settle();
        // Tap login
        await (await find(['~login_btn'])).click();
        await settle();
        // Wait for home
        // Condition-based: wait for the screen to render rather than a fixed pause.
        await driver.waitUntil(async () => (await driver.$$('//*')).length > 0, { timeout: 3000, interval: 300 });
        // Swipe up to reveal content
        {
            const swipeSize = await driver.getWindowSize();
            await driver.execute('mobile: swipeGesture', { left: Math.round(swipeSize.width * 0.1), top: Math.round(swipeSize.height * 0.1), width: Math.round(swipeSize.width * 0.8), height: Math.round(swipeSize.height * 0.8), direction: 'up', percent: 0.75 });
        }
        await settle();
        // Dismiss a dialog
        await driver.back();
        await settle();
        // Welcome message shown
        await expect(await find(['android=new UiSelector().text("Welcome")'])).toBeDisplayed();
    });
});

