"""
CrawlFlow — auto-generated by Mobile Test Recorder.
Auto-generated from an autonomous crawl (state + navigation).
App under test: com.example.shop
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException


def _find(driver, primary, fallbacks):
    """Locate an element, falling back through ranked alternatives (self-healing)."""
    for by, value in [primary, *fallbacks]:
        try:
            return driver.find_element(by, value)
        except NoSuchElementException:
            continue
    by, value = primary
    raise NoSuchElementException(f"None of the locators matched (primary + {len(fallbacks)} fallbacks): {by}={value}")


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = "com.example.shop"
    options.app_activity = ".MainActivity"
    drv = webdriver.Remote("http://localhost:4723", options=options)
    yield drv
    drv.quit()


def test_screen_1_state(driver):
    """State checks for discovered screen 1"""
    # Open app
    driver.activate_app("com.example.shop")
    # Welcome back is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Welcome back")'), []).is_displayed()
    # Email is visible
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]
    ).is_displayed()
    # Email is enabled
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]
    ).is_enabled()
    # Password is visible
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]
    ).is_displayed()
    # Password is enabled
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]
    ).is_enabled()
    # Remember me is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/remember"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Remember me")')],
    ).is_displayed()
    # Remember me is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/remember"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Remember me")')],
    ).is_enabled()
    # Sign in is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/signin"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Sign in")')],
    ).is_displayed()
    # Sign in is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/signin"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Sign in")')],
    ).is_enabled()
    # Forgot password? is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/forgot"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Forgot password?")')],
    ).is_displayed()
    # Forgot password? is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/forgot"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Forgot password?")')],
    ).is_enabled()


def test_screen_2_state(driver):
    """State checks for discovered screen 2"""
    # Open app
    driver.activate_app("com.example.shop")
    # Search products is visible
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).is_displayed()
    # Search products is enabled
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).is_enabled()
    # Running Shoes is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/p_shoes"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Running Shoes")')],
    ).is_displayed()
    # Running Shoes is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/p_shoes"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Running Shoes")')],
    ).is_enabled()
    # Backpack is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/p_bag"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Backpack")')],
    ).is_displayed()
    # Backpack is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/p_bag"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Backpack")')],
    ).is_enabled()
    # Cart is visible
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]
    ).is_displayed()
    # Cart is enabled
    assert _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).is_enabled()


def test_screen_3_state(driver):
    """State checks for discovered screen 3"""
    # Open app
    driver.activate_app("com.example.shop")
    # Running Shoes is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Running Shoes")'), []).is_displayed()
    # $89.00 is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("$89.00")'), []).is_displayed()
    # Add to cart is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/add"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Add to cart")')],
    ).is_displayed()
    # Add to cart is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/add"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Add to cart")')],
    ).is_enabled()


def test_screen_4_state(driver):
    """State checks for discovered screen 4"""
    # Open app
    driver.activate_app("com.example.shop")
    # Your cart is visible
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Your cart")'), []).is_displayed()
    # Place order is visible
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/order"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Place order")')],
    ).is_displayed()
    # Place order is enabled
    assert _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/order"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Place order")')],
    ).is_enabled()


def test_navigate_1(driver):
    """Tapping Sign in navigates onward"""
    # Open app
    driver.activate_app("com.example.shop")
    # Tap Sign in
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/signin"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Sign in")')],
    ).click()
    # Destination screen is shown
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).is_displayed()


def test_path_1_2_3_4(driver):
    """Multi-step path (4 screens): screen 1 → screen 2 → screen 3 → screen 4"""
    # Open app
    driver.activate_app("com.example.shop")
    # Type into Email
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).send_keys(
        "test@example.com"
    )
    # Type into Password
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).send_keys(
        "Password123!"
    )
    # Toggle Remember me
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/remember"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Remember me")')],
    ).click()
    # Tap Sign in
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/signin"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Sign in")')],
    ).click()
    # Reached screen 2
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).is_displayed()
    # Type into Search products
    _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).send_keys("test")
    # Tap Running Shoes
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/p_shoes"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Running Shoes")')],
    ).click()
    # Reached screen 3
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Running Shoes")'), []).is_displayed()
    # Tap Add to cart
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/add"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Add to cart")')],
    ).click()
    # Reached screen 4
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Your cart")'), []).is_displayed()


def test_path_1_2_4(driver):
    """Multi-step path (3 screens): screen 1 → screen 2 → screen 4"""
    # Open app
    driver.activate_app("com.example.shop")
    # Type into Email
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Email"), [(AppiumBy.ID, "com.example.shop:id/email")]).send_keys(
        "test@example.com"
    )
    # Type into Password
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Password"), [(AppiumBy.ID, "com.example.shop:id/password")]).send_keys(
        "Password123!"
    )
    # Toggle Remember me
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/remember"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Remember me")')],
    ).click()
    # Tap Sign in
    _find(
        driver,
        (AppiumBy.ID, "com.example.shop:id/signin"),
        [(AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Sign in")')],
    ).click()
    # Reached screen 2
    assert _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).is_displayed()
    # Type into Search products
    _find(
        driver, (AppiumBy.ACCESSIBILITY_ID, "Search products"), [(AppiumBy.ID, "com.example.shop:id/search")]
    ).send_keys("test")
    # Tap Cart
    _find(driver, (AppiumBy.ACCESSIBILITY_ID, "Cart"), [(AppiumBy.ID, "com.example.shop:id/cart")]).click()
    # Reached screen 4
    assert _find(driver, (AppiumBy.ANDROID_UIAUTOMATOR, 'new UiSelector().text("Your cart")'), []).is_displayed()
