/*
 * LoginFlow — auto-generated by Mobiscout.
 * Generated login flow used for golden tests.
 * App under test: com.example.app
 * DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
 */
package mobiscout;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.options.UiAutomator2Options;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.URL;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class LoginFlow {

    private AppiumDriver driver;

    // Run anywhere without regenerating: point at a different Appium/cloud-grid
    // hub with MOBISCOUT_APPIUM_SERVER.
    private static final String SERVER =
        System.getenv().getOrDefault("MOBISCOUT_APPIUM_SERVER", "http://localhost:4723");

    @BeforeMethod
    public void setUp() throws Exception {
        UiAutomator2Options options = new UiAutomator2Options();
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        options.setAppPackage("com.example.app");
        options.setAppActivity(".MainActivity");
        driver = new AndroidDriver(new URL(SERVER), options);
    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }

    /** Condition-based wait budget for locating elements. */
    private static final Duration TIMEOUT = Duration.ofSeconds(10);
    /** How many times find() scrolls looking for an off-screen element before giving up. */
    private static final int SCROLL_TRIES = 4;

    /** One pass over the ranked locators — no waiting. */
    private static WebElement locate(org.openqa.selenium.SearchContext context, List<By> locators) {
        for (By by : locators) {
            try {
                return context.findElement(by);
            } catch (NoSuchElementException ignored) {
            }
        }
        return null;
    }

    /**
     * One scroll-down gesture — used by find() to bring a below-the-fold element into view.
     */
    private void scrollDown() {
        org.openqa.selenium.Dimension scrollSize = driver.manage().window().getSize();
        java.util.Map<String, Object> scrollArgs = new java.util.HashMap<>();
        scrollArgs.put("left", (int) (scrollSize.getWidth() * 0.1));
        scrollArgs.put("top", (int) (scrollSize.getHeight() * 0.2));
        scrollArgs.put("width", (int) (scrollSize.getWidth() * 0.8));
        scrollArgs.put("height", (int) (scrollSize.getHeight() * 0.6));
        scrollArgs.put("direction", "down");
        scrollArgs.put("percent", 0.8);
        driver.executeScript("mobile: scrollGesture", scrollArgs);
    }

    /**
     * Locate an element, waiting for it to appear and self-healing through ranked
     * alternatives — each poll tries every locator until one resolves or we time
     * out. A real condition-based wait, not an instant lookup that flakes on async UI.
     * On a miss, scroll and retry: a control below the fold is not a missing control,
     * and the same crawl must not pass in one target and fail in another over that.
     */
    private WebElement find(By primary, By[] fallbacks) {
        List<By> locators = new ArrayList<>();
        locators.add(primary);
        locators.addAll(Arrays.asList(fallbacks));
        try {
            return new WebDriverWait(driver, TIMEOUT).until(d -> locate(d, locators));
        } catch (TimeoutException ignored) {
        }
        for (int i = 0; i < SCROLL_TRIES; i++) {
            scrollDown();
            WebElement found = locate(driver, locators);
            if (found != null) {
                return found;
            }
        }
        throw new NoSuchElementException(
            "No locator matched within " + TIMEOUT.getSeconds() + "s + " + SCROLL_TRIES
                + " scrolls (primary + " + fallbacks.length + " fallbacks)");
    }

    /** A generic loading indicator (no app-specific knowledge) — used by settle(). */
    private static final String BUSY_XPATH = "//android.widget.ProgressBar";

    /**
     * Middle beat of {@code act -> wait-busy-clears -> assert}: after an action that
     * triggers a transition, wait for a loading/activity indicator to disappear so the
     * next step doesn't act on a mid-transition screen. A no-op when nothing is
     * spinning; a stuck indicator is tolerated, not failed.
     */
    private void settle() {
        try {
            new WebDriverWait(driver, TIMEOUT).until(d -> d.findElements(By.xpath(BUSY_XPATH)).isEmpty());
        } catch (TimeoutException ignored) {
        }
        // A raised soft keyboard is a transient input surface, not part of the screen under
        // test: with adjustResize it shrinks the layout and can drop a bottom-anchored control
        // (a FAB) out of the accessibility tree, and an IME-occluded control reports
        // isDisplayed() == false. Both flake the next assert on a control that belongs to the
        // screen. Dismiss it so the screen settles deterministically; best-effort.
        try {
            io.appium.java_client.android.AndroidDriver androidDriver =
                (io.appium.java_client.android.AndroidDriver) driver;
            if (androidDriver.isKeyboardShown()) {
                androidDriver.hideKeyboard();
            }
        } catch (Exception ignored) {
        }
    }

    @Test
    public void login() {
        // Open app
        driver.activateApp("com.example.app");
        // Enter email
        find(AppiumBy.id("user_field"), new By[]{AppiumBy.xpath("//input[1]")}).sendKeys("alice@example.com");
        settle();
        // Tap login
        find(AppiumBy.accessibilityId("login_btn"), new By[]{}).click();
        settle();
        // Wait for home
        // Condition-based: wait for the screen to render rather than a global implicit wait.
        new WebDriverWait(driver, Duration.ofSeconds(3)).until(d -> !d.findElements(By.xpath("//*")).isEmpty());
        // Swipe up to reveal content
        {
            org.openqa.selenium.Dimension swipeSize = driver.manage().window().getSize();
            java.util.Map<String, Object> swipeArgs = new java.util.HashMap<>();
            swipeArgs.put("left", (int) (swipeSize.getWidth() * 0.1));
            swipeArgs.put("top", (int) (swipeSize.getHeight() * 0.1));
            swipeArgs.put("width", (int) (swipeSize.getWidth() * 0.8));
            swipeArgs.put("height", (int) (swipeSize.getHeight() * 0.8));
            swipeArgs.put("direction", "up");
            swipeArgs.put("percent", 0.75);
            driver.executeScript("mobile: swipeGesture", swipeArgs);
        }
        settle();
        // Dismiss a dialog
        driver.navigate().back();
        settle();
        // Welcome message shown
        Assert.assertTrue(find(AppiumBy.androidUIAutomator("new UiSelector().text(\"Welcome\")"), new By[]{}).isDisplayed());
    }

}
