"""
Step definitions for CrawlFlow — auto-generated by Mobile Test Recorder.

Generic, reusable pytest-bdd steps. Element targets are resolved through the
LOCATORS registry below (primary locator + ranked fallbacks for self-healing),
so the .feature file stays free of locator detail.
DO NOT EDIT BY HAND — regenerate from the recorded flow instead.
"""

import pytest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import NoSuchElementException
from pytest_bdd import given, when, then, parsers, scenarios

scenarios("features/crawl_flow.feature")

APP_PACKAGE = "com.example.shop"
APP_ACTIVITY = ".MainActivity"

# Friendly target name -> ranked locators (primary first, then fallbacks).
LOCATORS = {
    "Welcome back": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Welcome back\")")],
    "Email": [(AppiumBy.ACCESSIBILITY_ID, "Email"), (AppiumBy.ID, "com.example.shop:id/email")],
    "Password": [(AppiumBy.ACCESSIBILITY_ID, "Password"), (AppiumBy.ID, "com.example.shop:id/password")],
    "Remember me": [(AppiumBy.ID, "com.example.shop:id/remember"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Remember me\")")],
    "Sign in": [(AppiumBy.ID, "com.example.shop:id/signin"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Sign in\")")],
    "Search products": [(AppiumBy.ACCESSIBILITY_ID, "Search products"), (AppiumBy.ID, "com.example.shop:id/search")],
    "Running Shoes": [(AppiumBy.ID, "com.example.shop:id/p_shoes"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Running Shoes\")")],
    "Backpack": [(AppiumBy.ID, "com.example.shop:id/p_bag"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Backpack\")")],
    "Cart": [(AppiumBy.ACCESSIBILITY_ID, "Cart"), (AppiumBy.ID, "com.example.shop:id/cart")],
    "Add to cart": [(AppiumBy.ID, "com.example.shop:id/add"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Add to cart\")")],
    "Your cart": [(AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Your cart\")")],
    "Place order": [(AppiumBy.ID, "com.example.shop:id/order"), (AppiumBy.ANDROID_UIAUTOMATOR, "new UiSelector().text(\"Place order\")")],
}


def _find(driver, target):
    """Resolve a friendly target to an element via its ranked locators."""
    for by, value in LOCATORS[target]:
        try:
            return driver.find_element(by, value)
        except NoSuchElementException:
            continue
    raise NoSuchElementException(f"No locator matched for target: {target!r}")


@pytest.fixture()
def driver():
    options = UiAutomator2Options()
    options.platform_name = "Android"
    options.automation_name = "UiAutomator2"
    options.app_package = APP_PACKAGE
    options.app_activity = APP_ACTIVITY
    drv = webdriver.Remote("http://localhost:4723", options=options)
    yield drv
    drv.quit()


@given("the app is launched")
def _launch(driver):
    driver.activate_app(APP_PACKAGE)


@when(parsers.parse('I enter "{text}" into "{target}"'))
def _enter(driver, text, target):
    _find(driver, target).send_keys(text)


@when(parsers.parse('I tap "{target}"'))
def _tap(driver, target):
    _find(driver, target).click()


@when(parsers.parse("I wait {seconds:d} seconds"))
def _wait(driver, seconds):
    driver.implicitly_wait(seconds)


@when("I press back")
def _back(driver):
    driver.back()


@then(parsers.parse('"{target}" is visible'))
def _visible(driver, target):
    assert _find(driver, target).is_displayed()


@then(parsers.parse('"{target}" text is "{expected}"'))
def _text_equals(driver, target, expected):
    assert _find(driver, target).text == expected


@then(parsers.parse('"{target}" is enabled'))
def _enabled(driver, target):
    assert _find(driver, target).is_enabled()
